// Code generated by admgen; DO NOT EDIT.
// Source: apple/device-management@67045e2fa06f528b196c01edee6a8bf88b844beb

package status

import (
	"encoding/json"
)

// AccountListCalDAV: A status report of the client's Calendar accounts.
//
// AccountListCalDAV corresponds to declarative/status/account.list.caldav.yaml (Status Account List CalDAV).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type AccountListCalDAV struct {
	// A list of status values for the Calendar accounts.
	Value []AccountListCalDAVAccount `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x AccountListCalDAV) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *AccountListCalDAV) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, &x.Value) }

// SchemaPath returns the Apple schema file this type was generated from.
func (*AccountListCalDAV) SchemaPath() string { return "declarative/status/account.list.caldav.yaml" }

// AccountListCalDAVAccount: A status report of the client's Calendar account details.
type AccountListCalDAVAccount struct {
	// The unique identifier for the account.
	Identifier string `plist:"identifier" json:"identifier"`
	// If `true`, the account is removed and the status item object only contains this key and
	// the `identifier` key.
	Removed *bool `plist:"_removed,omitempty" json:"_removed,omitempty"`
	// The identifier of the declaration that installed the account. Only present if a
	// declaration installed the account.
	DeclarationIdentifier *string `plist:"declaration-identifier,omitempty" json:"declaration-identifier,omitempty"`
	// The name of the account.
	VisibleName *string `plist:"visible-name,omitempty" json:"visible-name,omitempty"`
	// The server host name for the account.
	Hostname *string `plist:"hostname,omitempty" json:"hostname,omitempty"`
	// The server port for the account.
	Port *int64 `plist:"port,omitempty" json:"port,omitempty"`
	// The user name for the account.
	Username *string `plist:"username,omitempty" json:"username,omitempty"`
	// If `true`, the Calendar app is displaying calendars and events for the account.
	AreCalendarsEnabled *bool `plist:"are-calendars-enabled,omitempty" json:"are-calendars-enabled,omitempty"`
	// If `true`, the Reminders app is displaying reminders for the account.
	AreRemindersEnabled *bool `plist:"are-reminders-enabled,omitempty" json:"are-reminders-enabled,omitempty"`
}

// AccountListCardDAV: A status report of the client's Contacts accounts.
//
// AccountListCardDAV corresponds to declarative/status/account.list.carddav.yaml (Status Account List CardDAV).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type AccountListCardDAV struct {
	// A list of status values for the Contacts accounts.
	Value []AccountListCardDAVAccount `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x AccountListCardDAV) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *AccountListCardDAV) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, &x.Value) }

// SchemaPath returns the Apple schema file this type was generated from.
func (*AccountListCardDAV) SchemaPath() string { return "declarative/status/account.list.carddav.yaml" }

// AccountListCardDAVAccount: A status report of the client's Contacts account details.
type AccountListCardDAVAccount struct {
	// The unique identifier for the account.
	Identifier string `plist:"identifier" json:"identifier"`
	// If `true`, the account is removed and the status item object only contains this key and
	// the `identifier` key.
	Removed *bool `plist:"_removed,omitempty" json:"_removed,omitempty"`
	// The identifier of the declaration that installed the account. Only present if a
	// declaration installed the account.
	DeclarationIdentifier *string `plist:"declaration-identifier,omitempty" json:"declaration-identifier,omitempty"`
	// The name of the account.
	VisibleName *string `plist:"visible-name,omitempty" json:"visible-name,omitempty"`
	// The server host name for the account.
	Hostname *string `plist:"hostname,omitempty" json:"hostname,omitempty"`
	// The server port for the account.
	Port *int64 `plist:"port,omitempty" json:"port,omitempty"`
	// The user name for the account.
	Username *string `plist:"username,omitempty" json:"username,omitempty"`
}

// AccountListExchange: A status report of the client's Exchange accounts.
//
// AccountListExchange corresponds to declarative/status/account.list.exchange.yaml (Status Account List Exchange).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type AccountListExchange struct {
	// A list of status values for the Exchange accounts.
	Value []AccountListExchangeAccount `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x AccountListExchange) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *AccountListExchange) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, &x.Value) }

// SchemaPath returns the Apple schema file this type was generated from.
func (*AccountListExchange) SchemaPath() string {
	return "declarative/status/account.list.exchange.yaml"
}

// AccountListExchangeAccount: A status report of the client's Exchange account details.
type AccountListExchangeAccount struct {
	// The unique identifier for the account.
	Identifier string `plist:"identifier" json:"identifier"`
	// If `true`, the account is removed and the status item object only contains this key and
	// the `identifier` key.
	Removed *bool `plist:"_removed,omitempty" json:"_removed,omitempty"`
	// The identifier of the declaration that installed the account. Only present if a
	// declaration installed the account.
	DeclarationIdentifier *string `plist:"declaration-identifier,omitempty" json:"declaration-identifier,omitempty"`
	// The name of the account.
	VisibleName *string `plist:"visible-name,omitempty" json:"visible-name,omitempty"`
	// The server host name for the account.
	Hostname *string `plist:"hostname,omitempty" json:"hostname,omitempty"`
	// The server port for the account.
	Port *int64 `plist:"port,omitempty" json:"port,omitempty"`
	// The user name for the account.
	Username *string `plist:"username,omitempty" json:"username,omitempty"`
	// A Boolean value that indicates whether the Mail app displays mail for this account.
	IsMailEnabled *bool `plist:"is-mail-enabled,omitempty" json:"is-mail-enabled,omitempty"`
	// A Boolean value that indicates whether the Calendar app displays calendars and events
	// for this account.
	AreCalendarsEnabled *bool `plist:"are-calendars-enabled,omitempty" json:"are-calendars-enabled,omitempty"`
	// A Boolean value that indicates whether the Contacts app displays contacts for this
	// account.
	AreContactsEnabled *bool `plist:"are-contacts-enabled,omitempty" json:"are-contacts-enabled,omitempty"`
	// A Boolean value that indicates whether the Notes app displays notes for this account.
	AreNotesEnabled *bool `plist:"are-notes-enabled,omitempty" json:"are-notes-enabled,omitempty"`
	// A Boolean value that indicates whether the Reminders app displays reminders for this
	// account.
	AreRemindersEnabled *bool `plist:"are-reminders-enabled,omitempty" json:"are-reminders-enabled,omitempty"`
}

// AccountListGoogle: A status report of the client's Google accounts.
//
// AccountListGoogle corresponds to declarative/status/account.list.google.yaml (Status Account List Google).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type AccountListGoogle struct {
	// A list of status values for the Google accounts.
	Value []AccountListGoogleAccount `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x AccountListGoogle) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *AccountListGoogle) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, &x.Value) }

// SchemaPath returns the Apple schema file this type was generated from.
func (*AccountListGoogle) SchemaPath() string { return "declarative/status/account.list.google.yaml" }

// AccountListGoogleAccount: A status report of the client's Google account details.
type AccountListGoogleAccount struct {
	// The unique identifier for the account.
	Identifier string `plist:"identifier" json:"identifier"`
	// If `true`, the account is removed and the status item object only contains this key and
	// the `identifier` key.
	Removed *bool `plist:"_removed,omitempty" json:"_removed,omitempty"`
	// The identifier of the declaration that installed the account. Only present if a
	// declaration installed the account.
	DeclarationIdentifier *string `plist:"declaration-identifier,omitempty" json:"declaration-identifier,omitempty"`
	// The name of the account.
	VisibleName *string `plist:"visible-name,omitempty" json:"visible-name,omitempty"`
	// The user name for the account.
	Username *string `plist:"username,omitempty" json:"username,omitempty"`
	// A Boolean value that indicates whether the Mail app displays mail for this account.
	IsMailEnabled *bool `plist:"is-mail-enabled,omitempty" json:"is-mail-enabled,omitempty"`
	// A Boolean value that indicates whether the Calendar app displays calendars and events
	// for this account.
	AreCalendarsEnabled *bool `plist:"are-calendars-enabled,omitempty" json:"are-calendars-enabled,omitempty"`
	// A Boolean value that indicates whether the Contacts app displays contacts for this
	// account.
	AreContactsEnabled *bool `plist:"are-contacts-enabled,omitempty" json:"are-contacts-enabled,omitempty"`
	// A Boolean value that indicates whether the Notes app displays notes for this account.
	AreNotesEnabled *bool `plist:"are-notes-enabled,omitempty" json:"are-notes-enabled,omitempty"`
}

// AccountListLDAP: A status report of the client's Lightweight Directory Access Protocol
// (LDAP) accounts.
//
// AccountListLDAP corresponds to declarative/status/account.list.ldap.yaml (Status Account List LDAP).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type AccountListLDAP struct {
	// A list of status values for the LDAP accounts.
	Value []AccountListLDAPAccount `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x AccountListLDAP) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *AccountListLDAP) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, &x.Value) }

// SchemaPath returns the Apple schema file this type was generated from.
func (*AccountListLDAP) SchemaPath() string { return "declarative/status/account.list.ldap.yaml" }

// AccountListLDAPAccount: A status report of the client's LDAP account details.
type AccountListLDAPAccount struct {
	// The unique identifier for the account.
	Identifier string `plist:"identifier" json:"identifier"`
	// If `true`, the account is removed and the status item object only contains this key and
	// the `identifier` key.
	Removed *bool `plist:"_removed,omitempty" json:"_removed,omitempty"`
	// The identifier of the declaration that installed the account. Only present if a
	// declaration installed the account.
	DeclarationIdentifier *string `plist:"declaration-identifier,omitempty" json:"declaration-identifier,omitempty"`
	// The name of the account.
	VisibleName *string `plist:"visible-name,omitempty" json:"visible-name,omitempty"`
	// The server host name for the account.
	Hostname *string `plist:"hostname,omitempty" json:"hostname,omitempty"`
	// The server port for the account.
	Port *int64 `plist:"port,omitempty" json:"port,omitempty"`
	// The user name for the account.
	Username *string `plist:"username,omitempty" json:"username,omitempty"`
	// A Boolean value that indicates whether the account is enabled for use with the Contacts
	// app.
	IsEnabled *bool `plist:"is-enabled,omitempty" json:"is-enabled,omitempty"`
}

// AccountListMailIncoming: A status report of the client's incoming Mail accounts.
//
// AccountListMailIncoming corresponds to declarative/status/account.list.mail.incoming.yaml (Status Account List Mail Incoming).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type AccountListMailIncoming struct {
	// A list of status values for the incoming Mail accounts.
	Value []AccountListMailIncomingAccount `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x AccountListMailIncoming) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *AccountListMailIncoming) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*AccountListMailIncoming) SchemaPath() string {
	return "declarative/status/account.list.mail.incoming.yaml"
}

// AccountListMailIncomingAccount: A status report of the client's incoming Mail account
// details.
type AccountListMailIncomingAccount struct {
	// The unique identifier for the account.
	Identifier string `plist:"identifier" json:"identifier"`
	// If `true`, the account is removed and the status item object only contains this key and
	// the `identifier` key.
	Removed *bool `plist:"_removed,omitempty" json:"_removed,omitempty"`
	// The identifier of the declaration that installed the account. Only present if a
	// declaration installed the account.
	DeclarationIdentifier *string `plist:"declaration-identifier,omitempty" json:"declaration-identifier,omitempty"`
	// The name of the account.
	VisibleName *string `plist:"visible-name,omitempty" json:"visible-name,omitempty"`
	// The server host name for the account.
	Hostname *string `plist:"hostname,omitempty" json:"hostname,omitempty"`
	// The server port for the account.
	Port *int64 `plist:"port,omitempty" json:"port,omitempty"`
	// The user name for the account.
	Username *string `plist:"username,omitempty" json:"username,omitempty"`
	// A Boolean value that indicates whether the Mail app displays mail for this account.
	IsMailEnabled *bool `plist:"is-mail-enabled,omitempty" json:"is-mail-enabled,omitempty"`
	// A Boolean value that indicates whether the Notes app displays notes for this account.
	AreNotesEnabled *bool `plist:"are-notes-enabled,omitempty" json:"are-notes-enabled,omitempty"`
}

// AccountListMailOutgoing: A status report of the client's outgoing Mail accounts.
//
// AccountListMailOutgoing corresponds to declarative/status/account.list.mail.outgoing.yaml (Status Account List Mail Outgoing).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type AccountListMailOutgoing struct {
	// A list of status values for the outgoing Mail accounts.
	Value []AccountListMailOutgoingAccount `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x AccountListMailOutgoing) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *AccountListMailOutgoing) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*AccountListMailOutgoing) SchemaPath() string {
	return "declarative/status/account.list.mail.outgoing.yaml"
}

// AccountListMailOutgoingAccount: A status report of the client's outgoing Mail account
// details.
type AccountListMailOutgoingAccount struct {
	// The unique identifier for the account.
	Identifier string `plist:"identifier" json:"identifier"`
	// If `true`, the account is removed and the status item object only contains this key and
	// the `identifier` key.
	Removed *bool `plist:"_removed,omitempty" json:"_removed,omitempty"`
	// The identifier of the declaration that installed the account. Only present if a
	// declaration installed the account.
	DeclarationIdentifier *string `plist:"declaration-identifier,omitempty" json:"declaration-identifier,omitempty"`
	// The name of the account.
	VisibleName *string `plist:"visible-name,omitempty" json:"visible-name,omitempty"`
	// The server host name for the account.
	Hostname *string `plist:"hostname,omitempty" json:"hostname,omitempty"`
	// The server port for the account.
	Port *int64 `plist:"port,omitempty" json:"port,omitempty"`
	// The user name for the account.
	Username *string `plist:"username,omitempty" json:"username,omitempty"`
}

// AccountListSubscribedCalendar: A status report of the client's subscribed calendars.
//
// AccountListSubscribedCalendar corresponds to declarative/status/account.list.subscribed-calendar.yaml (Status Account List Subscribed Calendar).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type AccountListSubscribedCalendar struct {
	// A list of status values for the subscribed calendars.
	Value []AccountListSubscribedCalendarAccount `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x AccountListSubscribedCalendar) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *AccountListSubscribedCalendar) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*AccountListSubscribedCalendar) SchemaPath() string {
	return "declarative/status/account.list.subscribed-calendar.yaml"
}

// AccountListSubscribedCalendarAccount: A status report of the client's subscribed calendar
// details.
type AccountListSubscribedCalendarAccount struct {
	// The unique identifier for the subscribed calendar.
	Identifier string `plist:"identifier" json:"identifier"`
	// If `true`, the subscribed calendar is removed and the status item object only contains
	// this key and the `identifier` key.
	Removed *bool `plist:"_removed,omitempty" json:"_removed,omitempty"`
	// The identifier of the declaration that installed the subscribed calendar. Only present
	// if a declaration installed the subscribed calendar.
	DeclarationIdentifier *string `plist:"declaration-identifier,omitempty" json:"declaration-identifier,omitempty"`
	// The name of the subscribed calendar.
	VisibleName *string `plist:"visible-name,omitempty" json:"visible-name,omitempty"`
	// The URL of the subscribed calendar.
	CalendarUrl *string `plist:"calendar-url,omitempty" json:"calendar-url,omitempty"`
	// The user name for authenticating with the subscribed calendar.
	Username *string `plist:"username,omitempty" json:"username,omitempty"`
	// A Boolean value that indicates whether the Calendar app displays this subscribed
	// calendar.
	IsEnabled *bool `plist:"is-enabled,omitempty" json:"is-enabled,omitempty"`
}

// AppManagedList: The device's declarative managed apps.
//
// AppManagedList corresponds to declarative/status/app.managed.list.yaml (Status App Managed List).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type AppManagedList struct {
	// An array of dictionaries that describe the device's declarative managed apps.
	Value []AppManagedListApp `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x AppManagedList) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *AppManagedList) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, &x.Value) }

// SchemaPath returns the Apple schema file this type was generated from.
func (*AppManagedList) SchemaPath() string { return "declarative/status/app.managed.list.yaml" }

// AppManagedListApp: A dictionary that describes a declarative managed app.
type AppManagedListApp struct {
	// The app's bundle id, which is unique.
	Identifier string `plist:"identifier" json:"identifier"`
	// If `true`, the system removed the app and only this key and the `identifier` key are
	// present in the status item object.
	Removed *bool `plist:"_removed,omitempty" json:"_removed,omitempty"`
	// The identifier of the declaration that controls the app.
	DeclarationIdentifier *string `plist:"declaration-identifier,omitempty" json:"declaration-identifier,omitempty"`
	// The name of the app.
	Name *string `plist:"name,omitempty" json:"name,omitempty"`
	// The app's external version identifier. You can also retrieve this value from the App
	// Store. For more information, see `Apps and Books for Organizations`.
	ExternalVersionId *int64 `plist:"external-version-id,omitempty" json:"external-version-id,omitempty"`
	// The version of the app.
	Version *string `plist:"version,omitempty" json:"version,omitempty"`
	// The short version of the app.
	ShortVersion *string `plist:"short-version,omitempty" json:"short-version,omitempty"`
	// The status of the app, which has the following possible values:
	State *string `plist:"state,omitempty" json:"state,omitempty"`
	// The update status of the app, which has the following possible values:
	UpdateState *string `plist:"update-state,omitempty" json:"update-state,omitempty"`
	// The status of app or extension managed configurations. This key is only present when
	// managed configurations are available for the managed app or any of its extensions.
	ConfigState *AppManagedListManagedConfiguration `plist:"config-state,omitempty" json:"config-state,omitempty"`
	// An array that contains additional details about the app state, including errors.
	Reasons []AppManagedListStatusReason `plist:"reasons,omitempty" json:"reasons,omitempty"`
}

// AppManagedListManagedConfiguration: The status of app or extension managed configurations.
// This key is only present when managed configurations are available for the managed app or
// any of its extensions.
type AppManagedListManagedConfiguration struct {
	// The status of any app managed configuration. This key is only present when the managed
	// app has a managed configuration.
	AppConfigState *AppManagedListManagedConfigurationState `plist:"app-config-state,omitempty" json:"app-config-state,omitempty"`
	// The status of any app extension managed configuration. This key's value is a dictionary
	// whose keys are the bundle identifiers of app extensions that have a managed
	// configuration. The values of each key represent the status of the corresponding app
	// extension's managed configuration.
	ExtensionConfigState map[string]AppManagedListManagedConfigurationState `plist:"extension-config-state,omitempty" json:"extension-config-state,omitempty"`
}

// AppManagedListManagedConfigurationState: The status of any app managed configuration. This
// key is only present when the managed app has a managed configuration.
type AppManagedListManagedConfigurationState struct {
	// The managed configuration status. - `unknown`: The managed configuration has not been
	// read - `invalid`: The managed configuration was read and deemed to be invalid - `valid`:
	// The managed configuration was read and deemed to be valid
	State string `plist:"state" json:"state"`
}

// AppManagedListStatusReason: Information about a status error.
type AppManagedListStatusReason struct {
	// A code for the state.
	Code string `plist:"code" json:"code"`
	// A description of the state.
	Description *string `plist:"description,omitempty" json:"description,omitempty"`
	// A dictionary that contains additional details about the state.
	Details map[string]any `plist:"details,omitempty" json:"details,omitempty"`
}

// DeviceSerialNumber: A status report of the device's serial number.
//
// DeviceSerialNumber corresponds to declarative/status/device.identifier.serial-number.yaml (Status Device Serial Number).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type DeviceSerialNumber struct {
	// The device's serial number.
	Value string `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x DeviceSerialNumber) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *DeviceSerialNumber) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, &x.Value) }

// SchemaPath returns the Apple schema file this type was generated from.
func (*DeviceSerialNumber) SchemaPath() string {
	return "declarative/status/device.identifier.serial-number.yaml"
}

// DeviceUDID: A status report of the device's UDID.
//
// DeviceUDID corresponds to declarative/status/device.identifier.udid.yaml (Status Device UDID).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type DeviceUDID struct {
	// The device's UDID. This value is always available on the device channel. This value is
	// only available on user channels whose organization matches that of the device channel.
	Value string `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x DeviceUDID) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *DeviceUDID) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, &x.Value) }

// SchemaPath returns the Apple schema file this type was generated from.
func (*DeviceUDID) SchemaPath() string { return "declarative/status/device.identifier.udid.yaml" }

// DeviceModelFamily: A status report of the device's hardware family.
//
// DeviceModelFamily corresponds to declarative/status/device.model.family.yaml (Status Device Model Family).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type DeviceModelFamily struct {
	// The hardware family of the device, such as `Mac`, `iPhone`, or `iPad`.
	Value string `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x DeviceModelFamily) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *DeviceModelFamily) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, &x.Value) }

// SchemaPath returns the Apple schema file this type was generated from.
func (*DeviceModelFamily) SchemaPath() string { return "declarative/status/device.model.family.yaml" }

// DeviceModelIdentifier: A status report of the device's hardware identifier.
//
// DeviceModelIdentifier corresponds to declarative/status/device.model.identifier.yaml (Status Device Model Identifier).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type DeviceModelIdentifier struct {
	// A two-part string that specifies the device's model. The first part specifies device's
	// model family, and the second part specifies the model's version. The model's version is
	// a comma-separated number where the first part of the number is the version, and the
	// second part is a variant, such as `MacBookPro15,1` or `iPhone13,2`.
	Value string `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x DeviceModelIdentifier) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *DeviceModelIdentifier) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*DeviceModelIdentifier) SchemaPath() string {
	return "declarative/status/device.model.identifier.yaml"
}

// DeviceModelMarketingName: A status report of the device's marketing name.
//
// DeviceModelMarketingName corresponds to declarative/status/device.model.marketing-name.yaml (Status Device Model Marketing Name).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type DeviceModelMarketingName struct {
	// The device's marketing name, such as `iPhone 12`. This value may not always be
	// available.
	Value string `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x DeviceModelMarketingName) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *DeviceModelMarketingName) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*DeviceModelMarketingName) SchemaPath() string {
	return "declarative/status/device.model.marketing-name.yaml"
}

// DeviceModelNumber: A status report of the device's hardware number.
//
// DeviceModelNumber corresponds to declarative/status/device.model.number.yaml (Status Device Model Number).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type DeviceModelNumber struct {
	// The device's model number.
	Value string `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x DeviceModelNumber) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *DeviceModelNumber) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, &x.Value) }

// SchemaPath returns the Apple schema file this type was generated from.
func (*DeviceModelNumber) SchemaPath() string { return "declarative/status/device.model.number.yaml" }

// DeviceOperatingSystemBuildVersion: A status report of the device's software build
// identifier.
//
// DeviceOperatingSystemBuildVersion corresponds to declarative/status/device.operating-system.build-version.yaml (Status Device Operating System Build Version).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type DeviceOperatingSystemBuildVersion struct {
	// The operating system's build version on the device, such as `18F132`.
	Value string `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x DeviceOperatingSystemBuildVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.Value)
}

// UnmarshalJSON decodes the status value.
func (x *DeviceOperatingSystemBuildVersion) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*DeviceOperatingSystemBuildVersion) SchemaPath() string {
	return "declarative/status/device.operating-system.build-version.yaml"
}

// DeviceOperatingSystemFamily: A status report of the device's operating system family.
//
// DeviceOperatingSystemFamily corresponds to declarative/status/device.operating-system.family.yaml (Status Device Operating System Family).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type DeviceOperatingSystemFamily struct {
	// The operating system family in use on the device, such as `macOS` or `iOS`.
	Value string `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x DeviceOperatingSystemFamily) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *DeviceOperatingSystemFamily) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*DeviceOperatingSystemFamily) SchemaPath() string {
	return "declarative/status/device.operating-system.family.yaml"
}

// DeviceOperatingSystemMarketingName: A status report of the device's operating system
// marketing name.
//
// DeviceOperatingSystemMarketingName corresponds to declarative/status/device.operating-system.marketing-name.yaml (Status Device Operating System Marketing Name).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type DeviceOperatingSystemMarketingName struct {
	// The operating system's marketing name in use on the device, such as `Catalina`.
	Value string `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x DeviceOperatingSystemMarketingName) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.Value)
}

// UnmarshalJSON decodes the status value.
func (x *DeviceOperatingSystemMarketingName) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*DeviceOperatingSystemMarketingName) SchemaPath() string {
	return "declarative/status/device.operating-system.marketing-name.yaml"
}

// DeviceOperatingSystemSupplementalBuildVersion: A status report of the device's operating
// system supplemental build identifier.
//
// DeviceOperatingSystemSupplementalBuildVersion corresponds to declarative/status/device.operating-system.supplemental.build-version.yaml (Status Device Operating System Supplemental Build Version).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type DeviceOperatingSystemSupplementalBuildVersion struct {
	// The operating system's build and Background Security Improvement versions in use on the
	// device, for example, `20A123a` or `20B27c`.
	Value string `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x DeviceOperatingSystemSupplementalBuildVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.Value)
}

// UnmarshalJSON decodes the status value.
func (x *DeviceOperatingSystemSupplementalBuildVersion) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*DeviceOperatingSystemSupplementalBuildVersion) SchemaPath() string {
	return "declarative/status/device.operating-system.supplemental.build-version.yaml"
}

// DeviceOperatingSystemSupplementalExtraVersion: A status report of the device's operating
// system's Background Security Improvement identifier.
//
// DeviceOperatingSystemSupplementalExtraVersion corresponds to declarative/status/device.operating-system.supplemental.extra-version.yaml (Status Device Operating System Supplemental Extra Version).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type DeviceOperatingSystemSupplementalExtraVersion struct {
	// The operating system's Background Security Improvement version in use on the device, for
	// example, `a`.
	Value string `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x DeviceOperatingSystemSupplementalExtraVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.Value)
}

// UnmarshalJSON decodes the status value.
func (x *DeviceOperatingSystemSupplementalExtraVersion) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*DeviceOperatingSystemSupplementalExtraVersion) SchemaPath() string {
	return "declarative/status/device.operating-system.supplemental.extra-version.yaml"
}

// DeviceOperatingSystemVersion: A status report of the device's operating system version.
//
// DeviceOperatingSystemVersion corresponds to declarative/status/device.operating-system.version.yaml (Status Device Operating System Version).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type DeviceOperatingSystemVersion struct {
	// The operating system's version in use on the device, such as `15.0`.
	Value string `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x DeviceOperatingSystemVersion) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *DeviceOperatingSystemVersion) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*DeviceOperatingSystemVersion) SchemaPath() string {
	return "declarative/status/device.operating-system.version.yaml"
}

// DeviceBatteryHealth: The device's battery health.
//
// DeviceBatteryHealth corresponds to declarative/status/device.power.battery-health.yaml (Status Device Battery Health).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type DeviceBatteryHealth struct {
	// The battery health status, which has the following values:
	Value string `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x DeviceBatteryHealth) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *DeviceBatteryHealth) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, &x.Value) }

// SchemaPath returns the Apple schema file this type was generated from.
func (*DeviceBatteryHealth) SchemaPath() string {
	return "declarative/status/device.power.battery-health.yaml"
}

// DiskManagementFileVaultEnabled: The enabled status of the File Vault.
//
// DiskManagementFileVaultEnabled corresponds to declarative/status/diskmanagement.filevault.enabled.yaml (Status Disk Management File Vault Enabled).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type DiskManagementFileVaultEnabled struct {
	// A Boolean value that specifies the File Vault enabled status on the device.
	Value bool `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x DiskManagementFileVaultEnabled) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *DiskManagementFileVaultEnabled) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*DiskManagementFileVaultEnabled) SchemaPath() string {
	return "declarative/status/diskmanagement.filevault.enabled.yaml"
}

// ManagementClientCapabilities: A status report of the client's protocol capabilities.
//
// ManagementClientCapabilities corresponds to declarative/status/management.client-capabilities.yaml (Status Management Client Capabilities).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type ManagementClientCapabilities struct {
	// An object that contains the client's protocol capabilities. These typically only change
	// when the device upgrades its software. An implicit status subscription for this status
	// item is always present, so the client always reports changes to the server.
	Value ManagementClientCapabilitiesCapabilities `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x ManagementClientCapabilities) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *ManagementClientCapabilities) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*ManagementClientCapabilities) SchemaPath() string {
	return "declarative/status/management.client-capabilities.yaml"
}

// ManagementClientCapabilitiesCapabilities: An object that contains the client's protocol
// capabilities. These typically only change when the device upgrades its software. An
// implicit status subscription for this status item is always present, so the client always
// reports changes to the server.
type ManagementClientCapabilitiesCapabilities struct {
	// A list of protocol versions that the client supports.
	SupportedVersions []string `plist:"supported-versions,omitempty" json:"supported-versions,omitempty"`
	// A set of optional protocol features that the client supports. Each object's key
	// represents a feature, and the property value represents the feature's associated
	// parameters.
	SupportedFeatures map[string]any `plist:"supported-features,omitempty" json:"supported-features,omitempty"`
	// A set of declaration and status items that the client supports.
	SupportedPayloads ManagementClientCapabilitiesCapabilitiesSupportedPayloads `plist:"supported-payloads,omitempty" json:"supported-payloads,omitempty"`
}

// ManagementClientCapabilitiesCapabilitiesSupportedPayloads: A set of declaration and status
// items that the client supports.
type ManagementClientCapabilitiesCapabilitiesSupportedPayloads struct {
	// A set of declarations that the client supports.
	Declarations ManagementClientCapabilitiesCapabilitiesSupportedPayloadsDeclarations `plist:"declarations,omitempty" json:"declarations,omitempty"`
	// A list of status items that the client supports.
	StatusItems []string `plist:"status-items,omitempty" json:"status-items,omitempty"`
}

// ManagementClientCapabilitiesCapabilitiesSupportedPayloadsDeclarations: A set of
// declarations that the client supports.
type ManagementClientCapabilitiesCapabilitiesSupportedPayloadsDeclarations struct {
	// An array of strings that represents the activation types that the client supports.
	Activations []string `plist:"activations,omitempty" json:"activations,omitempty"`
	// An array of strings that represents the assets that the client supports.
	Assets []string `plist:"assets,omitempty" json:"assets,omitempty"`
	// An array of strings that represents the configuration types that the client supports.
	Configurations []string `plist:"configurations,omitempty" json:"configurations,omitempty"`
	// An array of strings that represents the declaration types that the client supports.
	Management []string `plist:"management,omitempty" json:"management,omitempty"`
}

// ManagementDeclarations: A status report of the client's processed declarations.
//
// ManagementDeclarations corresponds to declarative/status/management.declarations.yaml (Status Management Declarations).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type ManagementDeclarations struct {
	// A collection of the client's processed declarations.
	Value ManagementDeclarationsDeclarations `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x ManagementDeclarations) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *ManagementDeclarations) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*ManagementDeclarations) SchemaPath() string {
	return "declarative/status/management.declarations.yaml"
}

// ManagementDeclarationsDeclarations: A collection of the client's processed declarations.
type ManagementDeclarationsDeclarations struct {
	// An array of declarations that represent the client's processed activation types.
	Activations []ManagementDeclarationsDeclaration `plist:"activations,omitempty" json:"activations,omitempty"`
	// An array of declarations that represent the client's processed configuration types.
	Configurations []ManagementDeclarationsDeclaration `plist:"configurations,omitempty" json:"configurations,omitempty"`
	// An array of declarations that represent the client's processed assets.
	Assets []ManagementDeclarationsDeclaration `plist:"assets,omitempty" json:"assets,omitempty"`
	// An array of declarations that represent the client's processed declaration types.
	Management []ManagementDeclarationsDeclaration `plist:"management,omitempty" json:"management,omitempty"`
}

// ManagementDeclarationsDeclaration: Status for a declaration processed by the client.
type ManagementDeclarationsDeclaration struct {
	// The `identifier` of the declaration this status report refers to.
	Identifier string `plist:"identifier" json:"identifier"`
	// The `ServerToken` of the declaration this status report refers to.
	ServerToken string `plist:"server-token" json:"server-token"`
	// If `true`, the declaration is active on the device.
	Active bool `plist:"active" json:"active"`
	// This string defines the validity of the declaration. If it's `invalid`, the `reasons`
	// property contains more details.
	Valid string `plist:"valid" json:"valid"`
	// The details of any client errors.
	Reasons []ManagementDeclarationsStatusReason `plist:"reasons,omitempty" json:"reasons,omitempty"`
}

// ManagementDeclarationsStatusReason: Information about a status error.
type ManagementDeclarationsStatusReason struct {
	// The error code for this error.
	Code string `plist:"code" json:"code"`
	// The description for this error.
	Description *string `plist:"description,omitempty" json:"description,omitempty"`
	// A dictionary that contains further details about this error.
	Details map[string]any `plist:"details,omitempty" json:"details,omitempty"`
}

// MDMApp: A status report of the client's MDM-installed apps.
//
// MDMApp corresponds to declarative/status/mdm.app.yaml (Status MDM App).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type MDMApp struct {
	// The list of apps. The response doesn't include apps that are managed by Declarative
	// Device Management.
	Value []MDMAppApp `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x MDMApp) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *MDMApp) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, &x.Value) }

// SchemaPath returns the Apple schema file this type was generated from.
func (*MDMApp) SchemaPath() string { return "declarative/status/mdm.app.yaml" }

// MDMAppApp: A status report that contains details about an MDM-installed app.
type MDMAppApp struct {
	// The app's bundle id, which is unique.
	Identifier string `plist:"identifier" json:"identifier"`
	// If `true`, the system removed the app and only this key and the `identifier` key are
	// present in the status item object. The device reports an MDM-installed app as removed if
	// management of the app has been transferred to Declarative Device Management.
	Removed *bool `plist:"_removed,omitempty" json:"_removed,omitempty"`
	// The name of the app.
	Name *string `plist:"name,omitempty" json:"name,omitempty"`
	// The app's external version identifier. You can also retrieve this value from the App
	// Store. For more information, see `Apps and Books for Organizations`.
	ExternalVersionId *string `plist:"external-version-id,omitempty" json:"external-version-id,omitempty"`
	// The version of the app.
	Version *string `plist:"version,omitempty" json:"version,omitempty"`
	// The short version of the app.
	ShortVersion *string `plist:"short-version,omitempty" json:"short-version,omitempty"`
	// The status of the app that `ManagedApplicationListCommand` reports.
	State *string `plist:"state,omitempty" json:"state,omitempty"`
}

// MigrationAssistantReport: Reports the status of a completed migration.
//
// MigrationAssistantReport corresponds to declarative/status/migration-assistant.report.yaml (Status Migration Assistant Report).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type MigrationAssistantReport struct {
	// The Migration Assistant migration status.
	Value MigrationAssistantReportMigrationAssistantReport `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x MigrationAssistantReport) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *MigrationAssistantReport) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*MigrationAssistantReport) SchemaPath() string {
	return "declarative/status/migration-assistant.report.yaml"
}

// MigrationAssistantReportMigrationAssistantReport: The Migration Assistant migration
// status.
type MigrationAssistantReportMigrationAssistantReport struct {
	// The total amount of data the system successfully migrated from the source system.
	CompletedDataSize *int64 `plist:"completed-data-size,omitempty" json:"completed-data-size,omitempty"`
	// The number of files successfully migrated from the source system.
	CompletedFileCount *int64 `plist:"completed-file-count,omitempty" json:"completed-file-count,omitempty"`
	// The RFC 3339 timestamp for when the system completed migration.
	CompletionTime *string `plist:"completion-time,omitempty" json:"completion-time,omitempty"`
	// The username of the user that the system migrated from the source system.
	SourceUser *string `plist:"source-user,omitempty" json:"source-user,omitempty"`
	// The RFC 3339 timestamp for when the system started migration.
	StartTime *string `plist:"start-time,omitempty" json:"start-time,omitempty"`
	// The username of the target user account on the destination system.
	TargetUser *string `plist:"target-user,omitempty" json:"target-user,omitempty"`
	// The total amount of data the system considers in scope for migration from the source
	// system.
	TotalDataSize *int64 `plist:"total-data-size,omitempty" json:"total-data-size,omitempty"`
	// The number of files the system considers in scope for migration from the source system.
	TotalFileCount *int64 `plist:"total-file-count,omitempty" json:"total-file-count,omitempty"`
	// The descriptions of migration errors that the system reports.
	Errors []string `plist:"errors,omitempty" json:"errors,omitempty"`
}

// MigrationAssistantState: The current migration state of the system.
//
// MigrationAssistantState corresponds to declarative/status/migration-assistant.state.yaml (Status Migration Assistant State).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type MigrationAssistantState struct {
	// The current migration state of the system, which has the following possible values: -
	// `none`: Migration has not started yet or no migration has taken place. - `migrating`:
	// Migration is in progress. - `completed`: Migration has completed successfully. -
	// `failed`: Migration has failed. - `cancelled`: The user cancelled migration. -
	// `unknown`: Migration status is unknown.
	Value string `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x MigrationAssistantState) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *MigrationAssistantState) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*MigrationAssistantState) SchemaPath() string {
	return "declarative/status/migration-assistant.state.yaml"
}

// PackageList: The client's declarative packages.
//
// PackageList corresponds to declarative/status/package.list.yaml (Status Package List).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type PackageList struct {
	// An array of dictionaries that describe the device's declarative packages.
	Value []PackageListPackage `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x PackageList) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *PackageList) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, &x.Value) }

// SchemaPath returns the Apple schema file this type was generated from.
func (*PackageList) SchemaPath() string { return "declarative/status/package.list.yaml" }

// PackageListPackage: A dictionary that describes a declarative package.
type PackageListPackage struct {
	// The package's unique identifier. This is the package identifier value of the package
	// file.
	Identifier string `plist:"identifier" json:"identifier"`
	// If `true`, the system removed the package and only this key and the `identifier` key are
	// present in the status item object.
	Removed *bool `plist:"_removed,omitempty" json:"_removed,omitempty"`
	// The identifier of the declaration that controls the package.
	DeclarationIdentifier *string `plist:"declaration-identifier,omitempty" json:"declaration-identifier,omitempty"`
	// The name of the package.
	Name *string `plist:"name,omitempty" json:"name,omitempty"`
	// The version of the package. This will be the package version value of the package file.
	Version *string `plist:"version,omitempty" json:"version,omitempty"`
	// The status of the package, which has the following possible values:
	State *string `plist:"state,omitempty" json:"state,omitempty"`
	// An array that contains additional details about the package state, including errors.
	Reasons []PackageListStatusReason `plist:"reasons,omitempty" json:"reasons,omitempty"`
}

// PackageListStatusReason: Information about a status error.
type PackageListStatusReason struct {
	// A code for the state.
	Code string `plist:"code" json:"code"`
	// A description of the state.
	Description *string `plist:"description,omitempty" json:"description,omitempty"`
	// A dictionary that contains additional details about the state.
	Details map[string]any `plist:"details,omitempty" json:"details,omitempty"`
}

// PasscodeCompliance: A status report of passcode compliance.
//
// PasscodeCompliance corresponds to declarative/status/passcode.is-compliant.yaml (Status Passcode Compliance).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type PasscodeCompliance struct {
	// If `true`, the passcode is in compliance with all passcode policies set on the device.
	// If `false`, the passcode isn't in compliance with one or more passcode policies set on
	// the device. When there are no passcode policies on the device, this value `true`.
	Value bool `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x PasscodeCompliance) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *PasscodeCompliance) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, &x.Value) }

// SchemaPath returns the Apple schema file this type was generated from.
func (*PasscodeCompliance) SchemaPath() string {
	return "declarative/status/passcode.is-compliant.yaml"
}

// PasscodeIsPresent: A status report of the passcode on the device.
//
// PasscodeIsPresent corresponds to declarative/status/passcode.is-present.yaml (Status Passcode Is Present).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type PasscodeIsPresent struct {
	// If `true`, a passcode is present on the device. If `false`, a passcode isn't present on
	// the device. When a passcode is present, the specific attributes of the passcode, such as
	// length or number of complex characters, aren't reported. Instead, use the
	// `passcode.is-compliant` status item to verify that the passcode complies with all
	// passcode policies set on the device.
	Value bool `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x PasscodeIsPresent) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *PasscodeIsPresent) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, &x.Value) }

// SchemaPath returns the Apple schema file this type was generated from.
func (*PasscodeIsPresent) SchemaPath() string { return "declarative/status/passcode.is-present.yaml" }

// ScreenSharingConnectionGroupUnresolvedConnections: Information about connection groups
// with member connection references that the system couldn't resolve.
//
// ScreenSharingConnectionGroupUnresolvedConnections corresponds to declarative/status/screensharing.connection.group.unresolved-connection.yaml (Status Screen Sharing Connection Group Unresolved Connections).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type ScreenSharingConnectionGroupUnresolvedConnections struct {
	// A status item that contains an array of unresolved connection groups.
	Value []ScreenSharingConnectionGroupUnresolvedConnectionsUnresolvedGroup `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x ScreenSharingConnectionGroupUnresolvedConnections) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.Value)
}

// UnmarshalJSON decodes the status value.
func (x *ScreenSharingConnectionGroupUnresolvedConnections) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*ScreenSharingConnectionGroupUnresolvedConnections) SchemaPath() string {
	return "declarative/status/screensharing.connection.group.unresolved-connection.yaml"
}

// ScreenSharingConnectionGroupUnresolvedConnectionsUnresolvedGroup: A status item that
// contains an unresolved connection group.
type ScreenSharingConnectionGroupUnresolvedConnectionsUnresolvedGroup struct {
	// The unique `ConnectionGroupUUID` identifier of the connection group.
	Identifier string `plist:"identifier" json:"identifier"`
	// If `true`, the system removed the unresolved connection group and only this key and the
	// `identifier` key are present in the status item object.
	Removed *bool `plist:"_removed,omitempty" json:"_removed,omitempty"`
	// An array of `ConnectionUUID` values specified in the `Members` key in the group's
	// declaration for the unresolved connections.
	UnresolvedConnections []string `plist:"unresolved_connections,omitempty" json:"unresolved_connections,omitempty"`
}

// SecurityCertificateList: A status report of the client's managed certificates.
//
// SecurityCertificateList corresponds to declarative/status/security.certificate.list.yaml (Status Security Certificate List).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type SecurityCertificateList struct {
	// A list of the device's managed certificates.
	Value []SecurityCertificateListCertificate `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x SecurityCertificateList) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *SecurityCertificateList) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*SecurityCertificateList) SchemaPath() string {
	return "declarative/status/security.certificate.list.yaml"
}

// SecurityCertificateListCertificate: A status report of a security certificate.
type SecurityCertificateListCertificate struct {
	// The unique identifier of the certificate which the system uses as the primary key.
	Identifier string `plist:"identifier" json:"identifier"`
	// If `true`, the system removed the app and only this key and the `identifier` key are
	// present in the status item object.
	Removed *bool `plist:"_removed,omitempty" json:"_removed,omitempty"`
	// The identifier of the asset declaration that installed the certificate, which is only
	// present if a declaration installed the certificate.
	DeclarationIdentifier *string `plist:"declaration-identifier,omitempty" json:"declaration-identifier,omitempty"`
	// The summary of the certificate's subject.
	SubjectSummary string `plist:"subject-summary" json:"subject-summary"`
	// If `true`, the certificate is an identity certificate.
	IsIdentity bool `plist:"is-identity" json:"is-identity"`
	// The certificate data in DER-encoded X.509 format.
	Data []byte `plist:"data,omitempty" json:"data,omitempty"`
}

// ServicesBackgroundTask: A status report of the device's background task details.
//
// ServicesBackgroundTask corresponds to declarative/status/services.background-task.yaml (Status Services Background Task).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type ServicesBackgroundTask struct {
	// The background task.
	Value []ServicesBackgroundTaskBackgroundTask `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x ServicesBackgroundTask) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *ServicesBackgroundTask) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*ServicesBackgroundTask) SchemaPath() string {
	return "declarative/status/services.background-task.yaml"
}

// ServicesBackgroundTaskBackgroundTask: A status report of a background task.
type ServicesBackgroundTaskBackgroundTask struct {
	// The background task UUID which the system uses as the primary key.
	Identifier string `plist:"identifier" json:"identifier"`
	// If `true`, the background task is removed and the status item object only contains this
	// key and the `identifier` key.
	Removed *bool `plist:"_removed,omitempty" json:"_removed,omitempty"`
	// For types other than `agent` or `daemon`, this is the code signature designated
	// requirement of the item, if available.
	CodeSignature *string `plist:"code-signature,omitempty" json:"code-signature,omitempty"`
	// The numeric user identifier of the owner of the background task.
	Uid int64 `plist:"uid" json:"uid"`
	// For an `agent` or `daemon`, the path to the `launchd` `plist` file. For other types, the
	// path to the app or the document.
	Path string `plist:"path" json:"path"`
	// The `SMAppService.Status` enumeration.
	State string `plist:"state" json:"state"`
	// The daemon, agent, or SFL login item type.
	Type string `plist:"type" json:"type"`
	// Details about a `launchd`-based background task, which is only present when the type is
	// `daemon` or `agent`.
	Launchd *ServicesBackgroundTaskBackgroundTaskLaunchd `plist:"launchd,omitempty" json:"launchd,omitempty"`
}

// ServicesBackgroundTaskBackgroundTaskLaunchd: Details about a `launchd`-based background
// task, which is only present when the type is `daemon` or `agent`.
type ServicesBackgroundTaskBackgroundTaskLaunchd struct {
	// The label of the `launchd`-based background task.
	Label string `plist:"label" json:"label"`
	// The program that the `launchd` `plist` file specifies.
	Program string `plist:"program" json:"program"`
	// The program arguments that the `launchd` `plist` file specifies.
	ProgramArguments []string `plist:"program-arguments,omitempty" json:"program-arguments,omitempty"`
	// The hash value of the `launchd` `plist` file.
	Checksum string `plist:"checksum" json:"checksum"`
	// A dictionary that indicates a `ServicesBackgroundTasks` configuration created this
	// background task. The dictionary contains properties that identify the configuration and
	// the declaration asset that provided the launchd plist for the task.
	DeviceManagement *ServicesBackgroundTaskBackgroundTaskLaunchdDeviceManagement `plist:"device-management,omitempty" json:"device-management,omitempty"`
}

// ServicesBackgroundTaskBackgroundTaskLaunchdDeviceManagement: A dictionary that indicates a
// `ServicesBackgroundTasks` configuration created this background task. The dictionary
// contains properties that identify the configuration and the declaration asset that
// provided the launchd plist for the task.
type ServicesBackgroundTaskBackgroundTaskLaunchdDeviceManagement struct {
	// The identifier of the `ServicesBackgroundTasks` configuration that created this task.
	ConfigurationIdentifier string `plist:"configuration-identifier" json:"configuration-identifier"`
	// The `Identifier` of the declaration asset that provided the launchd plist for this task.
	AssetIdentifier string `plist:"asset-identifier" json:"asset-identifier"`
	// The `ServerToken` of the declaration asset that provided the launchd plist for this
	// task.
	AssetServerToken string `plist:"asset-server-token" json:"asset-server-token"`
}

// SoftwareUpdateBetaEnrollment: A status report of the device's enrolled beta program.
//
// SoftwareUpdateBetaEnrollment corresponds to declarative/status/softwareupdate.beta-enrollment.yaml (Status Software Update Beta Enrollment).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type SoftwareUpdateBetaEnrollment struct {
	// The device's enrolled beta program name, or an empty string if there's no enrolled beta
	// program.
	Value string `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x SoftwareUpdateBetaEnrollment) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *SoftwareUpdateBetaEnrollment) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*SoftwareUpdateBetaEnrollment) SchemaPath() string {
	return "declarative/status/softwareupdate.beta-enrollment.yaml"
}

// SoftwareUpdateDeviceID: A status report of the device's update device ID.
//
// SoftwareUpdateDeviceID corresponds to declarative/status/softwareupdate.device-id.yaml (Status Software Update Device ID).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type SoftwareUpdateDeviceID struct {
	// The device identifier to use when looking up available software updates via
	// `https://gdmf.apple.com/v2/pmv`.
	Value string `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x SoftwareUpdateDeviceID) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *SoftwareUpdateDeviceID) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*SoftwareUpdateDeviceID) SchemaPath() string {
	return "declarative/status/softwareupdate.device-id.yaml"
}

// SoftwareUpdateFailureReason: A status report of a software update failure reason.
//
// SoftwareUpdateFailureReason corresponds to declarative/status/softwareupdate.failure-reason.yaml (Status Software Update Failure Reason).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type SoftwareUpdateFailureReason struct {
	// Details about a software update failure.
	Value SoftwareUpdateFailureReasonDictionary `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x SoftwareUpdateFailureReason) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *SoftwareUpdateFailureReason) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*SoftwareUpdateFailureReason) SchemaPath() string {
	return "declarative/status/softwareupdate.failure-reason.yaml"
}

// SoftwareUpdateFailureReasonDictionary: Details about a software update failure.
type SoftwareUpdateFailureReasonDictionary struct {
	// The number of times the current software update failed. If there are no failures, or no
	// pending software update, this is `0`.
	Count int64 `plist:"count" json:"count"`
	// If present, this describes the reason for last software update failure. This key isn't
	// present if there are no failures or no pending software update.
	Reason *string `plist:"reason,omitempty" json:"reason,omitempty"`
	// If present, this is the RFC 3339 timestamp of the last software update failure. This key
	// isn't present if there are no failures or no pending software update.
	Timestamp *string `plist:"timestamp,omitempty" json:"timestamp,omitempty"`
}

// SoftwareUpdateInstallReason: A status report of the reason for a pending software update
// on the device.
//
// SoftwareUpdateInstallReason corresponds to declarative/status/softwareupdate.install-reason.yaml (Status Software Update Install Reason).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type SoftwareUpdateInstallReason struct {
	// Details about the reason for a pending software update.
	Value SoftwareUpdateInstallReasonDictionary `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x SoftwareUpdateInstallReason) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *SoftwareUpdateInstallReason) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*SoftwareUpdateInstallReason) SchemaPath() string {
	return "declarative/status/softwareupdate.install-reason.yaml"
}

// SoftwareUpdateInstallReasonDictionary: Details about the reason for a pending software
// update.
type SoftwareUpdateInstallReasonDictionary struct {
	// A list of reasons for the pending software update. An empty list indicates that no
	// software update is pending.
	Reason []string `plist:"reason,omitempty" json:"reason,omitempty"`
	// The identifier of the declaration that caused the software update to occur. This key is
	// present only if the `reason` array contains the `declaration` value.
	DeclarationId *string `plist:"declaration-id,omitempty" json:"declaration-id,omitempty"`
}

// SoftwareUpdateInstallState: A status report of the software update install state.
//
// SoftwareUpdateInstallState corresponds to declarative/status/softwareupdate.install-state.yaml (Status Software Update Install State).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type SoftwareUpdateInstallState struct {
	// The software update install status, which has the following values:
	Value string `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x SoftwareUpdateInstallState) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *SoftwareUpdateInstallState) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*SoftwareUpdateInstallState) SchemaPath() string {
	return "declarative/status/softwareupdate.install-state.yaml"
}

// SoftwareUpdatePendingVersion: A status report of the pending software update version.
//
// SoftwareUpdatePendingVersion corresponds to declarative/status/softwareupdate.pending-version.yaml (Status Software Update Pending Version).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type SoftwareUpdatePendingVersion struct {
	// A dictionary that contains the build and OS versions of the software update that's
	// pending on the device.
	Value SoftwareUpdatePendingVersionDictionary `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x SoftwareUpdatePendingVersion) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *SoftwareUpdatePendingVersion) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &x.Value)
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*SoftwareUpdatePendingVersion) SchemaPath() string {
	return "declarative/status/softwareupdate.pending-version.yaml"
}

// SoftwareUpdatePendingVersionDictionary: A dictionary that contains the build and OS
// versions of the software update that's pending on the device.
type SoftwareUpdatePendingVersionDictionary struct {
	// The OS version of the pending software update, including any Background Security
	// Improvement version. This string is empty if no update is pending.
	OsVersion string `plist:"os-version" json:"os-version"`
	// The build version of the pending software update, including any Background Security
	// Improvement version. This string is empty if no update is pending.
	BuildVersion string `plist:"build-version" json:"build-version"`
	// The local date time value that indicates when the pending software update will be
	// installed. This key is only present when the pending software update is being enforced.
	TargetLocalDateTime *string `plist:"target-local-date-time,omitempty" json:"target-local-date-time,omitempty"`
}

// Reason: Provides details about an error for an item in a status report.
//
// Reason corresponds to declarative/status/statusreason.yaml (Status Reason).
type Reason struct {
	// The error code for this error.
	Code string `plist:"code" json:"code"`
	// A description of this error.
	Description *string `plist:"description,omitempty" json:"description,omitempty"`
	// A dictionary that contains additional details about the error.
	Details map[string]any `plist:"details,omitempty" json:"details,omitempty"`
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*Reason) SchemaPath() string { return "declarative/status/statusreason.yaml" }

// TestArrayValue: A test status item for an array.
//
// TestArrayValue corresponds to declarative/status/test.array-value.yaml (Status Test Array Value).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type TestArrayValue struct {
	// The test status item array value.
	Value []TestArrayValueArray `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x TestArrayValue) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *TestArrayValue) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, &x.Value) }

// SchemaPath returns the Apple schema file this type was generated from.
func (*TestArrayValue) SchemaPath() string { return "declarative/status/test.array-value.yaml" }

// TestArrayValueArray: A status value for the test status item array.
type TestArrayValueArray struct {
	// The value of the first sub-key.
	Key1 string `plist:"key1" json:"key1"`
	// The value of the second sub-key.
	Key2 *string `plist:"key2,omitempty" json:"key2,omitempty"`
}

// TestBooleanValue: A test status item for a Boolean value.
//
// TestBooleanValue corresponds to declarative/status/test.boolean-value.yaml (Status Test Boolean Value).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type TestBooleanValue struct {
	// The test status Boolean value.
	Value bool `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x TestBooleanValue) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *TestBooleanValue) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, &x.Value) }

// SchemaPath returns the Apple schema file this type was generated from.
func (*TestBooleanValue) SchemaPath() string { return "declarative/status/test.boolean-value.yaml" }

// TestDictionaryValue: A test status item for a dictionary.
//
// TestDictionaryValue corresponds to declarative/status/test.dictionary-value.yaml (Status Test Dictionary Value).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type TestDictionaryValue struct {
	// The test status dictionary value.
	Value TestDictionaryValueDictionary `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x TestDictionaryValue) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *TestDictionaryValue) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, &x.Value) }

// SchemaPath returns the Apple schema file this type was generated from.
func (*TestDictionaryValue) SchemaPath() string {
	return "declarative/status/test.dictionary-value.yaml"
}

// TestDictionaryValueDictionary: The test status dictionary value.
type TestDictionaryValueDictionary struct {
	// The value of the first sub-key.
	Key1 string `plist:"key1" json:"key1"`
	// The value of the second sub-key.
	Key2 *string `plist:"key2,omitempty" json:"key2,omitempty"`
}

// TestErrorValue: A test status item for an error.
//
// TestErrorValue corresponds to declarative/status/test.error-value.yaml (Status Test Error Value).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type TestErrorValue struct {
	// The test status error value.
	Value string `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x TestErrorValue) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *TestErrorValue) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, &x.Value) }

// SchemaPath returns the Apple schema file this type was generated from.
func (*TestErrorValue) SchemaPath() string { return "declarative/status/test.error-value.yaml" }

// TestIntegerValue: A test status item for an integer.
//
// TestIntegerValue corresponds to declarative/status/test.integer-value.yaml (Status Test Integer Value).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type TestIntegerValue struct {
	// The test status integer value.
	Value int64 `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x TestIntegerValue) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *TestIntegerValue) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, &x.Value) }

// SchemaPath returns the Apple schema file this type was generated from.
func (*TestIntegerValue) SchemaPath() string { return "declarative/status/test.integer-value.yaml" }

// TestRealValue: A test status item for a real value.
//
// TestRealValue corresponds to declarative/status/test.real-value.yaml (Status Test Real Value).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type TestRealValue struct {
	// The test status real value.
	Value float64 `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x TestRealValue) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *TestRealValue) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, &x.Value) }

// SchemaPath returns the Apple schema file this type was generated from.
func (*TestRealValue) SchemaPath() string { return "declarative/status/test.real-value.yaml" }

// TestStringValue: A test status item for a string.
//
// TestStringValue corresponds to declarative/status/test.string-value.yaml (Status Test String Value).
//
// The wire value is the Value field itself; this type exists so the status
// item has a name, a schema path, and support metadata.
type TestStringValue struct {
	// The test status string value.
	Value string `plist:"-" json:"-"`
}

// MarshalJSON encodes the status value.
func (x TestStringValue) MarshalJSON() ([]byte, error) { return json.Marshal(x.Value) }

// UnmarshalJSON decodes the status value.
func (x *TestStringValue) UnmarshalJSON(data []byte) error { return json.Unmarshal(data, &x.Value) }

// SchemaPath returns the Apple schema file this type was generated from.
func (*TestStringValue) SchemaPath() string { return "declarative/status/test.string-value.yaml" }
