// Code generated by admgen; DO NOT EDIT.
// Source: apple/device-management@67045e2fa06f528b196c01edee6a8bf88b844beb

package status_test

import (
	"testing"

	"github.com/deploymenttheory/go-apple-mdm/schema/internal/conformance"
	"github.com/deploymenttheory/go-apple-mdm/schema/status"
)

func sampleAccountListCalDAV(d int) *status.AccountListCalDAV {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.AccountListCalDAV{
		Value: conformance.SliceOf(sampleAccountListCalDAVAccount(d + 1)),
	}
}

func sampleAccountListCalDAVAccount(d int) *status.AccountListCalDAVAccount {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.AccountListCalDAVAccount{
		Identifier:            "s",
		Removed:               new(true),
		DeclarationIdentifier: new("s"),
		VisibleName:           new("s"),
		Hostname:              new("s"),
		Port:                  new(int64(1)),
		Username:              new("s"),
		AreCalendarsEnabled:   new(true),
		AreRemindersEnabled:   new(true),
	}
}

func sampleAccountListCardDAV(d int) *status.AccountListCardDAV {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.AccountListCardDAV{
		Value: conformance.SliceOf(sampleAccountListCardDAVAccount(d + 1)),
	}
}

func sampleAccountListCardDAVAccount(d int) *status.AccountListCardDAVAccount {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.AccountListCardDAVAccount{
		Identifier:            "s",
		Removed:               new(true),
		DeclarationIdentifier: new("s"),
		VisibleName:           new("s"),
		Hostname:              new("s"),
		Port:                  new(int64(1)),
		Username:              new("s"),
	}
}

func sampleAccountListExchange(d int) *status.AccountListExchange {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.AccountListExchange{
		Value: conformance.SliceOf(sampleAccountListExchangeAccount(d + 1)),
	}
}

func sampleAccountListExchangeAccount(d int) *status.AccountListExchangeAccount {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.AccountListExchangeAccount{
		Identifier:            "s",
		Removed:               new(true),
		DeclarationIdentifier: new("s"),
		VisibleName:           new("s"),
		Hostname:              new("s"),
		Port:                  new(int64(1)),
		Username:              new("s"),
		IsMailEnabled:         new(true),
		AreCalendarsEnabled:   new(true),
		AreContactsEnabled:    new(true),
		AreNotesEnabled:       new(true),
		AreRemindersEnabled:   new(true),
	}
}

func sampleAccountListGoogle(d int) *status.AccountListGoogle {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.AccountListGoogle{
		Value: conformance.SliceOf(sampleAccountListGoogleAccount(d + 1)),
	}
}

func sampleAccountListGoogleAccount(d int) *status.AccountListGoogleAccount {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.AccountListGoogleAccount{
		Identifier:            "s",
		Removed:               new(true),
		DeclarationIdentifier: new("s"),
		VisibleName:           new("s"),
		Username:              new("s"),
		IsMailEnabled:         new(true),
		AreCalendarsEnabled:   new(true),
		AreContactsEnabled:    new(true),
		AreNotesEnabled:       new(true),
	}
}

func sampleAccountListLDAP(d int) *status.AccountListLDAP {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.AccountListLDAP{
		Value: conformance.SliceOf(sampleAccountListLDAPAccount(d + 1)),
	}
}

func sampleAccountListLDAPAccount(d int) *status.AccountListLDAPAccount {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.AccountListLDAPAccount{
		Identifier:            "s",
		Removed:               new(true),
		DeclarationIdentifier: new("s"),
		VisibleName:           new("s"),
		Hostname:              new("s"),
		Port:                  new(int64(1)),
		Username:              new("s"),
		IsEnabled:             new(true),
	}
}

func sampleAccountListMailIncoming(d int) *status.AccountListMailIncoming {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.AccountListMailIncoming{
		Value: conformance.SliceOf(sampleAccountListMailIncomingAccount(d + 1)),
	}
}

func sampleAccountListMailIncomingAccount(d int) *status.AccountListMailIncomingAccount {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.AccountListMailIncomingAccount{
		Identifier:            "s",
		Removed:               new(true),
		DeclarationIdentifier: new("s"),
		VisibleName:           new("s"),
		Hostname:              new("s"),
		Port:                  new(int64(1)),
		Username:              new("s"),
		IsMailEnabled:         new(true),
		AreNotesEnabled:       new(true),
	}
}

func sampleAccountListMailOutgoing(d int) *status.AccountListMailOutgoing {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.AccountListMailOutgoing{
		Value: conformance.SliceOf(sampleAccountListMailOutgoingAccount(d + 1)),
	}
}

func sampleAccountListMailOutgoingAccount(d int) *status.AccountListMailOutgoingAccount {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.AccountListMailOutgoingAccount{
		Identifier:            "s",
		Removed:               new(true),
		DeclarationIdentifier: new("s"),
		VisibleName:           new("s"),
		Hostname:              new("s"),
		Port:                  new(int64(1)),
		Username:              new("s"),
	}
}

func sampleAccountListSubscribedCalendar(d int) *status.AccountListSubscribedCalendar {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.AccountListSubscribedCalendar{
		Value: conformance.SliceOf(sampleAccountListSubscribedCalendarAccount(d + 1)),
	}
}

func sampleAccountListSubscribedCalendarAccount(d int) *status.AccountListSubscribedCalendarAccount {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.AccountListSubscribedCalendarAccount{
		Identifier:            "s",
		Removed:               new(true),
		DeclarationIdentifier: new("s"),
		VisibleName:           new("s"),
		CalendarUrl:           new("s"),
		Username:              new("s"),
		IsEnabled:             new(true),
	}
}

func sampleAppManagedList(d int) *status.AppManagedList {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.AppManagedList{
		Value: conformance.SliceOf(sampleAppManagedListApp(d + 1)),
	}
}

func sampleAppManagedListApp(d int) *status.AppManagedListApp {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.AppManagedListApp{
		Identifier:            "s",
		Removed:               new(true),
		DeclarationIdentifier: new("s"),
		Name:                  new("s"),
		ExternalVersionId:     new(int64(1)),
		Version:               new("s"),
		ShortVersion:          new("s"),
		State:                 new("optional"),
		UpdateState:           new("available"),
		ConfigState:           sampleAppManagedListManagedConfiguration(d + 1),
		Reasons:               conformance.SliceOf(sampleAppManagedListStatusReason(d + 1)),
	}
}

func sampleAppManagedListManagedConfiguration(d int) *status.AppManagedListManagedConfiguration {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.AppManagedListManagedConfiguration{
		AppConfigState:       sampleAppManagedListManagedConfigurationState(d + 1),
		ExtensionConfigState: map[string]status.AppManagedListManagedConfigurationState{"k": conformance.Deref(sampleAppManagedListManagedConfigurationState(d + 1))},
	}
}

func sampleAppManagedListManagedConfigurationState(d int) *status.AppManagedListManagedConfigurationState {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.AppManagedListManagedConfigurationState{
		State: "unknown",
	}
}

func sampleAppManagedListStatusReason(d int) *status.AppManagedListStatusReason {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.AppManagedListStatusReason{
		Code:        "s",
		Description: new("s"),
		Details:     map[string]any{"k": any("x")},
	}
}

func sampleDeviceSerialNumber(d int) *status.DeviceSerialNumber {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.DeviceSerialNumber{
		Value: "s",
	}
}

func sampleDeviceUDID(d int) *status.DeviceUDID {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.DeviceUDID{
		Value: "s",
	}
}

func sampleDeviceModelFamily(d int) *status.DeviceModelFamily {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.DeviceModelFamily{
		Value: "s",
	}
}

func sampleDeviceModelIdentifier(d int) *status.DeviceModelIdentifier {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.DeviceModelIdentifier{
		Value: "s",
	}
}

func sampleDeviceModelMarketingName(d int) *status.DeviceModelMarketingName {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.DeviceModelMarketingName{
		Value: "s",
	}
}

func sampleDeviceModelNumber(d int) *status.DeviceModelNumber {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.DeviceModelNumber{
		Value: "s",
	}
}

func sampleDeviceOperatingSystemBuildVersion(d int) *status.DeviceOperatingSystemBuildVersion {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.DeviceOperatingSystemBuildVersion{
		Value: "s",
	}
}

func sampleDeviceOperatingSystemFamily(d int) *status.DeviceOperatingSystemFamily {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.DeviceOperatingSystemFamily{
		Value: "s",
	}
}

func sampleDeviceOperatingSystemMarketingName(d int) *status.DeviceOperatingSystemMarketingName {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.DeviceOperatingSystemMarketingName{
		Value: "s",
	}
}

func sampleDeviceOperatingSystemSupplementalBuildVersion(d int) *status.DeviceOperatingSystemSupplementalBuildVersion {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.DeviceOperatingSystemSupplementalBuildVersion{
		Value: "s",
	}
}

func sampleDeviceOperatingSystemSupplementalExtraVersion(d int) *status.DeviceOperatingSystemSupplementalExtraVersion {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.DeviceOperatingSystemSupplementalExtraVersion{
		Value: "s",
	}
}

func sampleDeviceOperatingSystemVersion(d int) *status.DeviceOperatingSystemVersion {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.DeviceOperatingSystemVersion{
		Value: "s",
	}
}

func sampleDeviceBatteryHealth(d int) *status.DeviceBatteryHealth {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.DeviceBatteryHealth{
		Value: "non-genuine",
	}
}

func sampleDiskManagementFileVaultEnabled(d int) *status.DiskManagementFileVaultEnabled {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.DiskManagementFileVaultEnabled{
		Value: true,
	}
}

func sampleManagementClientCapabilities(d int) *status.ManagementClientCapabilities {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.ManagementClientCapabilities{
		Value: conformance.Deref(sampleManagementClientCapabilitiesCapabilities(d + 1)),
	}
}

func sampleManagementClientCapabilitiesCapabilities(d int) *status.ManagementClientCapabilitiesCapabilities {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.ManagementClientCapabilitiesCapabilities{
		SupportedVersions: []string{"s"},
		SupportedFeatures: map[string]any{"k": any("x")},
		SupportedPayloads: conformance.Deref(sampleManagementClientCapabilitiesCapabilitiesSupportedPayloads(d + 1)),
	}
}

func sampleManagementClientCapabilitiesCapabilitiesSupportedPayloads(d int) *status.ManagementClientCapabilitiesCapabilitiesSupportedPayloads {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.ManagementClientCapabilitiesCapabilitiesSupportedPayloads{
		Declarations: conformance.Deref(sampleManagementClientCapabilitiesCapabilitiesSupportedPayloadsDeclarations(d + 1)),
		StatusItems:  []string{"s"},
	}
}

func sampleManagementClientCapabilitiesCapabilitiesSupportedPayloadsDeclarations(d int) *status.ManagementClientCapabilitiesCapabilitiesSupportedPayloadsDeclarations {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.ManagementClientCapabilitiesCapabilitiesSupportedPayloadsDeclarations{
		Activations:    []string{"s"},
		Assets:         []string{"s"},
		Configurations: []string{"s"},
		Management:     []string{"s"},
	}
}

func sampleManagementDeclarations(d int) *status.ManagementDeclarations {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.ManagementDeclarations{
		Value: conformance.Deref(sampleManagementDeclarationsDeclarations(d + 1)),
	}
}

func sampleManagementDeclarationsDeclarations(d int) *status.ManagementDeclarationsDeclarations {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.ManagementDeclarationsDeclarations{
		Activations:    conformance.SliceOf(sampleManagementDeclarationsDeclaration(d + 1)),
		Configurations: conformance.SliceOf(sampleManagementDeclarationsDeclaration(d + 1)),
		Assets:         conformance.SliceOf(sampleManagementDeclarationsDeclaration(d + 1)),
		Management:     conformance.SliceOf(sampleManagementDeclarationsDeclaration(d + 1)),
	}
}

func sampleManagementDeclarationsDeclaration(d int) *status.ManagementDeclarationsDeclaration {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.ManagementDeclarationsDeclaration{
		Identifier:  "s",
		ServerToken: "s",
		Active:      true,
		Valid:       "unknown",
		Reasons:     conformance.SliceOf(sampleManagementDeclarationsStatusReason(d + 1)),
	}
}

func sampleManagementDeclarationsStatusReason(d int) *status.ManagementDeclarationsStatusReason {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.ManagementDeclarationsStatusReason{
		Code:        "s",
		Description: new("s"),
		Details:     map[string]any{"k": any("x")},
	}
}

func sampleMDMApp(d int) *status.MDMApp {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.MDMApp{
		Value: conformance.SliceOf(sampleMDMAppApp(d + 1)),
	}
}

func sampleMDMAppApp(d int) *status.MDMAppApp {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.MDMAppApp{
		Identifier:        "s",
		Removed:           new(true),
		Name:              new("s"),
		ExternalVersionId: new("s"),
		Version:           new("s"),
		ShortVersion:      new("s"),
		State:             new("queued"),
	}
}

func sampleMigrationAssistantReport(d int) *status.MigrationAssistantReport {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.MigrationAssistantReport{
		Value: conformance.Deref(sampleMigrationAssistantReportMigrationAssistantReport(d + 1)),
	}
}

func sampleMigrationAssistantReportMigrationAssistantReport(d int) *status.MigrationAssistantReportMigrationAssistantReport {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.MigrationAssistantReportMigrationAssistantReport{
		CompletedDataSize:  new(int64(1)),
		CompletedFileCount: new(int64(1)),
		CompletionTime:     new("s"),
		SourceUser:         new("s"),
		StartTime:          new("s"),
		TargetUser:         new("s"),
		TotalDataSize:      new(int64(1)),
		TotalFileCount:     new(int64(1)),
		Errors:             []string{"s"},
	}
}

func sampleMigrationAssistantState(d int) *status.MigrationAssistantState {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.MigrationAssistantState{
		Value: "waiting",
	}
}

func samplePackageList(d int) *status.PackageList {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.PackageList{
		Value: conformance.SliceOf(samplePackageListPackage(d + 1)),
	}
}

func samplePackageListPackage(d int) *status.PackageListPackage {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.PackageListPackage{
		Identifier:            "s",
		Removed:               new(true),
		DeclarationIdentifier: new("s"),
		Name:                  new("s"),
		Version:               new("s"),
		State:                 new("optional"),
		Reasons:               conformance.SliceOf(samplePackageListStatusReason(d + 1)),
	}
}

func samplePackageListStatusReason(d int) *status.PackageListStatusReason {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.PackageListStatusReason{
		Code:        "s",
		Description: new("s"),
		Details:     map[string]any{"k": any("x")},
	}
}

func samplePasscodeCompliance(d int) *status.PasscodeCompliance {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.PasscodeCompliance{
		Value: true,
	}
}

func samplePasscodeIsPresent(d int) *status.PasscodeIsPresent {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.PasscodeIsPresent{
		Value: true,
	}
}

func sampleScreenSharingConnectionGroupUnresolvedConnections(d int) *status.ScreenSharingConnectionGroupUnresolvedConnections {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.ScreenSharingConnectionGroupUnresolvedConnections{
		Value: conformance.SliceOf(sampleScreenSharingConnectionGroupUnresolvedConnectionsUnresolvedGroup(d + 1)),
	}
}

func sampleScreenSharingConnectionGroupUnresolvedConnectionsUnresolvedGroup(d int) *status.ScreenSharingConnectionGroupUnresolvedConnectionsUnresolvedGroup {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.ScreenSharingConnectionGroupUnresolvedConnectionsUnresolvedGroup{
		Identifier:            "s",
		Removed:               new(true),
		UnresolvedConnections: []string{"s"},
	}
}

func sampleSecurityCertificateList(d int) *status.SecurityCertificateList {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.SecurityCertificateList{
		Value: conformance.SliceOf(sampleSecurityCertificateListCertificate(d + 1)),
	}
}

func sampleSecurityCertificateListCertificate(d int) *status.SecurityCertificateListCertificate {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.SecurityCertificateListCertificate{
		Identifier:            "s",
		Removed:               new(true),
		DeclarationIdentifier: new("s"),
		SubjectSummary:        "s",
		IsIdentity:            true,
		Data:                  []byte{1, 2, 3},
	}
}

func sampleServicesBackgroundTask(d int) *status.ServicesBackgroundTask {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.ServicesBackgroundTask{
		Value: conformance.SliceOf(sampleServicesBackgroundTaskBackgroundTask(d + 1)),
	}
}

func sampleServicesBackgroundTaskBackgroundTask(d int) *status.ServicesBackgroundTaskBackgroundTask {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.ServicesBackgroundTaskBackgroundTask{
		Identifier:    "s",
		Removed:       new(true),
		CodeSignature: new("s"),
		Uid:           int64(1),
		Path:          "s",
		State:         "not-registered",
		Type:          "daemon",
		Launchd:       sampleServicesBackgroundTaskBackgroundTaskLaunchd(d + 1),
	}
}

func sampleServicesBackgroundTaskBackgroundTaskLaunchd(d int) *status.ServicesBackgroundTaskBackgroundTaskLaunchd {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.ServicesBackgroundTaskBackgroundTaskLaunchd{
		Label:            "s",
		Program:          "s",
		ProgramArguments: []string{"s"},
		Checksum:         "s",
		DeviceManagement: sampleServicesBackgroundTaskBackgroundTaskLaunchdDeviceManagement(d + 1),
	}
}

func sampleServicesBackgroundTaskBackgroundTaskLaunchdDeviceManagement(d int) *status.ServicesBackgroundTaskBackgroundTaskLaunchdDeviceManagement {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.ServicesBackgroundTaskBackgroundTaskLaunchdDeviceManagement{
		ConfigurationIdentifier: "s",
		AssetIdentifier:         "s",
		AssetServerToken:        "s",
	}
}

func sampleSoftwareUpdateBetaEnrollment(d int) *status.SoftwareUpdateBetaEnrollment {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.SoftwareUpdateBetaEnrollment{
		Value: "s",
	}
}

func sampleSoftwareUpdateDeviceID(d int) *status.SoftwareUpdateDeviceID {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.SoftwareUpdateDeviceID{
		Value: "s",
	}
}

func sampleSoftwareUpdateFailureReason(d int) *status.SoftwareUpdateFailureReason {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.SoftwareUpdateFailureReason{
		Value: conformance.Deref(sampleSoftwareUpdateFailureReasonDictionary(d + 1)),
	}
}

func sampleSoftwareUpdateFailureReasonDictionary(d int) *status.SoftwareUpdateFailureReasonDictionary {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.SoftwareUpdateFailureReasonDictionary{
		Count:     int64(1),
		Reason:    new("s"),
		Timestamp: new("s"),
	}
}

func sampleSoftwareUpdateInstallReason(d int) *status.SoftwareUpdateInstallReason {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.SoftwareUpdateInstallReason{
		Value: conformance.Deref(sampleSoftwareUpdateInstallReasonDictionary(d + 1)),
	}
}

func sampleSoftwareUpdateInstallReasonDictionary(d int) *status.SoftwareUpdateInstallReasonDictionary {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.SoftwareUpdateInstallReasonDictionary{
		Reason:        []string{"system-settings"},
		DeclarationId: new("s"),
	}
}

func sampleSoftwareUpdateInstallState(d int) *status.SoftwareUpdateInstallState {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.SoftwareUpdateInstallState{
		Value: "none",
	}
}

func sampleSoftwareUpdatePendingVersion(d int) *status.SoftwareUpdatePendingVersion {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.SoftwareUpdatePendingVersion{
		Value: conformance.Deref(sampleSoftwareUpdatePendingVersionDictionary(d + 1)),
	}
}

func sampleSoftwareUpdatePendingVersionDictionary(d int) *status.SoftwareUpdatePendingVersionDictionary {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.SoftwareUpdatePendingVersionDictionary{
		OsVersion:           "s",
		BuildVersion:        "s",
		TargetLocalDateTime: new("s"),
	}
}

func sampleReason(d int) *status.Reason {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.Reason{
		Code:        "s",
		Description: new("s"),
		Details:     map[string]any{"k": "v"},
	}
}

func sampleTestArrayValue(d int) *status.TestArrayValue {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.TestArrayValue{
		Value: conformance.SliceOf(sampleTestArrayValueArray(d + 1)),
	}
}

func sampleTestArrayValueArray(d int) *status.TestArrayValueArray {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.TestArrayValueArray{
		Key1: "s",
		Key2: new("s"),
	}
}

func sampleTestBooleanValue(d int) *status.TestBooleanValue {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.TestBooleanValue{
		Value: true,
	}
}

func sampleTestDictionaryValue(d int) *status.TestDictionaryValue {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.TestDictionaryValue{
		Value: conformance.Deref(sampleTestDictionaryValueDictionary(d + 1)),
	}
}

func sampleTestDictionaryValueDictionary(d int) *status.TestDictionaryValueDictionary {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.TestDictionaryValueDictionary{
		Key1: "s",
		Key2: new("s"),
	}
}

func sampleTestErrorValue(d int) *status.TestErrorValue {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.TestErrorValue{
		Value: "s",
	}
}

func sampleTestIntegerValue(d int) *status.TestIntegerValue {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.TestIntegerValue{
		Value: int64(1),
	}
}

func sampleTestRealValue(d int) *status.TestRealValue {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.TestRealValue{
		Value: 1.5,
	}
}

func sampleTestStringValue(d int) *status.TestStringValue {
	if d > 12 {
		return nil
	}
	_ = d
	return &status.TestStringValue{
		Value: "s",
	}
}

func TestConformanceRoundTrip(t *testing.T) {
	t.Parallel()
	t.Run("AccountListCalDAV", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAccountListCalDAV(0), func() any { return new(status.AccountListCalDAV) }, true)
	})
	t.Run("AccountListCardDAV", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAccountListCardDAV(0), func() any { return new(status.AccountListCardDAV) }, true)
	})
	t.Run("AccountListExchange", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAccountListExchange(0), func() any { return new(status.AccountListExchange) }, true)
	})
	t.Run("AccountListGoogle", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAccountListGoogle(0), func() any { return new(status.AccountListGoogle) }, true)
	})
	t.Run("AccountListLDAP", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAccountListLDAP(0), func() any { return new(status.AccountListLDAP) }, true)
	})
	t.Run("AccountListMailIncoming", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAccountListMailIncoming(0), func() any { return new(status.AccountListMailIncoming) }, true)
	})
	t.Run("AccountListMailOutgoing", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAccountListMailOutgoing(0), func() any { return new(status.AccountListMailOutgoing) }, true)
	})
	t.Run("AccountListSubscribedCalendar", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAccountListSubscribedCalendar(0), func() any { return new(status.AccountListSubscribedCalendar) }, true)
	})
	t.Run("AppManagedList", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAppManagedList(0), func() any { return new(status.AppManagedList) }, true)
	})
	t.Run("DeviceSerialNumber", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleDeviceSerialNumber(0), func() any { return new(status.DeviceSerialNumber) }, true)
	})
	t.Run("DeviceUDID", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleDeviceUDID(0), func() any { return new(status.DeviceUDID) }, true)
	})
	t.Run("DeviceModelFamily", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleDeviceModelFamily(0), func() any { return new(status.DeviceModelFamily) }, true)
	})
	t.Run("DeviceModelIdentifier", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleDeviceModelIdentifier(0), func() any { return new(status.DeviceModelIdentifier) }, true)
	})
	t.Run("DeviceModelMarketingName", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleDeviceModelMarketingName(0), func() any { return new(status.DeviceModelMarketingName) }, true)
	})
	t.Run("DeviceModelNumber", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleDeviceModelNumber(0), func() any { return new(status.DeviceModelNumber) }, true)
	})
	t.Run("DeviceOperatingSystemBuildVersion", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleDeviceOperatingSystemBuildVersion(0), func() any { return new(status.DeviceOperatingSystemBuildVersion) }, true)
	})
	t.Run("DeviceOperatingSystemFamily", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleDeviceOperatingSystemFamily(0), func() any { return new(status.DeviceOperatingSystemFamily) }, true)
	})
	t.Run("DeviceOperatingSystemMarketingName", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleDeviceOperatingSystemMarketingName(0), func() any { return new(status.DeviceOperatingSystemMarketingName) }, true)
	})
	t.Run("DeviceOperatingSystemSupplementalBuildVersion", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleDeviceOperatingSystemSupplementalBuildVersion(0), func() any { return new(status.DeviceOperatingSystemSupplementalBuildVersion) }, true)
	})
	t.Run("DeviceOperatingSystemSupplementalExtraVersion", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleDeviceOperatingSystemSupplementalExtraVersion(0), func() any { return new(status.DeviceOperatingSystemSupplementalExtraVersion) }, true)
	})
	t.Run("DeviceOperatingSystemVersion", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleDeviceOperatingSystemVersion(0), func() any { return new(status.DeviceOperatingSystemVersion) }, true)
	})
	t.Run("DeviceBatteryHealth", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleDeviceBatteryHealth(0), func() any { return new(status.DeviceBatteryHealth) }, true)
	})
	t.Run("DiskManagementFileVaultEnabled", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleDiskManagementFileVaultEnabled(0), func() any { return new(status.DiskManagementFileVaultEnabled) }, true)
	})
	t.Run("ManagementClientCapabilities", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleManagementClientCapabilities(0), func() any { return new(status.ManagementClientCapabilities) }, true)
	})
	t.Run("ManagementDeclarations", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleManagementDeclarations(0), func() any { return new(status.ManagementDeclarations) }, true)
	})
	t.Run("MDMApp", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleMDMApp(0), func() any { return new(status.MDMApp) }, true)
	})
	t.Run("MigrationAssistantReport", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleMigrationAssistantReport(0), func() any { return new(status.MigrationAssistantReport) }, true)
	})
	t.Run("MigrationAssistantState", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleMigrationAssistantState(0), func() any { return new(status.MigrationAssistantState) }, true)
	})
	t.Run("PackageList", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, samplePackageList(0), func() any { return new(status.PackageList) }, true)
	})
	t.Run("PasscodeCompliance", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, samplePasscodeCompliance(0), func() any { return new(status.PasscodeCompliance) }, true)
	})
	t.Run("PasscodeIsPresent", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, samplePasscodeIsPresent(0), func() any { return new(status.PasscodeIsPresent) }, true)
	})
	t.Run("ScreenSharingConnectionGroupUnresolvedConnections", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleScreenSharingConnectionGroupUnresolvedConnections(0), func() any { return new(status.ScreenSharingConnectionGroupUnresolvedConnections) }, true)
	})
	t.Run("SecurityCertificateList", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleSecurityCertificateList(0), func() any { return new(status.SecurityCertificateList) }, true)
	})
	t.Run("ServicesBackgroundTask", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleServicesBackgroundTask(0), func() any { return new(status.ServicesBackgroundTask) }, true)
	})
	t.Run("SoftwareUpdateBetaEnrollment", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleSoftwareUpdateBetaEnrollment(0), func() any { return new(status.SoftwareUpdateBetaEnrollment) }, true)
	})
	t.Run("SoftwareUpdateDeviceID", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleSoftwareUpdateDeviceID(0), func() any { return new(status.SoftwareUpdateDeviceID) }, true)
	})
	t.Run("SoftwareUpdateFailureReason", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleSoftwareUpdateFailureReason(0), func() any { return new(status.SoftwareUpdateFailureReason) }, true)
	})
	t.Run("SoftwareUpdateInstallReason", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleSoftwareUpdateInstallReason(0), func() any { return new(status.SoftwareUpdateInstallReason) }, true)
	})
	t.Run("SoftwareUpdateInstallState", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleSoftwareUpdateInstallState(0), func() any { return new(status.SoftwareUpdateInstallState) }, true)
	})
	t.Run("SoftwareUpdatePendingVersion", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleSoftwareUpdatePendingVersion(0), func() any { return new(status.SoftwareUpdatePendingVersion) }, true)
	})
	t.Run("Reason", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleReason(0), func() any { return new(status.Reason) }, true)
	})
	t.Run("TestArrayValue", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleTestArrayValue(0), func() any { return new(status.TestArrayValue) }, true)
	})
	t.Run("TestBooleanValue", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleTestBooleanValue(0), func() any { return new(status.TestBooleanValue) }, true)
	})
	t.Run("TestDictionaryValue", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleTestDictionaryValue(0), func() any { return new(status.TestDictionaryValue) }, true)
	})
	t.Run("TestErrorValue", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleTestErrorValue(0), func() any { return new(status.TestErrorValue) }, true)
	})
	t.Run("TestIntegerValue", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleTestIntegerValue(0), func() any { return new(status.TestIntegerValue) }, true)
	})
	t.Run("TestRealValue", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleTestRealValue(0), func() any { return new(status.TestRealValue) }, true)
	})
	t.Run("TestStringValue", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleTestStringValue(0), func() any { return new(status.TestStringValue) }, true)
	})
}

func TestConformanceValidate(t *testing.T) {
	t.Parallel()
	conformance.Validates(t, "AccountListCalDAV", sampleAccountListCalDAV(0), new(status.AccountListCalDAV))
	conformance.Validates(t, "AccountListCardDAV", sampleAccountListCardDAV(0), new(status.AccountListCardDAV))
	conformance.Validates(t, "AccountListExchange", sampleAccountListExchange(0), new(status.AccountListExchange))
	conformance.Validates(t, "AccountListGoogle", sampleAccountListGoogle(0), new(status.AccountListGoogle))
	conformance.Validates(t, "AccountListLDAP", sampleAccountListLDAP(0), new(status.AccountListLDAP))
	conformance.Validates(t, "AccountListMailIncoming", sampleAccountListMailIncoming(0), new(status.AccountListMailIncoming))
	conformance.Validates(t, "AccountListMailOutgoing", sampleAccountListMailOutgoing(0), new(status.AccountListMailOutgoing))
	conformance.Validates(t, "AccountListSubscribedCalendar", sampleAccountListSubscribedCalendar(0), new(status.AccountListSubscribedCalendar))
	conformance.Validates(t, "AppManagedList", sampleAppManagedList(0), new(status.AppManagedList))
	conformance.Validates(t, "DeviceSerialNumber", sampleDeviceSerialNumber(0), new(status.DeviceSerialNumber))
	conformance.Validates(t, "DeviceUDID", sampleDeviceUDID(0), new(status.DeviceUDID))
	conformance.Validates(t, "DeviceModelFamily", sampleDeviceModelFamily(0), new(status.DeviceModelFamily))
	conformance.Validates(t, "DeviceModelIdentifier", sampleDeviceModelIdentifier(0), new(status.DeviceModelIdentifier))
	conformance.Validates(t, "DeviceModelMarketingName", sampleDeviceModelMarketingName(0), new(status.DeviceModelMarketingName))
	conformance.Validates(t, "DeviceModelNumber", sampleDeviceModelNumber(0), new(status.DeviceModelNumber))
	conformance.Validates(t, "DeviceOperatingSystemBuildVersion", sampleDeviceOperatingSystemBuildVersion(0), new(status.DeviceOperatingSystemBuildVersion))
	conformance.Validates(t, "DeviceOperatingSystemFamily", sampleDeviceOperatingSystemFamily(0), new(status.DeviceOperatingSystemFamily))
	conformance.Validates(t, "DeviceOperatingSystemMarketingName", sampleDeviceOperatingSystemMarketingName(0), new(status.DeviceOperatingSystemMarketingName))
	conformance.Validates(t, "DeviceOperatingSystemSupplementalBuildVersion", sampleDeviceOperatingSystemSupplementalBuildVersion(0), new(status.DeviceOperatingSystemSupplementalBuildVersion))
	conformance.Validates(t, "DeviceOperatingSystemSupplementalExtraVersion", sampleDeviceOperatingSystemSupplementalExtraVersion(0), new(status.DeviceOperatingSystemSupplementalExtraVersion))
	conformance.Validates(t, "DeviceOperatingSystemVersion", sampleDeviceOperatingSystemVersion(0), new(status.DeviceOperatingSystemVersion))
	conformance.Validates(t, "DeviceBatteryHealth", sampleDeviceBatteryHealth(0), new(status.DeviceBatteryHealth))
	conformance.Validates(t, "DiskManagementFileVaultEnabled", sampleDiskManagementFileVaultEnabled(0), new(status.DiskManagementFileVaultEnabled))
	conformance.Validates(t, "ManagementClientCapabilities", sampleManagementClientCapabilities(0), new(status.ManagementClientCapabilities))
	conformance.Validates(t, "ManagementDeclarations", sampleManagementDeclarations(0), new(status.ManagementDeclarations))
	conformance.Validates(t, "MDMApp", sampleMDMApp(0), new(status.MDMApp))
	conformance.Validates(t, "MigrationAssistantReport", sampleMigrationAssistantReport(0), new(status.MigrationAssistantReport))
	conformance.Validates(t, "MigrationAssistantState", sampleMigrationAssistantState(0), new(status.MigrationAssistantState))
	conformance.Validates(t, "PackageList", samplePackageList(0), new(status.PackageList))
	conformance.Validates(t, "PasscodeCompliance", samplePasscodeCompliance(0), new(status.PasscodeCompliance))
	conformance.Validates(t, "PasscodeIsPresent", samplePasscodeIsPresent(0), new(status.PasscodeIsPresent))
	conformance.Validates(t, "ScreenSharingConnectionGroupUnresolvedConnections", sampleScreenSharingConnectionGroupUnresolvedConnections(0), new(status.ScreenSharingConnectionGroupUnresolvedConnections))
	conformance.Validates(t, "SecurityCertificateList", sampleSecurityCertificateList(0), new(status.SecurityCertificateList))
	conformance.Validates(t, "ServicesBackgroundTask", sampleServicesBackgroundTask(0), new(status.ServicesBackgroundTask))
	conformance.Validates(t, "SoftwareUpdateBetaEnrollment", sampleSoftwareUpdateBetaEnrollment(0), new(status.SoftwareUpdateBetaEnrollment))
	conformance.Validates(t, "SoftwareUpdateDeviceID", sampleSoftwareUpdateDeviceID(0), new(status.SoftwareUpdateDeviceID))
	conformance.Validates(t, "SoftwareUpdateFailureReason", sampleSoftwareUpdateFailureReason(0), new(status.SoftwareUpdateFailureReason))
	conformance.Validates(t, "SoftwareUpdateInstallReason", sampleSoftwareUpdateInstallReason(0), new(status.SoftwareUpdateInstallReason))
	conformance.Validates(t, "SoftwareUpdateInstallState", sampleSoftwareUpdateInstallState(0), new(status.SoftwareUpdateInstallState))
	conformance.Validates(t, "SoftwareUpdatePendingVersion", sampleSoftwareUpdatePendingVersion(0), new(status.SoftwareUpdatePendingVersion))
	conformance.Validates(t, "Reason", sampleReason(0), new(status.Reason))
	conformance.Validates(t, "TestArrayValue", sampleTestArrayValue(0), new(status.TestArrayValue))
	conformance.Validates(t, "TestBooleanValue", sampleTestBooleanValue(0), new(status.TestBooleanValue))
	conformance.Validates(t, "TestDictionaryValue", sampleTestDictionaryValue(0), new(status.TestDictionaryValue))
	conformance.Validates(t, "TestErrorValue", sampleTestErrorValue(0), new(status.TestErrorValue))
	conformance.Validates(t, "TestIntegerValue", sampleTestIntegerValue(0), new(status.TestIntegerValue))
	conformance.Validates(t, "TestRealValue", sampleTestRealValue(0), new(status.TestRealValue))
	conformance.Validates(t, "TestStringValue", sampleTestStringValue(0), new(status.TestStringValue))
}

func TestConformanceRegistry(t *testing.T) {
	t.Parallel()
	if len(status.Registry) != 47 {
		t.Fatalf("registry has %d entries, want 47", len(status.Registry))
	}
	for name, en := range status.Registry {
		v := en.New()
		if v == nil || v.StatusItemTypeName() != en.ID || v.SchemaPath() != en.Schema {
			t.Errorf("registry entry %q is inconsistent: %+v", name, en)
		}
		var _ status.Item = v
		found := false
		for _, x := range status.ByID(en.ID) {
			if x.Schema == en.Schema {
				found = true
			}
		}
		if !found {
			t.Errorf("ByID(%q) does not contain %s", en.ID, name)
		}
	}
	if ids := status.IDs(); len(ids) == 0 || len(ids) > len(status.Registry) {
		t.Errorf("IDs() = %d", len(ids))
	}
	if len(status.ByID("no-such-id")) != 0 {
		t.Error("ByID(no-such-id) should be empty")
	}
	if status.Support("nope") != nil {
		t.Error("Support(nope) should be nil")
	}
	if status.Support("AccountListCalDAV") == nil {
		t.Error("missing support entry for AccountListCalDAV")
	}
	if status.Support("AccountListCardDAV") == nil {
		t.Error("missing support entry for AccountListCardDAV")
	}
	if status.Support("AccountListExchange") == nil {
		t.Error("missing support entry for AccountListExchange")
	}
	if status.Support("AccountListGoogle") == nil {
		t.Error("missing support entry for AccountListGoogle")
	}
	if status.Support("AccountListLDAP") == nil {
		t.Error("missing support entry for AccountListLDAP")
	}
	if status.Support("AccountListMailIncoming") == nil {
		t.Error("missing support entry for AccountListMailIncoming")
	}
	if status.Support("AccountListMailOutgoing") == nil {
		t.Error("missing support entry for AccountListMailOutgoing")
	}
	if status.Support("AccountListSubscribedCalendar") == nil {
		t.Error("missing support entry for AccountListSubscribedCalendar")
	}
	if status.Support("AppManagedList") == nil {
		t.Error("missing support entry for AppManagedList")
	}
	if status.Support("DeviceSerialNumber") == nil {
		t.Error("missing support entry for DeviceSerialNumber")
	}
	if status.Support("DeviceUDID") == nil {
		t.Error("missing support entry for DeviceUDID")
	}
	if status.Support("DeviceModelFamily") == nil {
		t.Error("missing support entry for DeviceModelFamily")
	}
	if status.Support("DeviceModelIdentifier") == nil {
		t.Error("missing support entry for DeviceModelIdentifier")
	}
	if status.Support("DeviceModelMarketingName") == nil {
		t.Error("missing support entry for DeviceModelMarketingName")
	}
	if status.Support("DeviceModelNumber") == nil {
		t.Error("missing support entry for DeviceModelNumber")
	}
	if status.Support("DeviceOperatingSystemBuildVersion") == nil {
		t.Error("missing support entry for DeviceOperatingSystemBuildVersion")
	}
	if status.Support("DeviceOperatingSystemFamily") == nil {
		t.Error("missing support entry for DeviceOperatingSystemFamily")
	}
	if status.Support("DeviceOperatingSystemMarketingName") == nil {
		t.Error("missing support entry for DeviceOperatingSystemMarketingName")
	}
	if status.Support("DeviceOperatingSystemSupplementalBuildVersion") == nil {
		t.Error("missing support entry for DeviceOperatingSystemSupplementalBuildVersion")
	}
	if status.Support("DeviceOperatingSystemSupplementalExtraVersion") == nil {
		t.Error("missing support entry for DeviceOperatingSystemSupplementalExtraVersion")
	}
	if status.Support("DeviceOperatingSystemVersion") == nil {
		t.Error("missing support entry for DeviceOperatingSystemVersion")
	}
	if status.Support("DeviceBatteryHealth") == nil {
		t.Error("missing support entry for DeviceBatteryHealth")
	}
	if status.Support("DiskManagementFileVaultEnabled") == nil {
		t.Error("missing support entry for DiskManagementFileVaultEnabled")
	}
	if status.Support("ManagementClientCapabilities") == nil {
		t.Error("missing support entry for ManagementClientCapabilities")
	}
	if status.Support("ManagementDeclarations") == nil {
		t.Error("missing support entry for ManagementDeclarations")
	}
	if status.Support("MDMApp") == nil {
		t.Error("missing support entry for MDMApp")
	}
	if status.Support("MigrationAssistantReport") == nil {
		t.Error("missing support entry for MigrationAssistantReport")
	}
	if status.Support("MigrationAssistantState") == nil {
		t.Error("missing support entry for MigrationAssistantState")
	}
	if status.Support("PackageList") == nil {
		t.Error("missing support entry for PackageList")
	}
	if status.Support("PasscodeCompliance") == nil {
		t.Error("missing support entry for PasscodeCompliance")
	}
	if status.Support("PasscodeIsPresent") == nil {
		t.Error("missing support entry for PasscodeIsPresent")
	}
	if status.Support("ScreenSharingConnectionGroupUnresolvedConnections") == nil {
		t.Error("missing support entry for ScreenSharingConnectionGroupUnresolvedConnections")
	}
	if status.Support("SecurityCertificateList") == nil {
		t.Error("missing support entry for SecurityCertificateList")
	}
	if status.Support("ServicesBackgroundTask") == nil {
		t.Error("missing support entry for ServicesBackgroundTask")
	}
	if status.Support("SoftwareUpdateBetaEnrollment") == nil {
		t.Error("missing support entry for SoftwareUpdateBetaEnrollment")
	}
	if status.Support("SoftwareUpdateDeviceID") == nil {
		t.Error("missing support entry for SoftwareUpdateDeviceID")
	}
	if status.Support("SoftwareUpdateFailureReason") == nil {
		t.Error("missing support entry for SoftwareUpdateFailureReason")
	}
	if status.Support("SoftwareUpdateInstallReason") == nil {
		t.Error("missing support entry for SoftwareUpdateInstallReason")
	}
	if status.Support("SoftwareUpdateInstallState") == nil {
		t.Error("missing support entry for SoftwareUpdateInstallState")
	}
	if status.Support("SoftwareUpdatePendingVersion") == nil {
		t.Error("missing support entry for SoftwareUpdatePendingVersion")
	}
	if status.Support("Reason") == nil {
		t.Error("missing support entry for Reason")
	}
	if status.Support("TestArrayValue") == nil {
		t.Error("missing support entry for TestArrayValue")
	}
	if status.Support("TestBooleanValue") == nil {
		t.Error("missing support entry for TestBooleanValue")
	}
	if status.Support("TestDictionaryValue") == nil {
		t.Error("missing support entry for TestDictionaryValue")
	}
	if status.Support("TestErrorValue") == nil {
		t.Error("missing support entry for TestErrorValue")
	}
	if status.Support("TestIntegerValue") == nil {
		t.Error("missing support entry for TestIntegerValue")
	}
	if status.Support("TestRealValue") == nil {
		t.Error("missing support entry for TestRealValue")
	}
	if status.Support("TestStringValue") == nil {
		t.Error("missing support entry for TestStringValue")
	}
}
