// Code generated by admgen; DO NOT EDIT.
// Source: apple/device-management@67045e2fa06f528b196c01edee6a8bf88b844beb

package status

import (
	"github.com/deploymenttheory/go-apple-mdm/schema/support"
)

// Item is implemented by every top-level type in this package.
type Item interface {
	// StatusItemTypeName returns the wire identifier from Apple's schema.
	StatusItemTypeName() string
	// SchemaPath returns the schema file the type was generated from.
	SchemaPath() string
	// Validate checks the value against the schema for the target.
	Validate(t support.Target) error
}

// Entry describes one schema in the Registry.
type Entry struct {
	// ID is the wire identifier: RequestType, MessageType, PayloadType,
	// DeclarationType, StatusItemType, error code, or type name.
	ID string
	// Schema is the YAML path in apple/device-management.
	Schema string
	Title  string
	// New returns a zero value of the type as Item.
	New func() Item
	// NewResponse returns a zero response value, or nil when the schema
	// defines no response keys.
	NewResponse func() any
}

// Wire identifiers.
const (
	// StatusItemTypeAccountListCalDAV: Status Account List CalDAV
	StatusItemTypeAccountListCalDAV = "account.list.caldav"
	// StatusItemTypeAccountListCardDAV: Status Account List CardDAV
	StatusItemTypeAccountListCardDAV = "account.list.carddav"
	// StatusItemTypeAccountListExchange: Status Account List Exchange
	StatusItemTypeAccountListExchange = "account.list.exchange"
	// StatusItemTypeAccountListGoogle: Status Account List Google
	StatusItemTypeAccountListGoogle = "account.list.google"
	// StatusItemTypeAccountListLDAP: Status Account List LDAP
	StatusItemTypeAccountListLDAP = "account.list.ldap"
	// StatusItemTypeAccountListMailIncoming: Status Account List Mail Incoming
	StatusItemTypeAccountListMailIncoming = "account.list.mail.incoming"
	// StatusItemTypeAccountListMailOutgoing: Status Account List Mail Outgoing
	StatusItemTypeAccountListMailOutgoing = "account.list.mail.outgoing"
	// StatusItemTypeAccountListSubscribedCalendar: Status Account List Subscribed Calendar
	StatusItemTypeAccountListSubscribedCalendar = "account.list.subscribed-calendar"
	// StatusItemTypeAppManagedList: Status App Managed List
	StatusItemTypeAppManagedList = "app.managed.list"
	// StatusItemTypeDeviceSerialNumber: Status Device Serial Number
	StatusItemTypeDeviceSerialNumber = "device.identifier.serial-number"
	// StatusItemTypeDeviceUDID: Status Device UDID
	StatusItemTypeDeviceUDID = "device.identifier.udid"
	// StatusItemTypeDeviceModelFamily: Status Device Model Family
	StatusItemTypeDeviceModelFamily = "device.model.family"
	// StatusItemTypeDeviceModelIdentifier: Status Device Model Identifier
	StatusItemTypeDeviceModelIdentifier = "device.model.identifier"
	// StatusItemTypeDeviceModelMarketingName: Status Device Model Marketing Name
	StatusItemTypeDeviceModelMarketingName = "device.model.marketing-name"
	// StatusItemTypeDeviceModelNumber: Status Device Model Number
	StatusItemTypeDeviceModelNumber = "device.model.number"
	// StatusItemTypeDeviceOperatingSystemBuildVersion: Status Device Operating System Build Version
	StatusItemTypeDeviceOperatingSystemBuildVersion = "device.operating-system.build-version"
	// StatusItemTypeDeviceOperatingSystemFamily: Status Device Operating System Family
	StatusItemTypeDeviceOperatingSystemFamily = "device.operating-system.family"
	// StatusItemTypeDeviceOperatingSystemMarketingName: Status Device Operating System Marketing Name
	StatusItemTypeDeviceOperatingSystemMarketingName = "device.operating-system.marketing-name"
	// StatusItemTypeDeviceOperatingSystemSupplementalBuildVersion: Status Device Operating System Supplemental Build Version
	StatusItemTypeDeviceOperatingSystemSupplementalBuildVersion = "device.operating-system.supplemental.build-version"
	// StatusItemTypeDeviceOperatingSystemSupplementalExtraVersion: Status Device Operating System Supplemental Extra Version
	StatusItemTypeDeviceOperatingSystemSupplementalExtraVersion = "device.operating-system.supplemental.extra-version"
	// StatusItemTypeDeviceOperatingSystemVersion: Status Device Operating System Version
	StatusItemTypeDeviceOperatingSystemVersion = "device.operating-system.version"
	// StatusItemTypeDeviceBatteryHealth: Status Device Battery Health
	StatusItemTypeDeviceBatteryHealth = "device.power.battery-health"
	// StatusItemTypeDiskManagementFileVaultEnabled: Status Disk Management File Vault Enabled
	StatusItemTypeDiskManagementFileVaultEnabled = "diskmanagement.filevault.enabled"
	// StatusItemTypeManagementClientCapabilities: Status Management Client Capabilities
	StatusItemTypeManagementClientCapabilities = "management.client-capabilities"
	// StatusItemTypeManagementDeclarations: Status Management Declarations
	StatusItemTypeManagementDeclarations = "management.declarations"
	// StatusItemTypeMDMApp: Status MDM App
	StatusItemTypeMDMApp = "mdm.app"
	// StatusItemTypeMigrationAssistantReport: Status Migration Assistant Report
	StatusItemTypeMigrationAssistantReport = "migration-assistant.report"
	// StatusItemTypeMigrationAssistantState: Status Migration Assistant State
	StatusItemTypeMigrationAssistantState = "migration-assistant.state"
	// StatusItemTypePackageList: Status Package List
	StatusItemTypePackageList = "package.list"
	// StatusItemTypePasscodeCompliance: Status Passcode Compliance
	StatusItemTypePasscodeCompliance = "passcode.is-compliant"
	// StatusItemTypePasscodeIsPresent: Status Passcode Is Present
	StatusItemTypePasscodeIsPresent = "passcode.is-present"
	// StatusItemTypeScreenSharingConnectionGroupUnresolvedConnections: Status Screen Sharing Connection Group Unresolved Connections
	StatusItemTypeScreenSharingConnectionGroupUnresolvedConnections = "screensharing.connection.group.unresolved-connection"
	// StatusItemTypeSecurityCertificateList: Status Security Certificate List
	StatusItemTypeSecurityCertificateList = "security.certificate.list"
	// StatusItemTypeServicesBackgroundTask: Status Services Background Task
	StatusItemTypeServicesBackgroundTask = "services.background-task"
	// StatusItemTypeSoftwareUpdateBetaEnrollment: Status Software Update Beta Enrollment
	StatusItemTypeSoftwareUpdateBetaEnrollment = "softwareupdate.beta-enrollment"
	// StatusItemTypeSoftwareUpdateDeviceID: Status Software Update Device ID
	StatusItemTypeSoftwareUpdateDeviceID = "softwareupdate.device-id"
	// StatusItemTypeSoftwareUpdateFailureReason: Status Software Update Failure Reason
	StatusItemTypeSoftwareUpdateFailureReason = "softwareupdate.failure-reason"
	// StatusItemTypeSoftwareUpdateInstallReason: Status Software Update Install Reason
	StatusItemTypeSoftwareUpdateInstallReason = "softwareupdate.install-reason"
	// StatusItemTypeSoftwareUpdateInstallState: Status Software Update Install State
	StatusItemTypeSoftwareUpdateInstallState = "softwareupdate.install-state"
	// StatusItemTypeSoftwareUpdatePendingVersion: Status Software Update Pending Version
	StatusItemTypeSoftwareUpdatePendingVersion = "softwareupdate.pending-version"
	// StatusItemTypeTestArrayValue: Status Test Array Value
	StatusItemTypeTestArrayValue = "test.array-value"
	// StatusItemTypeTestBooleanValue: Status Test Boolean Value
	StatusItemTypeTestBooleanValue = "test.boolean-value"
	// StatusItemTypeTestDictionaryValue: Status Test Dictionary Value
	StatusItemTypeTestDictionaryValue = "test.dictionary-value"
	// StatusItemTypeTestErrorValue: Status Test Error Value
	StatusItemTypeTestErrorValue = "test.error-value"
	// StatusItemTypeTestIntegerValue: Status Test Integer Value
	StatusItemTypeTestIntegerValue = "test.integer-value"
	// StatusItemTypeTestRealValue: Status Test Real Value
	StatusItemTypeTestRealValue = "test.real-value"
	// StatusItemTypeTestStringValue: Status Test String Value
	StatusItemTypeTestStringValue = "test.string-value"
)

// Registry maps Go type names to constructors, one entry per schema file.
// Several schemas may share a wire identifier (for example six profile
// payloads use com.apple.MCX), so look up by identifier with ByID.
var Registry = map[string]Entry{
	"AccountListCalDAV":                                 {ID: "account.list.caldav", Schema: "declarative/status/account.list.caldav.yaml", Title: "Status Account List CalDAV", New: func() Item { return new(AccountListCalDAV) }},
	"AccountListCardDAV":                                {ID: "account.list.carddav", Schema: "declarative/status/account.list.carddav.yaml", Title: "Status Account List CardDAV", New: func() Item { return new(AccountListCardDAV) }},
	"AccountListExchange":                               {ID: "account.list.exchange", Schema: "declarative/status/account.list.exchange.yaml", Title: "Status Account List Exchange", New: func() Item { return new(AccountListExchange) }},
	"AccountListGoogle":                                 {ID: "account.list.google", Schema: "declarative/status/account.list.google.yaml", Title: "Status Account List Google", New: func() Item { return new(AccountListGoogle) }},
	"AccountListLDAP":                                   {ID: "account.list.ldap", Schema: "declarative/status/account.list.ldap.yaml", Title: "Status Account List LDAP", New: func() Item { return new(AccountListLDAP) }},
	"AccountListMailIncoming":                           {ID: "account.list.mail.incoming", Schema: "declarative/status/account.list.mail.incoming.yaml", Title: "Status Account List Mail Incoming", New: func() Item { return new(AccountListMailIncoming) }},
	"AccountListMailOutgoing":                           {ID: "account.list.mail.outgoing", Schema: "declarative/status/account.list.mail.outgoing.yaml", Title: "Status Account List Mail Outgoing", New: func() Item { return new(AccountListMailOutgoing) }},
	"AccountListSubscribedCalendar":                     {ID: "account.list.subscribed-calendar", Schema: "declarative/status/account.list.subscribed-calendar.yaml", Title: "Status Account List Subscribed Calendar", New: func() Item { return new(AccountListSubscribedCalendar) }},
	"AppManagedList":                                    {ID: "app.managed.list", Schema: "declarative/status/app.managed.list.yaml", Title: "Status App Managed List", New: func() Item { return new(AppManagedList) }},
	"DeviceBatteryHealth":                               {ID: "device.power.battery-health", Schema: "declarative/status/device.power.battery-health.yaml", Title: "Status Device Battery Health", New: func() Item { return new(DeviceBatteryHealth) }},
	"DeviceModelFamily":                                 {ID: "device.model.family", Schema: "declarative/status/device.model.family.yaml", Title: "Status Device Model Family", New: func() Item { return new(DeviceModelFamily) }},
	"DeviceModelIdentifier":                             {ID: "device.model.identifier", Schema: "declarative/status/device.model.identifier.yaml", Title: "Status Device Model Identifier", New: func() Item { return new(DeviceModelIdentifier) }},
	"DeviceModelMarketingName":                          {ID: "device.model.marketing-name", Schema: "declarative/status/device.model.marketing-name.yaml", Title: "Status Device Model Marketing Name", New: func() Item { return new(DeviceModelMarketingName) }},
	"DeviceModelNumber":                                 {ID: "device.model.number", Schema: "declarative/status/device.model.number.yaml", Title: "Status Device Model Number", New: func() Item { return new(DeviceModelNumber) }},
	"DeviceOperatingSystemBuildVersion":                 {ID: "device.operating-system.build-version", Schema: "declarative/status/device.operating-system.build-version.yaml", Title: "Status Device Operating System Build Version", New: func() Item { return new(DeviceOperatingSystemBuildVersion) }},
	"DeviceOperatingSystemFamily":                       {ID: "device.operating-system.family", Schema: "declarative/status/device.operating-system.family.yaml", Title: "Status Device Operating System Family", New: func() Item { return new(DeviceOperatingSystemFamily) }},
	"DeviceOperatingSystemMarketingName":                {ID: "device.operating-system.marketing-name", Schema: "declarative/status/device.operating-system.marketing-name.yaml", Title: "Status Device Operating System Marketing Name", New: func() Item { return new(DeviceOperatingSystemMarketingName) }},
	"DeviceOperatingSystemSupplementalBuildVersion":     {ID: "device.operating-system.supplemental.build-version", Schema: "declarative/status/device.operating-system.supplemental.build-version.yaml", Title: "Status Device Operating System Supplemental Build Version", New: func() Item { return new(DeviceOperatingSystemSupplementalBuildVersion) }},
	"DeviceOperatingSystemSupplementalExtraVersion":     {ID: "device.operating-system.supplemental.extra-version", Schema: "declarative/status/device.operating-system.supplemental.extra-version.yaml", Title: "Status Device Operating System Supplemental Extra Version", New: func() Item { return new(DeviceOperatingSystemSupplementalExtraVersion) }},
	"DeviceOperatingSystemVersion":                      {ID: "device.operating-system.version", Schema: "declarative/status/device.operating-system.version.yaml", Title: "Status Device Operating System Version", New: func() Item { return new(DeviceOperatingSystemVersion) }},
	"DeviceSerialNumber":                                {ID: "device.identifier.serial-number", Schema: "declarative/status/device.identifier.serial-number.yaml", Title: "Status Device Serial Number", New: func() Item { return new(DeviceSerialNumber) }},
	"DeviceUDID":                                        {ID: "device.identifier.udid", Schema: "declarative/status/device.identifier.udid.yaml", Title: "Status Device UDID", New: func() Item { return new(DeviceUDID) }},
	"DiskManagementFileVaultEnabled":                    {ID: "diskmanagement.filevault.enabled", Schema: "declarative/status/diskmanagement.filevault.enabled.yaml", Title: "Status Disk Management File Vault Enabled", New: func() Item { return new(DiskManagementFileVaultEnabled) }},
	"MDMApp":                                            {ID: "mdm.app", Schema: "declarative/status/mdm.app.yaml", Title: "Status MDM App", New: func() Item { return new(MDMApp) }},
	"ManagementClientCapabilities":                      {ID: "management.client-capabilities", Schema: "declarative/status/management.client-capabilities.yaml", Title: "Status Management Client Capabilities", New: func() Item { return new(ManagementClientCapabilities) }},
	"ManagementDeclarations":                            {ID: "management.declarations", Schema: "declarative/status/management.declarations.yaml", Title: "Status Management Declarations", New: func() Item { return new(ManagementDeclarations) }},
	"MigrationAssistantReport":                          {ID: "migration-assistant.report", Schema: "declarative/status/migration-assistant.report.yaml", Title: "Status Migration Assistant Report", New: func() Item { return new(MigrationAssistantReport) }},
	"MigrationAssistantState":                           {ID: "migration-assistant.state", Schema: "declarative/status/migration-assistant.state.yaml", Title: "Status Migration Assistant State", New: func() Item { return new(MigrationAssistantState) }},
	"PackageList":                                       {ID: "package.list", Schema: "declarative/status/package.list.yaml", Title: "Status Package List", New: func() Item { return new(PackageList) }},
	"PasscodeCompliance":                                {ID: "passcode.is-compliant", Schema: "declarative/status/passcode.is-compliant.yaml", Title: "Status Passcode Compliance", New: func() Item { return new(PasscodeCompliance) }},
	"PasscodeIsPresent":                                 {ID: "passcode.is-present", Schema: "declarative/status/passcode.is-present.yaml", Title: "Status Passcode Is Present", New: func() Item { return new(PasscodeIsPresent) }},
	"ScreenSharingConnectionGroupUnresolvedConnections": {ID: "screensharing.connection.group.unresolved-connection", Schema: "declarative/status/screensharing.connection.group.unresolved-connection.yaml", Title: "Status Screen Sharing Connection Group Unresolved Connections", New: func() Item { return new(ScreenSharingConnectionGroupUnresolvedConnections) }},
	"SecurityCertificateList":                           {ID: "security.certificate.list", Schema: "declarative/status/security.certificate.list.yaml", Title: "Status Security Certificate List", New: func() Item { return new(SecurityCertificateList) }},
	"ServicesBackgroundTask":                            {ID: "services.background-task", Schema: "declarative/status/services.background-task.yaml", Title: "Status Services Background Task", New: func() Item { return new(ServicesBackgroundTask) }},
	"SoftwareUpdateBetaEnrollment":                      {ID: "softwareupdate.beta-enrollment", Schema: "declarative/status/softwareupdate.beta-enrollment.yaml", Title: "Status Software Update Beta Enrollment", New: func() Item { return new(SoftwareUpdateBetaEnrollment) }},
	"SoftwareUpdateDeviceID":                            {ID: "softwareupdate.device-id", Schema: "declarative/status/softwareupdate.device-id.yaml", Title: "Status Software Update Device ID", New: func() Item { return new(SoftwareUpdateDeviceID) }},
	"SoftwareUpdateFailureReason":                       {ID: "softwareupdate.failure-reason", Schema: "declarative/status/softwareupdate.failure-reason.yaml", Title: "Status Software Update Failure Reason", New: func() Item { return new(SoftwareUpdateFailureReason) }},
	"SoftwareUpdateInstallReason":                       {ID: "softwareupdate.install-reason", Schema: "declarative/status/softwareupdate.install-reason.yaml", Title: "Status Software Update Install Reason", New: func() Item { return new(SoftwareUpdateInstallReason) }},
	"SoftwareUpdateInstallState":                        {ID: "softwareupdate.install-state", Schema: "declarative/status/softwareupdate.install-state.yaml", Title: "Status Software Update Install State", New: func() Item { return new(SoftwareUpdateInstallState) }},
	"SoftwareUpdatePendingVersion":                      {ID: "softwareupdate.pending-version", Schema: "declarative/status/softwareupdate.pending-version.yaml", Title: "Status Software Update Pending Version", New: func() Item { return new(SoftwareUpdatePendingVersion) }},
	"TestArrayValue":                                    {ID: "test.array-value", Schema: "declarative/status/test.array-value.yaml", Title: "Status Test Array Value", New: func() Item { return new(TestArrayValue) }},
	"TestBooleanValue":                                  {ID: "test.boolean-value", Schema: "declarative/status/test.boolean-value.yaml", Title: "Status Test Boolean Value", New: func() Item { return new(TestBooleanValue) }},
	"TestDictionaryValue":                               {ID: "test.dictionary-value", Schema: "declarative/status/test.dictionary-value.yaml", Title: "Status Test Dictionary Value", New: func() Item { return new(TestDictionaryValue) }},
	"TestErrorValue":                                    {ID: "test.error-value", Schema: "declarative/status/test.error-value.yaml", Title: "Status Test Error Value", New: func() Item { return new(TestErrorValue) }},
	"TestIntegerValue":                                  {ID: "test.integer-value", Schema: "declarative/status/test.integer-value.yaml", Title: "Status Test Integer Value", New: func() Item { return new(TestIntegerValue) }},
	"TestRealValue":                                     {ID: "test.real-value", Schema: "declarative/status/test.real-value.yaml", Title: "Status Test Real Value", New: func() Item { return new(TestRealValue) }},
	"TestStringValue":                                   {ID: "test.string-value", Schema: "declarative/status/test.string-value.yaml", Title: "Status Test String Value", New: func() Item { return new(TestStringValue) }},
}

// IDs returns the distinct wire identifiers in sorted order.
func IDs() []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(Registry))
	for _, en := range Registry {
		if !seen[en.ID] {
			seen[en.ID] = true
			out = append(out, en.ID)
		}
	}
	sortStrings(out)
	return out
}

// ByID returns every entry with the given wire identifier, sorted by type name.
func ByID(id string) []Entry {
	var names []string
	for name, en := range Registry {
		if en.ID == id {
			names = append(names, name)
		}
	}
	sortStrings(names)
	out := make([]Entry, 0, len(names))
	for _, n := range names {
		out = append(out, Registry[n])
	}
	return out
}

func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j-1] > s[j]; j-- {
			s[j-1], s[j] = s[j], s[j-1]
		}
	}
}

// StatusItemTypeName returns "account.list.caldav".
func (*AccountListCalDAV) StatusItemTypeName() string { return "account.list.caldav" }

// StatusItemTypeName returns "account.list.carddav".
func (*AccountListCardDAV) StatusItemTypeName() string { return "account.list.carddav" }

// StatusItemTypeName returns "account.list.exchange".
func (*AccountListExchange) StatusItemTypeName() string { return "account.list.exchange" }

// StatusItemTypeName returns "account.list.google".
func (*AccountListGoogle) StatusItemTypeName() string { return "account.list.google" }

// StatusItemTypeName returns "account.list.ldap".
func (*AccountListLDAP) StatusItemTypeName() string { return "account.list.ldap" }

// StatusItemTypeName returns "account.list.mail.incoming".
func (*AccountListMailIncoming) StatusItemTypeName() string { return "account.list.mail.incoming" }

// StatusItemTypeName returns "account.list.mail.outgoing".
func (*AccountListMailOutgoing) StatusItemTypeName() string { return "account.list.mail.outgoing" }

// StatusItemTypeName returns "account.list.subscribed-calendar".
func (*AccountListSubscribedCalendar) StatusItemTypeName() string {
	return "account.list.subscribed-calendar"
}

// StatusItemTypeName returns "app.managed.list".
func (*AppManagedList) StatusItemTypeName() string { return "app.managed.list" }

// StatusItemTypeName returns "device.identifier.serial-number".
func (*DeviceSerialNumber) StatusItemTypeName() string { return "device.identifier.serial-number" }

// StatusItemTypeName returns "device.identifier.udid".
func (*DeviceUDID) StatusItemTypeName() string { return "device.identifier.udid" }

// StatusItemTypeName returns "device.model.family".
func (*DeviceModelFamily) StatusItemTypeName() string { return "device.model.family" }

// StatusItemTypeName returns "device.model.identifier".
func (*DeviceModelIdentifier) StatusItemTypeName() string { return "device.model.identifier" }

// StatusItemTypeName returns "device.model.marketing-name".
func (*DeviceModelMarketingName) StatusItemTypeName() string { return "device.model.marketing-name" }

// StatusItemTypeName returns "device.model.number".
func (*DeviceModelNumber) StatusItemTypeName() string { return "device.model.number" }

// StatusItemTypeName returns "device.operating-system.build-version".
func (*DeviceOperatingSystemBuildVersion) StatusItemTypeName() string {
	return "device.operating-system.build-version"
}

// StatusItemTypeName returns "device.operating-system.family".
func (*DeviceOperatingSystemFamily) StatusItemTypeName() string {
	return "device.operating-system.family"
}

// StatusItemTypeName returns "device.operating-system.marketing-name".
func (*DeviceOperatingSystemMarketingName) StatusItemTypeName() string {
	return "device.operating-system.marketing-name"
}

// StatusItemTypeName returns "device.operating-system.supplemental.build-version".
func (*DeviceOperatingSystemSupplementalBuildVersion) StatusItemTypeName() string {
	return "device.operating-system.supplemental.build-version"
}

// StatusItemTypeName returns "device.operating-system.supplemental.extra-version".
func (*DeviceOperatingSystemSupplementalExtraVersion) StatusItemTypeName() string {
	return "device.operating-system.supplemental.extra-version"
}

// StatusItemTypeName returns "device.operating-system.version".
func (*DeviceOperatingSystemVersion) StatusItemTypeName() string {
	return "device.operating-system.version"
}

// StatusItemTypeName returns "device.power.battery-health".
func (*DeviceBatteryHealth) StatusItemTypeName() string { return "device.power.battery-health" }

// StatusItemTypeName returns "diskmanagement.filevault.enabled".
func (*DiskManagementFileVaultEnabled) StatusItemTypeName() string {
	return "diskmanagement.filevault.enabled"
}

// StatusItemTypeName returns "management.client-capabilities".
func (*ManagementClientCapabilities) StatusItemTypeName() string {
	return "management.client-capabilities"
}

// StatusItemTypeName returns "management.declarations".
func (*ManagementDeclarations) StatusItemTypeName() string { return "management.declarations" }

// StatusItemTypeName returns "mdm.app".
func (*MDMApp) StatusItemTypeName() string { return "mdm.app" }

// StatusItemTypeName returns "migration-assistant.report".
func (*MigrationAssistantReport) StatusItemTypeName() string { return "migration-assistant.report" }

// StatusItemTypeName returns "migration-assistant.state".
func (*MigrationAssistantState) StatusItemTypeName() string { return "migration-assistant.state" }

// StatusItemTypeName returns "package.list".
func (*PackageList) StatusItemTypeName() string { return "package.list" }

// StatusItemTypeName returns "passcode.is-compliant".
func (*PasscodeCompliance) StatusItemTypeName() string { return "passcode.is-compliant" }

// StatusItemTypeName returns "passcode.is-present".
func (*PasscodeIsPresent) StatusItemTypeName() string { return "passcode.is-present" }

// StatusItemTypeName returns "screensharing.connection.group.unresolved-connection".
func (*ScreenSharingConnectionGroupUnresolvedConnections) StatusItemTypeName() string {
	return "screensharing.connection.group.unresolved-connection"
}

// StatusItemTypeName returns "security.certificate.list".
func (*SecurityCertificateList) StatusItemTypeName() string { return "security.certificate.list" }

// StatusItemTypeName returns "services.background-task".
func (*ServicesBackgroundTask) StatusItemTypeName() string { return "services.background-task" }

// StatusItemTypeName returns "softwareupdate.beta-enrollment".
func (*SoftwareUpdateBetaEnrollment) StatusItemTypeName() string {
	return "softwareupdate.beta-enrollment"
}

// StatusItemTypeName returns "softwareupdate.device-id".
func (*SoftwareUpdateDeviceID) StatusItemTypeName() string { return "softwareupdate.device-id" }

// StatusItemTypeName returns "softwareupdate.failure-reason".
func (*SoftwareUpdateFailureReason) StatusItemTypeName() string {
	return "softwareupdate.failure-reason"
}

// StatusItemTypeName returns "softwareupdate.install-reason".
func (*SoftwareUpdateInstallReason) StatusItemTypeName() string {
	return "softwareupdate.install-reason"
}

// StatusItemTypeName returns "softwareupdate.install-state".
func (*SoftwareUpdateInstallState) StatusItemTypeName() string { return "softwareupdate.install-state" }

// StatusItemTypeName returns "softwareupdate.pending-version".
func (*SoftwareUpdatePendingVersion) StatusItemTypeName() string {
	return "softwareupdate.pending-version"
}

// StatusItemTypeName returns "".
func (*Reason) StatusItemTypeName() string { return "" }

// StatusItemTypeName returns "test.array-value".
func (*TestArrayValue) StatusItemTypeName() string { return "test.array-value" }

// StatusItemTypeName returns "test.boolean-value".
func (*TestBooleanValue) StatusItemTypeName() string { return "test.boolean-value" }

// StatusItemTypeName returns "test.dictionary-value".
func (*TestDictionaryValue) StatusItemTypeName() string { return "test.dictionary-value" }

// StatusItemTypeName returns "test.error-value".
func (*TestErrorValue) StatusItemTypeName() string { return "test.error-value" }

// StatusItemTypeName returns "test.integer-value".
func (*TestIntegerValue) StatusItemTypeName() string { return "test.integer-value" }

// StatusItemTypeName returns "test.real-value".
func (*TestRealValue) StatusItemTypeName() string { return "test.real-value" }

// StatusItemTypeName returns "test.string-value".
func (*TestStringValue) StatusItemTypeName() string { return "test.string-value" }
