// Code generated by admgen; DO NOT EDIT.
// Source: apple/device-management@67045e2fa06f528b196c01edee6a8bf88b844beb

package errors

// CodePlatformSSORequired: An error response that indicates Platform SSO is required.
//
// CodePlatformSSORequired corresponds to mdm/errors/psso.required.yaml (Error Code Platform SSO Required).
type CodePlatformSSORequired struct {
	// Indicates that the device needs to do Platform SSO before enrollment and setup can
	// proceed.
	Code string `plist:"code" json:"code"`
	// A description of the error. Only use this for logging purposes and don't display it to
	// the user.
	Description *string `plist:"description,omitempty" json:"description,omitempty"`
	// A description of the error to display to the user.
	Message *string `plist:"message,omitempty" json:"message,omitempty"`
	// A dictionary that contains additional data about the error code.
	Details CodePlatformSSORequiredDetails `plist:"details,omitempty" json:"details,omitempty"`
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*CodePlatformSSORequired) SchemaPath() string { return "mdm/errors/psso.required.yaml" }

// CodePlatformSSORequiredDetails: A dictionary that contains additional data about the error
// code.
type CodePlatformSSORequiredDetails struct {
	// The URL of the profile containing an `ExtensibleSingleSignOn` profile payload that the
	// device uses to configure the SSO extension for Platform SSO.
	ProfileURL string `plist:"ProfileURL" json:"ProfileURL"`
	// A dictionary that specifies the package that the device uses to install an app with the
	// SSO app extension used for Platform SSO.
	Package CodePlatformSSORequiredDetailsPackage `plist:"Package,omitempty" json:"Package,omitempty"`
	// The URL the device uses to create an `ASWebAuthenticationSession` to trigger Platform
	// SSO authentication, once the profile and app are installed.
	AuthURL string `plist:"AuthURL" json:"AuthURL"`
}

// CodePlatformSSORequiredDetailsPackage: A dictionary that specifies the package that the
// device uses to install an app with the SSO app extension used for Platform SSO.
type CodePlatformSSORequiredDetailsPackage struct {
	// The URL of the app manifest, which needs to begin with `https:`.
	ManifestURL string `plist:"ManifestURL" json:"ManifestURL"`
	// An array of DER-encoded certificates to pin the connection when fetching the
	// `ManifestURL`.
	PinningCerts [][]byte `plist:"PinningCerts,omitempty" json:"PinningCerts,omitempty"`
	// If `true`, certificate revocation checks require a positive response when using
	// certificate pinning with `PinningCerts`.
	PinningRevocationCheckRequired *bool `plist:"PinningRevocationCheckRequired,omitempty" json:"PinningRevocationCheckRequired,omitempty"`
}

// CodeSoftwareUpdateRequired: An error response that indicates the system requires a
// software update.
//
// CodeSoftwareUpdateRequired corresponds to mdm/errors/softwareupdate.required.yaml (Error Code Software Update Required).
type CodeSoftwareUpdateRequired struct {
	// Indicates that the device needs to perform a software update before enrollment and setup
	// can proceed.
	Code string `plist:"code" json:"code"`
	// A description of the error. Only use this for logging purposes and don't display it to
	// the user.
	Description *string `plist:"description,omitempty" json:"description,omitempty"`
	// A description of the error to display to the user.
	Message *string `plist:"message,omitempty" json:"message,omitempty"`
	// A dictionary that contains additional data about the error code.
	Details CodeSoftwareUpdateRequiredDetails `plist:"details,omitempty" json:"details,omitempty"`
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*CodeSoftwareUpdateRequired) SchemaPath() string {
	return "mdm/errors/softwareupdate.required.yaml"
}

// CodeSoftwareUpdateRequiredDetails: A dictionary that contains additional data about the
// error code.
type CodeSoftwareUpdateRequiredDetails struct {
	// The OS version that the device needs to update to, for example, "16.1". This identifier
	// can include a supplemental version identifier, for example, "16.1 (a)".
	OSVersion string `plist:"OSVersion" json:"OSVersion"`
	// The build version that the device needs to update to, for example, "20A242. The systems
	// uses the build version for testing during seeding periods. This identifier can include a
	// supplemental version identifier, for example, "20A242a". If the `BuildVersion` isn't
	// consistent with the `OSVersion`, `OSVersion` take precedence.
	BuildVersion *string `plist:"BuildVersion,omitempty" json:"BuildVersion,omitempty"`
	// The device enrolls in the beta program, allowing enforced software updates to beta
	// program OS versions. The device remains in the beta program after the system completes
	// the enforced software update.
	RequireBetaProgram *CodeSoftwareUpdateRequiredDetailsRequireBetaProgram `plist:"RequireBetaProgram,omitempty" json:"RequireBetaProgram,omitempty"`
}

// CodeSoftwareUpdateRequiredDetailsRequireBetaProgram: The device enrolls in the beta
// program, allowing enforced software updates to beta program OS versions. The device
// remains in the beta program after the system completes the enforced software update.
type CodeSoftwareUpdateRequiredDetailsRequireBetaProgram struct {
	// A human readable description of the beta program.
	Description string `plist:"Description" json:"Description"`
	// The AxM seeding service token for the AxM organization the MDM server is part of. The
	// system uses this token to enroll the device in the corresponding beta program.
	Token string `plist:"Token" json:"Token"`
}

// UnrecognizedDevice: An error response that indicates a device needs to unenroll.
//
// UnrecognizedDevice corresponds to mdm/errors/unrecognized.device.yaml (Error Unrecognized Device).
type UnrecognizedDevice struct {
	// Indicates that the device is not recognized by the server. This causes the device to
	// unenroll from MDM.
	Code string `plist:"code" json:"code"`
	// A description of the error. Only use this for logging purposes and don't display it to
	// the user.
	Description *string `plist:"description,omitempty" json:"description,omitempty"`
	// A description of the error to display to the user.
	Message *string `plist:"message,omitempty" json:"message,omitempty"`
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*UnrecognizedDevice) SchemaPath() string { return "mdm/errors/unrecognized.device.yaml" }

// CodePairingTokenMissing: An error response that indicates a missing pairing token.
//
// CodePairingTokenMissing corresponds to mdm/errors/watch.pairing.token.missing.yaml (Error Code Pairing Token Missing).
type CodePairingTokenMissing struct {
	// Indicates that the pairing token, which the system requires to enroll the watch, is
	// missing.
	Code string `plist:"code" json:"code"`
	// A description of the error. Only use this for logging purposes and don't display it to
	// the user.
	Description *string `plist:"description,omitempty" json:"description,omitempty"`
	// A description of the error to display to the user.
	Message *string `plist:"message,omitempty" json:"message,omitempty"`
	// A dictionary that contains additional data about the error code.
	Details CodePairingTokenMissingDetails `plist:"details,omitempty" json:"details,omitempty"`
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*CodePairingTokenMissing) SchemaPath() string {
	return "mdm/errors/watch.pairing.token.missing.yaml"
}

// CodePairingTokenMissingDetails: A dictionary that contains additional data about the error
// code.
type CodePairingTokenMissingDetails struct {
	// The security token to pass to the phone's MDM server to create the pairing token. This
	// token needs to be a random UUID string.
	SecurityToken string `plist:"security-token" json:"security-token"`
}

// WellKnownFailed: An error response that indicates a well-known service discovery request
// failed.
//
// WellKnownFailed corresponds to mdm/errors/well-known.failed.yaml (Error Well-known Failed).
type WellKnownFailed struct {
	// Indicates that the well-known request has failed.
	Code string `plist:"code" json:"code"`
	// A description of the error. Only use this for logging purposes and don't display it to
	// the user.
	Description *string `plist:"description,omitempty" json:"description,omitempty"`
	// A description of the error to display to the user.
	Message *string `plist:"message,omitempty" json:"message,omitempty"`
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*WellKnownFailed) SchemaPath() string { return "mdm/errors/well-known.failed.yaml" }
