package schemagen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// ModulePath is the import path root of generated packages.
const ModulePath = "github.com/deploymenttheory/go-apple-mdm"

// Options control generation.
type Options struct {
	// Commit of apple/device-management the tree came from, for headers.
	Commit string
}

// Files maps a path relative to schema/ to file contents.
type Files map[string][]byte

// Generate emits every package from a built tree.
func Generate(pkgs []*Package, opts Options) (Files, error) {
	files := Files{}
	var names []string
	for _, p := range pkgs {
		e := &emitter{pkg: p, opts: opts}
		for name, src := range e.files() {
			formatted, err := format.Source(src)
			if err != nil {
				return nil, fmt.Errorf("%s/%s: format: %w\n%s", p.Name, name, err, numbered(src))
			}
			files[p.Name+"/"+name] = formatted
		}
		names = append(names, e.exportedNames()...)
	}
	sort.Strings(names)
	files["NAMES.lock"] = []byte(strings.Join(names, "\n") + "\n")
	return files, nil
}

// numbered prefixes source lines with numbers for error reports.
func numbered(src []byte) string {
	var sb strings.Builder
	for i, line := range strings.Split(string(src), "\n") {
		fmt.Fprintf(&sb, "%4d  %s\n", i+1, line)
	}
	return sb.String()
}

// emitter writes one package.
type emitter struct {
	pkg  *Package
	opts Options
}

func (e *emitter) header(extra ...string) string {
	var sb strings.Builder
	sb.WriteString("// Code generated by admgen; DO NOT EDIT.\n")
	fmt.Fprintf(&sb, "// Source: apple/device-management@%s\n", e.opts.Commit)
	for _, x := range extra {
		sb.WriteString("// " + x + "\n")
	}
	sb.WriteString("\npackage " + e.pkg.Name + "\n\n")
	return sb.String()
}

func (e *emitter) files() map[string][]byte {
	return map[string][]byte{
		"doc.gen.go":              e.docFile(),
		"types.gen.go":            e.typesFile(),
		"registry.gen.go":         e.registryFile(),
		"validate.gen.go":         e.validateFile(),
		"support.gen.go":          e.supportFile(),
		"conformance_gen_test.go": e.conformanceFile(),
	}
}

// familyDoc gives the Apple documentation page and YAML directory per family.
func familyDoc(f Family) (url, dir, what string) {
	switch f {
	case FamilyCommands:
		return "https://developer.apple.com/documentation/devicemanagement/commands-and-queries", "mdm/commands", "MDM commands and their responses"
	case FamilyCheckin:
		return "https://developer.apple.com/documentation/devicemanagement/check-in", "mdm/checkin", "MDM check-in messages"
	case FamilyErrors:
		return "https://developer.apple.com/documentation/devicemanagement/managing-connections", "mdm/errors", "enrollment error response bodies"
	case FamilyProfiles:
		return "https://developer.apple.com/documentation/devicemanagement/profile-specific-payload-keys", "mdm/profiles", "configuration profile payloads"
	case FamilyDDM:
		return "https://developer.apple.com/documentation/devicemanagement/devicemanagement-declarations", "declarative/declarations", "declarative device management declarations"
	case FamilyDDMProto:
		return "https://developer.apple.com/documentation/devicemanagement/declarativemanagementrequest", "declarative/protocol", "declarative device management protocol messages"
	case FamilyStatus:
		return "https://developer.apple.com/documentation/devicemanagement/status-items", "declarative/status", "declarative device management status items"
	case FamilyOther, familyUnknown:
	}
	return "https://developer.apple.com/documentation/devicemanagement", "other", "other device management data formats"
}

func (e *emitter) docFile() []byte {
	url, dir, what := familyDoc(e.pkg.Family)
	var sb strings.Builder
	sb.WriteString("// Code generated by admgen; DO NOT EDIT.\n")
	fmt.Fprintf(&sb, "// Source: apple/device-management@%s\n\n", e.opts.Commit)
	fmt.Fprintf(&sb, "// Package %s contains %s generated from Apple's device\n", e.pkg.Name, what)
	fmt.Fprintf(&sb, "// management schema (%s/ in\n", dir)
	sb.WriteString("// https://github.com/apple/device-management).\n//\n")
	fmt.Fprintf(&sb, "// Documentation: %s\n//\n", url)
	fmt.Fprintf(
		&sb,
		"// This package holds %d schema files and %d types. Every type carries\n",
		len(e.pkg.Schemas),
		len(e.pkg.Types),
	)
	sb.WriteString("// plist and json struct tags with Apple's wire keys, a Validate method\n")
	sb.WriteString(
		"// driven by the schema's constraints, and support metadata queryable through\n",
	)
	sb.WriteString("// Support(path) or the schema/support package.\n")
	fmt.Fprintf(&sb, "package %s\n", e.pkg.Name)
	return []byte(sb.String())
}

// wrap formats a documentation string as a Go comment block limited to the
// first paragraph and wrapped at width.
func wrap(prefix, text string, width int) string {
	text = strings.TrimSpace(text)
	if text == "" {
		return ""
	}
	if i := strings.Index(text, "\n\n"); i > 0 {
		text = text[:i]
	}
	text = strings.Join(strings.Fields(text), " ")
	var sb strings.Builder
	line := ""
	for w := range strings.FieldsSeq(text) {
		if line != "" && len(line)+1+len(w) > width {
			sb.WriteString(prefix + line + "\n")
			line = w
			continue
		}
		if line == "" {
			line = w
		} else {
			line += " " + w
		}
	}
	if line != "" {
		sb.WriteString(prefix + line + "\n")
	}
	return sb.String()
}

// goLiteral renders a YAML scalar as a Go literal for enum lists and
// sample values.
func goLiteral(v any) string {
	switch x := v.(type) {
	case string:
		return strconv.Quote(x)
	case int:
		return "int64(" + strconv.Itoa(x) + ")"
	case int64:
		return "int64(" + strconv.FormatInt(x, 10) + ")"
	case float64:
		s := strconv.FormatFloat(x, 'g', -1, 64)
		if !strings.ContainsAny(s, ".eE") {
			s += ".0"
		}
		return s
	case bool:
		return strconv.FormatBool(x)
	}
	return strconv.Quote(fmt.Sprint(v))
}

// supportPath is the key used in support tables.
func supportPath(top string, f *Field) string {
	p := f.Path
	if after, ok := strings.CutPrefix(p, "response:"); ok {
		p = "response." + after
	}
	return top + "." + p
}

// topName returns the top-level type name a TypeDef belongs to.
func topName(td *TypeDef) string {
	return TypeNameForSchema(td.Schema)
}

// exportedNames lists every exported identifier the package emits, for
// NAMES.lock.
func (e *emitter) exportedNames() []string {
	var out []string
	add := func(s string) { out = append(out, e.pkg.Name+"/"+s) }
	for _, td := range e.pkg.Types {
		add(td.Name)
		for _, f := range td.Fields {
			add(td.Name + "." + f.Name)
		}
	}
	for _, c := range e.constants() {
		add(c.name)
	}
	add("Registry")
	add("Entry")
	add("Support")
	add("IDs")
	add("ByID")
	if iface := e.familyInterface(); iface != "" {
		add(iface)
	}
	return out
}

type constant struct {
	name, value, doc string
}

// constants returns the wire identifier constants for the family.
func (e *emitter) constants() []constant {
	var out []constant
	for _, st := range e.pkg.Schemas {
		id, prefix := e.identifier(st)
		if id == "" {
			continue
		}
		out = append(out, constant{name: prefix + st.Name, value: id, doc: st.Schema.Title})
	}
	return out
}

// identifier returns the wire identifier of a schema and the constant
// prefix for its family, or "" when the schema has none.
func (e *emitter) identifier(st *SchemaType) (id, prefix string) {
	p := st.Schema.Payload
	switch e.pkg.Family {
	case FamilyCommands:
		return p.RequestType, "RequestType"
	case FamilyCheckin:
		return p.RequestType, "MessageType"
	case FamilyProfiles:
		return p.PayloadType, "PayloadType"
	case FamilyDDM:
		if st.Schema.Kind == KindCredential {
			return p.CredentialType, "CredentialType"
		}
		if st.Schema.Kind == KindBase {
			return "", ""
		}
		return p.DeclarationType, "DeclarationType"
	case FamilyStatus:
		return p.StatusItemType, "StatusItemType"
	case FamilyErrors:
		for _, k := range st.Schema.PayloadKeys {
			if k.Key == "code" && len(k.RangeList) == 1 {
				return fmt.Sprint(k.RangeList[0]), "ErrorCode"
			}
		}
		return "", ""
	case FamilyDDMProto, FamilyOther, familyUnknown:
		return st.Name, "Type"
	}
	return "", ""
}

// familyInterface names the marker interface for the family's top-level
// types, and the method that returns the wire identifier.
func (e *emitter) familyInterface() string {
	switch e.pkg.Family {
	case FamilyCommands:
		return "Command"
	case FamilyCheckin:
		return "Message"
	case FamilyProfiles:
		return "Payload"
	case FamilyDDM:
		return "Declaration"
	case FamilyStatus:
		return "Item"
	case FamilyErrors:
		return "Error"
	case FamilyDDMProto, FamilyOther, familyUnknown:
		return "Object"
	}
	return ""
}

func (e *emitter) identifierMethod() string {
	switch e.pkg.Family {
	case FamilyCommands:
		return "RequestTypeName"
	case FamilyCheckin:
		return "MessageTypeName"
	case FamilyProfiles:
		return "PayloadTypeName"
	case FamilyDDM:
		return "DeclarationTypeName"
	case FamilyStatus:
		return "StatusItemTypeName"
	case FamilyErrors:
		return "ErrorCodeName"
	case FamilyDDMProto, FamilyOther, familyUnknown:
		return "TypeName"
	}
	return ""
}

// reservedFieldNames are method names generated on every type; a wire key
// mapping to one of them must be renamed through fieldNameOverrides.
var reservedFieldNames = map[string]bool{
	"Validate":                true,
	"SchemaPath":              true,
	"RequestTypeName":         true,
	"MessageTypeName":         true,
	"PayloadTypeName":         true,
	"DeclarationTypeName":     true,
	"StatusItemTypeName":      true,
	"ErrorCodeName":           true,
	"TypeName":                true,
	"DeclarationKind":         true,
	"ResponseRequestTypeName": true,
	"MarshalJSON":             true,
	"UnmarshalJSON":           true,
	"CredentialTypeName":      true,
}

func buf() *bytes.Buffer { return &bytes.Buffer{} }
