package schemagen

import (
	"errors"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

func TestGenerateWholeTree(t *testing.T) {
	t.Parallel()
	files, err := Run(schemaRoot(t), Options{Commit: "test"})
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	// 8 packages x 6 files + EXPORTED_IDENTIFIERS.lock, plus reasons.gen.go for the two
	// packages whose schemas declare a reason vocabulary.
	if len(files) != 8*6+1+2 {
		t.Fatalf("got %d files", len(files))
	}
	for _, name := range []string{"ddm/reasons.gen.go", "status/reasons.gen.go"} {
		if _, ok := files[name]; !ok {
			t.Errorf("missing %s", name)
		}
	}
	// A package whose schemas declare no reasons must not carry an empty
	// vocabulary, which would read as "Apple defines none" rather than
	// "Apple defines none here".
	if _, ok := files["commands/reasons.gen.go"]; ok {
		t.Error("commands has no reasons but a reasons.gen.go was emitted")
	}
	for name, data := range files {
		if name == "EXPORTED_IDENTIFIERS.lock" {
			continue
		}
		if _, err := format.Source(data); err != nil {
			t.Errorf("%s: not gofmt-clean: %v", name, err)
		}
		if !strings.HasPrefix(string(data), "// Code generated by admgen; DO NOT EDIT.") {
			t.Errorf("%s: missing generated header", name)
		}
	}
	names := strings.Split(strings.TrimSpace(string(files["EXPORTED_IDENTIFIERS.lock"])), "\n")
	if !sort.StringsAreSorted(names) || len(names) < 1000 {
		t.Errorf("EXPORTED_IDENTIFIERS.lock has %d entries, sorted=%v", len(names), sort.StringsAreSorted(names))
	}
	for _, want := range []string{"commands/DeviceLock", "commands/DeviceLock.Message", "commands/Registry", "status/DeviceModelFamily.Value", "ddm/Declaration", "ddm/ReasonErrorActivationFailed", "ddm/ReasonCodes", "status/ReasonInfoUpdateAvailable"} {
		if sort.SearchStrings(names, want) >= len(names) || names[sort.SearchStrings(names, want)] != want {
			t.Errorf("EXPORTED_IDENTIFIERS.lock missing %s", want)
		}
	}
}

func TestWriteAndVerify(t *testing.T) {
	t.Parallel()
	root := schemaRoot(t)
	out := t.TempDir()
	files, err := Run(root, Options{Commit: "test"})
	if err != nil {
		t.Fatal(err)
	}
	// A stale generated file must be removed by Write; a hand-written file kept.
	if err := os.MkdirAll(filepath.Join(out, "old"), 0o750); err != nil {
		t.Fatal(err)
	}
	stale := filepath.Join(out, "old", "gone.gen.go")
	keep := filepath.Join(out, "old", "keep.go")
	for _, p := range []string{stale, keep} {
		if err := os.WriteFile(p, []byte("package old\n"), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	if err := Write(out, files); err != nil {
		t.Fatalf("Write: %v", err)
	}
	if _, err := os.Stat(stale); !errors.Is(err, os.ErrNotExist) {
		t.Error("stale generated file was not removed")
	}
	if _, err := os.Stat(keep); err != nil {
		t.Error("hand-written file was removed")
	}
	if err := Verify(root, out, Options{Commit: "test"}); err != nil {
		t.Fatalf("Verify after Write: %v", err)
	}
	// Different commit changes headers: verify must fail.
	if err := Verify(root, out, Options{Commit: "other"}); !errors.Is(err, ErrVerify) {
		t.Fatalf("Verify with other commit: %v", err)
	}
	// A name that was once generated stays in the lock: a stale entry without a
	// RENAMES entry fails verify, and generate must not drop it either.
	lock := filepath.Join(out, "EXPORTED_IDENTIFIERS.lock")
	if err := os.WriteFile(lock, append(files["EXPORTED_IDENTIFIERS.lock"], []byte("commands/Obsolete\n")...), 0o600); err != nil {
		t.Fatal(err)
	}
	err = Verify(root, out, Options{Commit: "test"})
	if !errors.Is(err, ErrVerify) || !strings.Contains(err.Error(), "commands/Obsolete") {
		t.Fatalf("Verify with removed name: %v", err)
	}
	if err := Write(out, files); err != nil {
		t.Fatal(err)
	}
	if data, _ := os.ReadFile(lock); !strings.Contains(string(data), "commands/Obsolete") {
		t.Fatal("generate dropped a locked name without a RENAMES entry")
	}
	// With a RENAMES entry, generate drops the name and verify passes.
	if err := os.WriteFile(filepath.Join(out, "ALLOWED_REMOVALS.md"), []byte("# Renames\n\n- `commands/Obsolete` replaced by nothing\n- not a rename line\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := Verify(root, out, Options{Commit: "test"}); !errors.Is(err, ErrVerify) {
		t.Fatalf("Verify before regenerating should report the lock as out of date, got %v", err)
	}
	if err := Write(out, files); err != nil {
		t.Fatal(err)
	}
	if data, _ := os.ReadFile(lock); strings.Contains(string(data), "commands/Obsolete") {
		t.Fatal("generate kept a name ALLOWED_REMOVALS.md allows to drop")
	}
	if err := Verify(root, out, Options{Commit: "test"}); err != nil {
		t.Fatalf("Verify with RENAMES entry: %v", err)
	}
	// A missing file fails verify.
	if err := os.Remove(filepath.Join(out, "commands", "doc.gen.go")); err != nil {
		t.Fatal(err)
	}
	if err := Verify(root, out, Options{Commit: "test"}); !errors.Is(err, ErrVerify) {
		t.Fatalf("Verify with missing file: %v", err)
	}
	// Errors from bad roots.
	if _, err := Run(filepath.Join(out, "nope"), Options{}); err == nil {
		t.Error("Run with bad root should fail")
	}
	if err := Verify(filepath.Join(out, "nope"), out, Options{}); err == nil {
		t.Error("Verify with bad root should fail")
	}
	if err := Verify(root, filepath.Join(out, "missing-out"), Options{Commit: "test"}); err == nil {
		t.Error("Verify with missing out dir should fail")
	}
	if err := Write(filepath.Join(keep, "not-a-dir"), files); err == nil {
		t.Error("Write into a file path should fail")
	}
}

func TestReadGeneratedFrom(t *testing.T) {
	t.Parallel()
	p, err := ReadGeneratedFrom(filepath.Join("..", "..", "schema", "GENERATED_FROM.json"))
	if err != nil {
		t.Skipf("provenance not available: %v", err)
	}
	if p.Commit == "" || p.Source == "" {
		t.Errorf("incomplete provenance: %+v", p)
	}
	if _, err := ReadGeneratedFrom(filepath.Join(t.TempDir(), "missing.json")); err == nil {
		t.Error("expected error for missing file")
	}
	bad := filepath.Join(t.TempDir(), "bad.json")
	if err := os.WriteFile(bad, []byte("{"), 0o600); err != nil {
		t.Fatal(err)
	}
	if _, err := ReadGeneratedFrom(bad); err == nil {
		t.Error("expected error for malformed json")
	}
}

func TestEmitHelpers(t *testing.T) {
	t.Parallel()
	if got := wrap("// ", "one two three four five", 12); got != "// one two\n// three four\n// five\n" {
		t.Errorf("wrap = %q", got)
	}
	if wrap("", "", 10) != "" || wrap("", "first\n\nsecond", 80) != "first\n" {
		t.Error("wrap edge cases")
	}
	cases := map[any]string{"s": `"s"`, 1: "int64(1)", int64(2): "int64(2)", 1.5: "1.5", 2.0: "2.0", true: "true"}
	for in, want := range cases {
		if got := goLiteral(in); got != want {
			t.Errorf("goLiteral(%v) = %s, want %s", in, got, want)
		}
	}
	if goLiteral([]int{1}) != `"[1]"` {
		t.Error("goLiteral fallback")
	}
	if floatPtr(nil) != "nil" || floatPtr(new(float64)) != "new(0.0)" {
		t.Error("floatPtr")
	}
	f := &Field{Path: "response:A.B"}
	if supportPath("T", f) != "T.response.A.B" {
		t.Errorf("supportPath = %s", supportPath("T", f))
	}
	for _, k := range []Kind{KindActivation, KindAsset, KindConfiguration, KindManagement, KindCredential, KindBase, KindDefault} {
		if kindConst(k) == "" {
			t.Error("kindConst")
		}
	}
	if osConst("weird") != `OS("weird")` {
		t.Error("osConst fallback")
	}
	e := &emitter{pkg: &Package{Family: familyUnknown}}
	if e.familyInterface() != "Object" || e.identifierMethod() != "TypeName" {
		t.Error("unknown family defaults")
	}
	url, dir, what := familyDoc(familyUnknown)
	if url == "" || dir != "other" || what == "" {
		t.Error("familyDoc fallback")
	}
	if got := numbered([]byte("a\nb")); !strings.Contains(got, "   1  a") {
		t.Errorf("numbered = %q", got)
	}
}

func TestGenerateFormatFailureIsReported(t *testing.T) {
	t.Parallel()
	// A type name that is not a valid identifier forces a format error.
	s := &Schema{Title: "Bad", Path: "mdm/commands/bad.yaml", Family: FamilyCommands, Payload: Payload{RequestType: "Bad"}}
	pkgs, err := Build(&Tree{Schemas: []*Schema{s}})
	if err != nil {
		t.Fatal(err)
	}
	pkgs[0].Types[0].Name = "not valid"
	if _, err := Generate(pkgs, Options{}); err == nil || !strings.Contains(err.Error(), "format") {
		t.Fatalf("expected format error, got %v", err)
	}
}

func TestSupportOverlayErrors(t *testing.T) {
	t.Parallel()
	for _, src := range []*OSSupport{{Introduced: "x"}, {Deprecated: "x"}, {Removed: "x"}} {
		if err := overlay(&supportOS{}, src); err == nil {
			t.Errorf("expected version error for %+v", src)
		}
	}
	st := &SchemaType{Schema: &Schema{Path: "p", Payload: Payload{SupportedOS: SupportedOS{IOS: &OSSupport{Introduced: "bad"}}}}}
	if _, err := effective(st); err == nil {
		t.Error("effective should fail on bad payload version")
	}
	key := Key{Key: "K", Type: "<string>", SupportedOS: &SupportedOS{MacOS: &OSSupport{Removed: "bad"}}}
	st = &SchemaType{Name: "T", Schema: &Schema{Path: "p"}, Request: &TypeDef{Fields: []*Field{{Name: "K", Key: "K", Path: "K", Src: &key}}}}
	if _, err := effective(st); err == nil {
		t.Error("effective should fail on bad key version")
	}
}
