package lab

// Catalogue returns a fresh module inventory in stable ID order. Modules without an
// explicit Stage take their theme's lifecycle stage.
func Catalogue() []Module {
	modules := []Module{
		{
			ID:         "E2E-001",
			Name:       "Pre-issued identity enrols: Authenticate, TokenUpdate, Idle, no commands",
			Theme:      "mdm",
			Regression: "TestE2E_EnrollIdle",
			Modes:      []string{"simulated"},
			Steps:      scenario(enrollIdle),
		},
		{
			ID:         "E2E-002",
			Name:       "Three commands queued, delivered in order, acknowledged with typed responses",
			Theme:      "mdm",
			Regression: "TestE2E_CommandsInOrder",
			Modes:      []string{"simulated"},
			Steps:      scenario(commandsInOrder),
		},
		{
			ID:         "E2E-003",
			Name:       "Device answers NotNow, command is retried after backoff",
			Theme:      "mdm",
			Regression: "TestE2E_NotNowBackoff",
			Modes:      []string{"simulated"},
			Steps:      scenario(notNow),
		},
		{
			ID:         "E2E-004",
			Name:       "Device ErrorChain is available through the command result API",
			Theme:      "mdm",
			Regression: "TestE2E_CommandError",
			Modes:      []string{"simulated"},
			Steps:      scenario(commandError),
		},
		{
			ID:         "E2E-005",
			Name:       "Re-enrollment denies an unauthorized new identity and preserves the pending queue",
			Theme:      "mdm",
			Regression: "TestE2E_Reenroll",
			Modes:      []string{"simulated"},
			Steps:      scenario(reenroll),
		},
		{
			ID:         "E2E-006",
			Name:       "SCEP enrollment from an unsigned profile, push, command",
			Theme:      "enrollment",
			Regression: "TestE2E_SCEPEnrollPush",
			Modes:      []string{"simulated"},
			Steps:      scenario(scepPush),
		},
		{
			ID:         "E2E-007",
			Name:       "APNs 410 is returned as an invalid-token outcome",
			Theme:      "apns",
			Regression: "TestE2E_PushInvalidToken",
			Modes:      []string{"simulated"},
			Steps:      scenario(invalidToken),
		},
		{
			ID:         "E2E-008",
			Name:       "Assigned declarations reach the device and its DDM status is persisted",
			Theme:      "ddm",
			Regression: "TestE2E_DDMRoundTrip",
			Modes:      []string{"simulated"},
			Steps:      scenario(ddmRoundTrip),
		},
		{
			ID:         "E2E-009",
			Name:       "An activation predicate produces inactive declaration status",
			Theme:      "ddm",
			Regression: "TestE2E_DDMPredicate",
			Modes:      []string{"simulated"},
			Steps:      scenario(ddmPredicate),
		},
		{
			ID:         "E2E-011",
			Name:       "DEP token import, profile configuration and device synchronization through the admin API",
			Theme:      "dep",
			Regression: "TestE2E_DEPAssign",
			Modes:      []string{"simulated"},
			Steps:      scenario(depAssign),
		},
		{
			ID:         "E2E-012",
			Name:       "Mac and iPhone service discovery and account-driven enrollment with apple-as-web",
			Theme:      "accountdriven",
			Regression: "TestE2E_ServiceDiscovery",
			Modes:      []string{"simulated"},
			Steps:      scenario(accountDriven),
		},
		{
			ID:         "E2E-013",
			Settings:   map[string]string{"DM_REQUIRE_USER_AUTH": "true"},
			Name:       "Digest user authentication, command isolation for two users, and device-only command rejection",
			Theme:      "user",
			Regression: "TestE2E_UserChannel",
			Modes:      []string{"simulated"},
			Steps:      scenario(userChannels),
		},
		{
			ID:         "E2E-014",
			Settings:   map[string]string{"DM_IDENTITY": "acme"},
			Name:       "ACME attested enrollment with replay, wrong-key, stale, missing and foreign-attestation rejection",
			Theme:      "acme",
			Regression: "TestE2E_ACMEAttest",
			Modes:      []string{"simulated"},
			Steps:      scenario(acmeEnroll),
		},
		{
			ID:         "E2E-016",
			Name:       "OTA profile service: phase 1 signed by the device certificate with the challenge, SCEP, phase 2 signed by the new identity, final profile enrolls",
			Theme:      "ota",
			Regression: "TestE2E_OTAProfileService",
			Modes:      []string{"simulated"},
			Steps:      scenario(otaEnroll),
		},
		{
			ID:         "E2E-017",
			Name:       "CheckOut clears persisted DDM status and prevents reactivation",
			Theme:      "ddm",
			Regression: "TestE2E_DDMCheckOutClears",
			Modes:      []string{"simulated"},
			Steps:      scenario(ddmCheckout),
		},
		{
			ID:         "E2E-018",
			Name:       "ADE enrollment through the configured reference-server endpoint",
			Theme:      "ade",
			Regression: "TestE2E_ADEWebViewAuth",
			Modes:      []string{"simulated"},
			Steps:      scenario(adeEnroll),
		},
		{
			ID:         "E2E-019",
			Settings:   map[string]string{"DM_ACCOUNT_DRIVEN_METHOD": "apple-oauth2"},
			Name:       "Mac and iPhone account-driven enrollment with apple-oauth2 authorization code flow",
			Theme:      "accountdriven",
			Regression: "TestE2E_AccountDrivenOAuth2",
			Modes:      []string{"simulated"},
			Steps:      scenario(accountDriven),
		},
		{
			ID:         "E2E-020",
			Name:       "Shared iPad device and user commands reach their respective channels",
			Theme:      "sharedipad",
			Regression: "TestE2E_SharedIPad",
			Modes:      []string{"simulated"},
			Steps:      scenario(sharedIPad),
		},
		{
			ID:         "E2E-021",
			Name:       "ABM server listing, bounded device listing, assignment completion and unassignment",
			Theme:      "abm",
			Regression: "TestE2E_ABMAssignDevices",
			Modes:      []string{"simulated"},
			Steps:      scenario(abmAssign),
		},
		{
			ID:         "E2E-023",
			Settings:   map[string]string{"DM_IDENTITY": "acme"},
			Name:       "`DeviceInformation` with `DeviceAttestationNonce`: the returned `DevicePropertiesAttestation` chain verifies and its properties are read; the device returns its cached attestation for a repeated nonce; a tampered chain is refused",
			Theme:      "attestation",
			Regression: "TestE2E_DeviceAttestation",
			Modes:      []string{"simulated"},
			Steps:      scenario(deviceAttestation),
		},
		{
			ID:         "E2E-024",
			Name:       "Admin route discovery includes authorization actions and rejects an invalid credential",
			Theme:      "admin",
			Regression: "TestE2E_AdminCLI",
			Modes:      []string{"simulated"},
			Steps:      scenario(adminRoutes),
		},
		{
			ID:         "E2E-025",
			Settings:   map[string]string{"DM_RETURN_TO_SERVICE": "true"},
			Name:       "Return to service: a device escrows a bootstrap token, asks for its return-to-service configuration, and the response carries the escrowed token for the device to use during Return to Service",
			Theme:      "returntoservice",
			Regression: "TestE2E_ReturnToService",
			Modes:      []string{"simulated"},
			Steps:      scenario(returnEnabled),
		},
		{
			ID:         "E2E-026",
			Name:       "An unconfigured return-to-service policy reports Enabled false",
			Theme:      "returntoservice",
			Regression: "TestE2E_ReturnToServiceDisabledByDefault",
			Modes:      []string{"simulated"},
			Steps:      scenario(returnDisabled),
		},
		{
			ID:    "E2E-027",
			Name:  "Public MDMServiceConfig, HTTPS anchors and minimal trust profile agree",
			Theme: "enrollment",
			Modes: []string{"simulated", "live"},
			Steps: scenario(serviceDiscovery),
		},
		{
			ID:    "E2E-028",
			Name:  "SCEP profile replacement rotates identity and management continues",
			Theme: "replacement",
			Modes: []string{"simulated"},
			Steps: scenario(replacementScenario("scep", false)),
		},
		{
			ID:    "E2E-029",
			Name:  "Failed SCEP profile replacement preserves the working enrollment",
			Theme: "replacement",
			Modes: []string{"simulated"},
			Steps: scenario(replacementScenario("scep", true)),
		},
		{
			ID:       "E2E-030",
			Name:     "ACME profile replacement rotates identity and management continues",
			Theme:    "replacement",
			Modes:    []string{"simulated"},
			Settings: map[string]string{"DM_IDENTITY": "acme"},
			Steps:    scenario(replacementScenario("acme", false)),
		},
		{
			ID:       "E2E-031",
			Name:     "Failed ACME profile replacement preserves the working enrollment",
			Theme:    "replacement",
			Modes:    []string{"simulated"},
			Settings: map[string]string{"DM_IDENTITY": "acme"},
			Steps:    scenario(replacementScenario("acme", true)),
		},
		{
			ID:    "E2E-032",
			Name:  "Single-use enrollment link: landing page, profile download, enrollment and refused reuse",
			Theme: "enrollment",
			Modes: []string{"simulated"},
			Steps: scenario(enrollmentLinkEnroll),
		},
		{
			ID:    "APP-001",
			Name:  "App alert accepted with certificate authentication",
			Theme: "apppush",
			Modes: []string{"simulated", "live"},
			Steps: scenario(appAlert),
		},
		{
			ID:    "APP-002",
			Name:  "App background push accepted with certificate authentication",
			Theme: "apppush",
			Modes: []string{"simulated", "live"},
			Steps: scenario(appBackground),
		},
		{
			ID:    "APP-003",
			Name:  "A renewed app certificate advances the credential version and supports another send",
			Theme: "apppush",
			Modes: []string{"simulated"},
			Steps: scenario(appRenewal),
		},
		{
			ID:    "LIVE-004",
			Name:  "DDM subscriptions report OS/build and remove temporary declarations",
			Theme: "ddm",
			Modes: []string{
				"live",
			},
			Prerequisites: []string{
				"completed enrollment",
				"MDM push identity",
				"automatic status subscriptions enabled",
			},
			Steps: scenario(liveDDM),
		},
		{
			ID:    "LIVE-005",
			Name:  "macOS 26 device Blueprint activation, profile replacement and removal",
			Theme: "blueprints", Modes: []string{"live"},
			Prerequisites: []string{"enrolled macOS 26 test device", "MDM push identity", "automatic status subscriptions enabled"},
			Steps:         scenario(liveBlueprints(false)),
		},
		{
			ID:    "LIVE-006",
			Name:  "macOS 26 user Blueprint activation, profile replacement and removal",
			Theme: "blueprints", Modes: []string{"live"},
			Prerequisites: []string{"enrolled macOS 26 test device", "logged-in MDM-enabled user and -user-id", "MDM push identity", "automatic status subscriptions enabled"},
			Steps:         scenario(liveBlueprints(true)),
		},
		{
			ID:    "LIVE-002",
			Name:  "ACME Mac enrollment, installing user channel and APNs-triggered inventory",
			Theme: "enrollment",
			Modes: []string{"live"},
			Prerequisites: []string{
				"manually installed ACME enrollment profile",
				"MDM push identity",
				"Mac device ID",
			},
			Steps: scenario(liveEnrollment("acme")),
		},
		{
			ID:    "LIVE-003",
			Name:  "SCEP Mac enrollment, installing user channel and APNs-triggered inventory",
			Theme: "enrollment",
			Modes: []string{"live"},
			Prerequisites: []string{
				"manually installed SCEP enrollment profile",
				"MDM push identity",
				"Mac device ID",
			},
			Steps: scenario(liveEnrollment("scep")),
		},
		{
			ID:    "LIVE-001",
			Name:  "Enrolled device acknowledges DeviceInformation after an APNs wake",
			Theme: "mdm",
			Modes: []string{"live"},
			Prerequisites: []string{
				"device ID",
				"completed enrollment and TokenUpdate",
				"MDM push identity",
			},
			Steps: scenario(liveMDM),
		},
	}
	for i := range modules {
		if modules[i].Stage == 0 {
			modules[i].Stage = themeStages[modules[i].Theme]
		}
	}
	return modules
}
