package replycerts

import (
	"bytes"
	"context"
	"crypto"
	"crypto/sha256"
	"crypto/x509"
	"encoding/hex"
	json "encoding/json/v2"
	"errors"
	"fmt"
	"time"

	"github.com/deploymenttheory/go-apple-dm/devicemanagement/appleplatformservices/dep"
	"github.com/deploymenttheory/go-apple-dm/devicemanagement/mdmprotocol/mdm"
	"github.com/deploymenttheory/go-apple-dm/devicemanagement/mdmprotocol/profile"
	"github.com/deploymenttheory/go-apple-dm/devicemanagement/schema/commands"
	"github.com/deploymenttheory/go-apple-dm/devicemanagement/state"
)

// Errors deliberately omit certificate, password and private-key bytes.
var (
	ErrInvalid  = errors.New("replycerts: invalid command or stored identity")
	ErrConflict = errors.New(
		"replycerts: command identity or encryption certificate conflicts with workflow",
	)
)

// Manager creates one RSA certificate per command. Concurrent/retried prepares
// select the same persisted key. New commands get new keys automatically.
// A certificate is never renewed in place after binding it to a command.
type Manager struct{ Store state.Store }

type binding struct {
	Digest          string    `json:"digest"`
	Certificate     []byte    `json:"certificate"`
	Key             []byte    `json:"key"`
	CreatedAt       time.Time `json:"createdAt"`
	ProfileUUID     string    `json:"profileUUID,omitempty"`
	CertificateUUID string    `json:"certificateUUID,omitempty"`
	EscrowUUID      string    `json:"escrowUUID,omitempty"`
}

func recordKey(id mdm.EnrollmentID, uuid string) string {
	data, _ := json.Marshal(struct {
		Enrollment mdm.EnrollmentID `json:"enrollment"`
		Command    string           `json:"command"`
	}{id, uuid})
	h := sha256.Sum256(data)
	return "pki/command-encryption/" + hex.EncodeToString(h[:])
}

// Prepare fills ReplyEncryptionCertificate for a personal-key rotation, or
// NewCertificate for an institutional-key rotation, before queueing. It rejects
// externally supplied encryption certificates. A retry may include the exact
// certificate already generated by this workflow. Other commands pass through.
// The enrollment and command UUID bind the retained key to the intended reply.
func (m *Manager) Prepare(
	ctx context.Context,
	id mdm.EnrollmentID,
	command *mdm.Command,
) (*mdm.Command, error) {
	if command == nil {
		return nil, ErrInvalid
	}
	decoded, err := mdm.DecodeCommand(command.Raw)
	if err != nil {
		return nil, ErrInvalid
	}
	payload, ok := decoded.Payload.(*commands.RotateFileVaultKey)
	if !ok {
		return command, nil
	}
	if m.Store == nil || id.Channel != mdm.ChannelDevice || id.ID == "" ||
		decoded.UUID != command.UUID {
		return nil, ErrInvalid
	}
	var supplied []byte
	switch payload.KeyType {
	case "personal":
		if payload.FileVaultUnlock.Password == nil || *payload.FileVaultUnlock.Password == "" ||
			len(payload.NewCertificate) != 0 {
			return nil, ErrInvalid
		}
		supplied = payload.ReplyEncryptionCertificate
		payload.ReplyEncryptionCertificate = nil
	case "institutional":
		unlock := payload.FileVaultUnlock
		password := unlock.Password != nil && *unlock.Password != ""
		export := len(unlock.PrivateKeyExport) > 0 && unlock.PrivateKeyExportPassword != nil &&
			*unlock.PrivateKeyExportPassword != ""
		if (!password && !export) || len(payload.ReplyEncryptionCertificate) != 0 {
			return nil, ErrInvalid
		}
		supplied = payload.NewCertificate
		payload.NewCertificate = nil
	default:
		return nil, ErrInvalid
	}
	normalized, err := mdm.NewCommand(payload, mdm.WithUUID(command.UUID))
	if err != nil {
		return nil, fmt.Errorf("replycerts: normalize: %w", err)
	}
	digest := sha256.Sum256(normalized.Raw)
	selected, err := m.selectIdentity(ctx, id, command.UUID, digest, supplied, false)
	if err != nil {
		return nil, err
	}
	cert, _, err := material(selected)
	if err != nil {
		return nil, err
	}
	if len(supplied) != 0 && !bytes.Equal(supplied, cert.Raw) {
		return nil, ErrConflict
	}
	if payload.KeyType == "personal" {
		payload.ReplyEncryptionCertificate = cert.Raw
	} else {
		payload.NewCertificate = cert.Raw
	}
	prepared, err := mdm.NewCommand(payload, mdm.WithUUID(command.UUID))
	if err != nil {
		return nil, fmt.Errorf("replycerts: command: %w", err)
	}
	return prepared, nil
}

// Recipient loads the exact retained certificate/key after an authenticated
// response. Pass them to cms.DecryptEnvelope for EncryptedNewRecoveryKey or
// the CMS envelope produced by a profile prepared with EscrowProfile.
// This privileged API must never be exposed as an administrative key export.
func (m *Manager) Recipient(
	ctx context.Context,
	id mdm.EnrollmentID,
	commandUUID string,
) (*x509.Certificate, crypto.Decrypter, error) {
	if m.Store == nil || id.ID == "" || commandUUID == "" {
		return nil, nil, ErrInvalid
	}
	r, err := m.Store.Get(ctx, recordKey(id, commandUUID))
	if err != nil {
		return nil, nil, fmt.Errorf("replycerts: load: %w", err)
	}
	var selected binding
	if json.Unmarshal(r.Value, &selected) != nil {
		return nil, nil, ErrInvalid
	}
	return material(selected)
}

func material(b binding) (*x509.Certificate, crypto.Decrypter, error) {
	pair := dep.Keypair{CertPEM: b.Certificate, KeyPEM: b.Key}
	cert, err := pair.Certificate()
	if err != nil {
		return nil, nil, ErrInvalid
	}
	key, err := pair.PrivateKey()
	if err != nil || !key.PublicKey.Equal(cert.PublicKey) {
		return nil, nil, ErrInvalid
	}
	return cert, key, nil
}

// Forget removes a settled workflow's key. The caller must first save
// the recovered secret in persistent storage and rule out pending/replayed
// responses, or deliberately abandon the command. There is intentionally no
// age-based automatic deletion.
// For escrow profiles, retain the binding while the profile remains installed
// or any encrypted recovery key still depends on it, regardless of command status.
func (m *Manager) Forget(ctx context.Context, id mdm.EnrollmentID, commandUUID string) error {
	if m.Store == nil || id.ID == "" || commandUUID == "" {
		return ErrInvalid
	}
	key := recordKey(id, commandUUID)
	if err := m.Store.Update(
		ctx,
		[]string{key},
		func(tx state.Tx) error { return tx.Delete(ctx, key) },
	); err != nil {
		return fmt.Errorf("replycerts: forget: %w", err)
	}
	return nil
}

func (m *Manager) selectIdentity(
	ctx context.Context,
	id mdm.EnrollmentID,
	commandUUID string,
	digest [32]byte,
	supplied []byte,
	escrow bool,
) (binding, error) {
	key := recordKey(id, commandUUID)
	var selected binding
	err := m.Store.Update(ctx, []string{key}, func(tx state.Tx) error {
		r, readErr := tx.Get(ctx, key)
		if readErr == nil {
			if json.Unmarshal(r.Value, &selected) != nil {
				return ErrInvalid
			}
			if selected.Digest != hex.EncodeToString(digest[:]) {
				return ErrConflict
			}
			return nil
		}
		if !errors.Is(readErr, state.ErrNotFound) {
			return fmt.Errorf("replycerts: read binding: %w", readErr)
		}
		if len(supplied) != 0 {
			return ErrConflict
		}
		// Existing Go-only RSA/X.509 generation; this is a distinct key from DEP,
		// APNs, HTTPS and the enrollment issuer. It is never uploaded to Apple.
		pair, genErr := dep.GenerateTokenPKI("MDM FileVault encryption", 365*24*time.Hour, tx.Now())
		if genErr != nil {
			return fmt.Errorf("replycerts: generate: %w", genErr)
		}
		selected = binding{
			Digest:      hex.EncodeToString(digest[:]),
			Certificate: pair.CertPEM,
			Key:         pair.KeyPEM,
			CreatedAt:   tx.Now(),
		}
		if escrow {
			selected.ProfileUUID = profile.NewUUID()
			selected.CertificateUUID = profile.NewUUID()
			selected.EscrowUUID = profile.NewUUID()
		}
		data, encodeErr := json.Marshal(selected)
		if encodeErr != nil {
			return fmt.Errorf("replycerts: encode: %w", encodeErr)
		}
		// No expiry: even an expired certificate's key decrypts delayed replies.
		if err := tx.Put(ctx, state.Record{Key: key, Value: data}); err != nil {
			return fmt.Errorf("replycerts: persist: %w", err)
		}
		return nil
	})
	if err != nil {
		return binding{}, fmt.Errorf("replycerts: prepare: %w", err)
	}
	return selected, nil
}
