// Code generated by admgen; DO NOT EDIT.
// Source: apple/device-management@67045e2fa06f528b196c01edee6a8bf88b844beb

// Package profiles contains configuration profile payloads generated from Apple's device
// management schema (mdm/profiles/ in
// https://github.com/apple/device-management).
//
// Documentation: https://developer.apple.com/documentation/devicemanagement/profile-specific-payload-keys
//
// This package holds 127 schema files and 230 types. Every type carries
// plist and json struct tags with Apple's wire keys, a Validate method
// driven by the schema's constraints, and support metadata queryable through
// Support(path) or the schema/support package.
package profiles
