// Code generated by schemagen; DO NOT EDIT.
// Source: apple/device-management@67045e2fa06f528b196c01edee6a8bf88b844beb

// Package commands holds the MDM commands and their responses generated from
// Apple's device management schema: 65 schema files and 220 types.
//
// # Design
//
// Apple publishes the wire format of the MDM commands and their responses as
// YAML in https://github.com/apple/device-management, pinned here as a git
// submodule. Generating this package from that pinned commit derives the
// wire types, validation, and support metadata from Apple's schema (decision
// record 0003). Every type carries plist and json struct tags with Apple's
// wire keys, a Validate method driven by the schema's constraints, and
// support metadata queryable through Support(path) or the
// devicemanagement/schema/support package.
//
// Edit the generator to change this package. schemagen verify fails when
// regeneration would change it or drop an exported name
// (devicemanagement/schema/EXPORTED_IDENTIFIERS.lock). Protocol semantics
// that Apple documents only in prose live in the hand-written packages that
// import this one.
//
// # References
//
//   - Decision record 0001: https://github.com/deploymenttheory/go-apple-dm/blob/main/docs/research/decisions/0001-architecture.md
//   - Decision record 0003: https://github.com/deploymenttheory/go-apple-dm/blob/main/docs/research/decisions/0003-schema-generator.md
//   - Architecture: https://github.com/deploymenttheory/go-apple-dm/blob/main/docs/architecture.md
//   - Apple: https://developer.apple.com/documentation/devicemanagement/commands-and-queries
//   - Apple: https://github.com/apple/device-management/blob/release/docs/schema.md
//   - Schema: third_party/device-management/mdm/commands/**
//   - Upstream: https://github.com/apple/device-management at commit 67045e2fa06f528b196c01edee6a8bf88b844beb (devicemanagement/schema/GENERATED_FROM.json)
package commands
