// Code generated by admgen; DO NOT EDIT.
// Source: apple/device-management@67045e2fa06f528b196c01edee6a8bf88b844beb

package checkin

// Authenticate: Authenticates a user during MDM payload installation.
//
// Authenticate corresponds to mdm/checkin/authenticate.yaml (Authenticate).
type Authenticate struct {
	// The device's name.
	DeviceName string `plist:"DeviceName" json:"DeviceName"`
	// The device's model name.
	ModelName string `plist:"ModelName" json:"ModelName"`
	// The device's model.
	Model string `plist:"Model" json:"Model"`
	// The message type, which requires a value of `Authenticate`.
	MessageType string `plist:"MessageType" json:"MessageType"`
	// The topic that the device subscribes to.
	Topic string `plist:"Topic" json:"Topic"`
	// The device's UDID (unique device identifier). The system requires this value if the
	// enrollment type is a device enrollment.
	UDID *string `plist:"UDID,omitempty" json:"UDID,omitempty"`
	// The per-enrollment identifier for the device. The system requires this value if the
	// enrollment type is a user enrollment.
	EnrollmentID *string `plist:"EnrollmentID,omitempty" json:"EnrollmentID,omitempty"`
	// The device's OS version.
	OSVersion *string `plist:"OSVersion,omitempty" json:"OSVersion,omitempty"`
	// The device's build version.
	BuildVersion *string `plist:"BuildVersion,omitempty" json:"BuildVersion,omitempty"`
	// The device's product name (such as `iPhone17,2`).
	ProductName *string `plist:"ProductName,omitempty" json:"ProductName,omitempty"`
	// The device's serial number.
	SerialNumber *string `plist:"SerialNumber,omitempty" json:"SerialNumber,omitempty"`
	// The device's IMEI (International Mobile Equipment Identity).
	IMEI *string `plist:"IMEI,omitempty" json:"IMEI,omitempty"`
	// The device's MEID (Mobile Equipment Identifier).
	MEID *string `plist:"MEID,omitempty" json:"MEID,omitempty"`
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*Authenticate) SchemaPath() string { return "mdm/checkin/authenticate.yaml" }

// CheckOut: Responds to the removal of the MDM enrollment profile from a device.
//
// CheckOut corresponds to mdm/checkin/checkout.yaml (Check Out).
type CheckOut struct {
	// The message type, which requires a value of `CheckOut`.
	MessageType string `plist:"MessageType" json:"MessageType"`
	// The topic the device subscribes to.
	Topic string `plist:"Topic" json:"Topic"`
	// The device's UDID (unique device identifier). The system requires this value if the
	// enrollment type is a device enrollment.
	UDID string `plist:"UDID" json:"UDID"`
	// The per-enrollment identifier for the device. The system requires this value if the
	// enrollment type is a user enrollment.
	EnrollmentID string `plist:"EnrollmentID" json:"EnrollmentID"`
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*CheckOut) SchemaPath() string { return "mdm/checkin/checkout.yaml" }

// DeclarativeManagement: Sends declarative management requests to the server.
//
// DeclarativeManagement corresponds to mdm/checkin/declarativemanagement.yaml (Declarative Management).
type DeclarativeManagement struct {
	// The message type, which requires a value of `DeclarativeManagement`.
	MessageType string `plist:"MessageType" json:"MessageType"`
	// The type of operation the declaration is requesting. This key needs to be one of these
	// values:
	Endpoint string `plist:"Endpoint" json:"Endpoint"`
	// A Base64-encoded JSON object using the `SynchronizationTokens` schema.
	Data []byte `plist:"Data,omitempty" json:"Data,omitempty"`
	// The device's UDID (unique device identifier). The system requires this value if the
	// enrollment type is a device enrollment.
	UDID string `plist:"UDID" json:"UDID"`
	// The per-enrollment identifier for the device. The system requires this value if the
	// enrollment type is a user enrollment.
	EnrollmentID string `plist:"EnrollmentID" json:"EnrollmentID"`
	// The per-enrollment identifier for the user. The system requires this value if the
	// enrollment type is a user enrollment on the user channel.
	EnrollmentUserID string `plist:"EnrollmentUserID" json:"EnrollmentUserID"`
	// For macOS, this value is the short name of the user.
	UserShortName *string `plist:"UserShortName,omitempty" json:"UserShortName,omitempty"`
	// For macOS, this value is the ID of the user.
	UserID *string `plist:"UserID,omitempty" json:"UserID,omitempty"`
	// The full name of the user.
	UserLongName string `plist:"UserLongName" json:"UserLongName"`
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*DeclarativeManagement) SchemaPath() string { return "mdm/checkin/declarativemanagement.yaml" }

// GetBootstrapToken: Gets the bootstrap token from the server.
//
// GetBootstrapToken corresponds to mdm/checkin/getbootstraptoken.yaml (Get Bootstrap Token).
type GetBootstrapToken struct {
	// The message type, which requires a value of `GetBootstrapToken`.
	MessageType string `plist:"MessageType" json:"MessageType"`
	// If `true`, the device is awaiting a `Device-Configured-Command` command before
	// proceeding through Setup Assistant.
	AwaitingConfiguration *bool `plist:"AwaitingConfiguration,omitempty" json:"AwaitingConfiguration,omitempty"`
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*GetBootstrapToken) SchemaPath() string { return "mdm/checkin/getbootstraptoken.yaml" }

// GetBootstrapTokenResponse: Response to GetBootstrapToken.
//
// GetBootstrapTokenResponse corresponds to mdm/checkin/getbootstraptoken.yaml (Get Bootstrap Token).
type GetBootstrapTokenResponse struct {
	// The current bootstrap token data for the device.
	BootstrapToken []byte `plist:"BootstrapToken,omitempty" json:"BootstrapToken,omitempty"`
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*GetBootstrapTokenResponse) SchemaPath() string { return "mdm/checkin/getbootstraptoken.yaml" }

// GetToken: Gets a token from the server.
//
// GetToken corresponds to mdm/checkin/gettoken.yaml (Get Token).
type GetToken struct {
	// The message type, which requires a value of `GetToken`.
	MessageType string `plist:"MessageType" json:"MessageType"`
	// A string that specifies the service for the requested token.
	TokenServiceType string `plist:"TokenServiceType" json:"TokenServiceType"`
	// Parameters that the system uses to generate the token.
	TokenParameters *GetTokenTokenParameters `plist:"TokenParameters,omitempty" json:"TokenParameters,omitempty"`
	// The device's UDID (unique device identifier). The system requires this value if the
	// enrollment type is a device enrollment.
	UDID string `plist:"UDID" json:"UDID"`
	// The per-enrollment identifier for the device. The system requires this value if the
	// enrollment type is a user enrollment.
	EnrollmentID string `plist:"EnrollmentID" json:"EnrollmentID"`
	// The per-enrollment identifier for the user. The system requires this value if the
	// enrollment type is a user enrollment on the user channel.
	EnrollmentUserID string `plist:"EnrollmentUserID" json:"EnrollmentUserID"`
	// For macOS, this value is the short name of the user.
	UserShortName *string `plist:"UserShortName,omitempty" json:"UserShortName,omitempty"`
	// For macOS, this value is the ID of the user.
	UserID *string `plist:"UserID,omitempty" json:"UserID,omitempty"`
	// The full name of the user.
	UserLongName string `plist:"UserLongName" json:"UserLongName"`
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*GetToken) SchemaPath() string { return "mdm/checkin/gettoken.yaml" }

// GetTokenTokenParameters: Parameters that the system uses to generate the token.
type GetTokenTokenParameters struct {
	// A security token to generate the server token. Required by the `com.apple.watch.pairing`
	// service type.
	SecurityToken *string `plist:"SecurityToken,omitempty" json:"SecurityToken,omitempty"`
	// The identifier of the phone paired to the watch. Required by the
	// `com.apple.watch.pairing` service type.
	PhoneUDID *string `plist:"PhoneUDID,omitempty" json:"PhoneUDID,omitempty"`
	// The identifier of the watch paired to the phone. Required by the
	// `com.apple.watch.pairing` service type.
	WatchUDID *string `plist:"WatchUDID,omitempty" json:"WatchUDID,omitempty"`
}

// GetTokenResponse: Response to GetToken.
//
// GetTokenResponse corresponds to mdm/checkin/gettoken.yaml (Get Token).
type GetTokenResponse struct {
	// The token data. If the token is a string value, it needs to be a UTF-8-encoded string.
	TokenData []byte `plist:"TokenData,omitempty" json:"TokenData,omitempty"`
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*GetTokenResponse) SchemaPath() string { return "mdm/checkin/gettoken.yaml" }

// ReturnToService: Gets the return-to-service configuration from the server.
//
// ReturnToService corresponds to mdm/checkin/returntoservice.yaml (Return To Service).
type ReturnToService struct {
	// The message type, which requires a value of `ReturnToService`.
	MessageType string `plist:"MessageType" json:"MessageType"`
	// The device's UDID (unique device identifier). The system requires this value if the
	// enrollment type is a device enrollment.
	UDID string `plist:"UDID" json:"UDID"`
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*ReturnToService) SchemaPath() string { return "mdm/checkin/returntoservice.yaml" }

// ReturnToServiceResponse: Response to ReturnToService.
//
// ReturnToServiceResponse corresponds to mdm/checkin/returntoservice.yaml (Return To Service).
type ReturnToServiceResponse struct {
	// If `true`, the device preserves the data plan on an iPhone or iPad with eSIM
	// functionality, if one exists. This value is available in iOS 26.4 and later.
	PreserveDataPlan *bool `plist:"PreserveDataPlan,omitempty" json:"PreserveDataPlan,omitempty"`
	// A dictionary containing the configuration for return to service.
	ReturnToService ReturnToServiceResponseReturnToService `plist:"ReturnToService,omitempty" json:"ReturnToService,omitempty"`
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*ReturnToServiceResponse) SchemaPath() string { return "mdm/checkin/returntoservice.yaml" }

// ReturnToServiceResponseReturnToService: A dictionary containing the configuration for
// return to service.
type ReturnToServiceResponseReturnToService struct {
	// If `true`, the device automatically erases itself and then performs reenrollment.
	Enabled bool `plist:"Enabled" json:"Enabled"`
	// The Wi-Fi profile that installs after erasure when using return to service. This is
	// required when the device doesn't have Ethernet access.
	WiFiProfileData []byte `plist:"WiFiProfileData,omitempty" json:"WiFiProfileData,omitempty"`
	// The MDM profile that installs after erasure when using return to service. If provided,
	// the device uses this profile directly instead of fetching it from the server. This key
	// is required if the device's Automated Device Enrollment profile contains the
	// `configuration-web-url` key.
	MDMProfileData []byte `plist:"MDMProfileData,omitempty" json:"MDMProfileData,omitempty"`
	// The system uses the bootstrap token for return to service with app preservation.
	// Required when Automated Device Enrollment enables return to service for the device.
	BootstrapToken []byte `plist:"BootstrapToken,omitempty" json:"BootstrapToken,omitempty"`
}

// SetBootstrapToken: Sends the bootstrap token to the server.
//
// SetBootstrapToken corresponds to mdm/checkin/setbootstraptoken.yaml (Set Bootstrap Token).
type SetBootstrapToken struct {
	// The message type, which requires a value of `SetBootstrapToken`.
	MessageType string `plist:"MessageType" json:"MessageType"`
	// The device's bootstrap token data. If this field is missing or zero length, the server
	// needs to remove the bootstrap token for this device.
	BootstrapToken []byte `plist:"BootstrapToken,omitempty" json:"BootstrapToken,omitempty"`
	// If `true`, the device is awaiting a `Device-Configured-Command` command before
	// proceeding through Setup Assistant.
	AwaitingConfiguration *bool `plist:"AwaitingConfiguration,omitempty" json:"AwaitingConfiguration,omitempty"`
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*SetBootstrapToken) SchemaPath() string { return "mdm/checkin/setbootstraptoken.yaml" }

// TokenUpdate: Updates the token for a device on the server.
//
// TokenUpdate corresponds to mdm/checkin/tokenupdate.yaml (Token Update).
type TokenUpdate struct {
	// If `true`, the device isn't on-console.
	NotOnConsole bool `plist:"NotOnConsole" json:"NotOnConsole"`
	// The message type, which requires a value of `TokenUpdate`.
	MessageType string `plist:"MessageType" json:"MessageType"`
	// The topic the device subscribes to.
	Topic string `plist:"Topic" json:"Topic"`
	// The device's UDID (unique device identifier). The system requires this value if the
	// enrollment type is a device enrollment.
	UDID string `plist:"UDID" json:"UDID"`
	// The per-enrollment identifier for the device. The system requires this value if the
	// enrollment type is a user enrollment.
	EnrollmentID string `plist:"EnrollmentID" json:"EnrollmentID"`
	// The per-enrollment identifier for the user. The system requires this value if the
	// enrollment type is a user enrollment on the user channel.
	EnrollmentUserID string `plist:"EnrollmentUserID" json:"EnrollmentUserID"`
	// For macOS, this value is the short name of the user.
	UserShortName *string `plist:"UserShortName,omitempty" json:"UserShortName,omitempty"`
	// For macOS, this value is the ID of the user.
	UserID *string `plist:"UserID,omitempty" json:"UserID,omitempty"`
	// The full name of the user.
	UserLongName string `plist:"UserLongName" json:"UserLongName"`
	// The push token for the device.
	Token []byte `plist:"Token,omitempty" json:"Token,omitempty"`
	// The magic string to include in the push notification message.
	PushMagic string `plist:"PushMagic" json:"PushMagic"`
	// The data to use to unlock the device. If provided, the server needs to retain this data
	// and send it when trying to implement `Clear-Passcode-Command`.
	UnlockToken []byte `plist:"UnlockToken,omitempty" json:"UnlockToken,omitempty"`
	// If `true` from the device channel, the device is awaiting a `Device-Configured-Command`
	// command before proceeding through Setup Assistant.
	AwaitingConfiguration *bool `plist:"AwaitingConfiguration,omitempty" json:"AwaitingConfiguration,omitempty"`
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*TokenUpdate) SchemaPath() string { return "mdm/checkin/tokenupdate.yaml" }

// UserAuthenticate: Authenticates a user with a two-step authentication protocol.
//
// UserAuthenticate corresponds to mdm/checkin/userauthenticate.yaml (User Authenticate).
type UserAuthenticate struct {
	// The message type, which requires a value of `UserAuthenticate`.
	MessageType string `plist:"MessageType" json:"MessageType"`
	// The device's UDID (unique device identifier). The system requires this value if the
	// enrollment type is a device enrollment.
	UDID string `plist:"UDID" json:"UDID"`
	// The local mobile user's GUID or the network user's GUID from an Open Directory record.
	UserID string `plist:"UserID" json:"UserID"`
	// A string that the client provides in the second `User-Authenticate` request after
	// receiving `DigestChallenge` from the server on the first `User-Authenticate` request.
	DigestResponse string `plist:"DigestResponse" json:"DigestResponse"`
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*UserAuthenticate) SchemaPath() string { return "mdm/checkin/userauthenticate.yaml" }
