// Code generated by admgen; DO NOT EDIT.
// Source: apple/device-management@67045e2fa06f528b196c01edee6a8bf88b844beb

package ddm_test

import (
	"testing"

	"github.com/deploymenttheory/go-apple-mdm/schema/ddm"
	"github.com/deploymenttheory/go-apple-mdm/schema/internal/conformance"
)

func sampleActivationSimple(d int) *ddm.ActivationSimple {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.ActivationSimple{
		StandardConfigurations: []string{"s"},
		Predicate:              new("s"),
	}
}

func sampleAssetCredentialACME(d int) *ddm.AssetCredentialACME {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AssetCredentialACME{
		Reference:      conformance.Deref(sampleAssetCredentialACMEReference(d + 1)),
		Authentication: sampleAssetCredentialACMEAuthentication(d + 1),
		Accessible:     new("Default"),
	}
}

func sampleAssetCredentialACMEReference(d int) *ddm.AssetCredentialACMEReference {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AssetCredentialACMEReference{
		DataURL:     "s",
		ContentType: new("s"),
		Size:        new(int64(1)),
		HashSHA256:  new("s"),
	}
}

func sampleAssetCredentialACMEAuthentication(d int) *ddm.AssetCredentialACMEAuthentication {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AssetCredentialACMEAuthentication{
		Type: "MDM",
	}
}

func sampleAssetCredentialCertificate(d int) *ddm.AssetCredentialCertificate {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AssetCredentialCertificate{
		Reference:      conformance.Deref(sampleAssetCredentialCertificateReference(d + 1)),
		Authentication: sampleAssetCredentialCertificateAuthentication(d + 1),
	}
}

func sampleAssetCredentialCertificateReference(d int) *ddm.AssetCredentialCertificateReference {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AssetCredentialCertificateReference{
		DataURL:     "s",
		ContentType: new("s"),
		Size:        new(int64(1)),
		HashSHA256:  new("s"),
	}
}

func sampleAssetCredentialCertificateAuthentication(d int) *ddm.AssetCredentialCertificateAuthentication {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AssetCredentialCertificateAuthentication{
		Type: "MDM",
	}
}

func sampleAssetCredentialIdentity(d int) *ddm.AssetCredentialIdentity {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AssetCredentialIdentity{
		Reference:      conformance.Deref(sampleAssetCredentialIdentityReference(d + 1)),
		Authentication: sampleAssetCredentialIdentityAuthentication(d + 1),
		Accessible:     new("Default"),
	}
}

func sampleAssetCredentialIdentityReference(d int) *ddm.AssetCredentialIdentityReference {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AssetCredentialIdentityReference{
		DataURL:     "s",
		ContentType: new("s"),
		Size:        new(int64(1)),
		HashSHA256:  new("s"),
	}
}

func sampleAssetCredentialIdentityAuthentication(d int) *ddm.AssetCredentialIdentityAuthentication {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AssetCredentialIdentityAuthentication{
		Type: "MDM",
	}
}

func sampleAssetCredentialSCEP(d int) *ddm.AssetCredentialSCEP {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AssetCredentialSCEP{
		Reference:      conformance.Deref(sampleAssetCredentialSCEPReference(d + 1)),
		Authentication: sampleAssetCredentialSCEPAuthentication(d + 1),
		Accessible:     new("Default"),
	}
}

func sampleAssetCredentialSCEPReference(d int) *ddm.AssetCredentialSCEPReference {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AssetCredentialSCEPReference{
		DataURL:     "s",
		ContentType: new("s"),
		Size:        new(int64(1)),
		HashSHA256:  new("s"),
	}
}

func sampleAssetCredentialSCEPAuthentication(d int) *ddm.AssetCredentialSCEPAuthentication {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AssetCredentialSCEPAuthentication{
		Type: "MDM",
	}
}

func sampleAssetCredentialUserNameAndPassword(d int) *ddm.AssetCredentialUserNameAndPassword {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AssetCredentialUserNameAndPassword{
		Reference:      conformance.Deref(sampleAssetCredentialUserNameAndPasswordReference(d + 1)),
		Authentication: sampleAssetCredentialUserNameAndPasswordAuthentication(d + 1),
	}
}

func sampleAssetCredentialUserNameAndPasswordReference(d int) *ddm.AssetCredentialUserNameAndPasswordReference {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AssetCredentialUserNameAndPasswordReference{
		DataURL:     "s",
		ContentType: new("s"),
		Size:        new(int64(1)),
		HashSHA256:  new("s"),
	}
}

func sampleAssetCredentialUserNameAndPasswordAuthentication(d int) *ddm.AssetCredentialUserNameAndPasswordAuthentication {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AssetCredentialUserNameAndPasswordAuthentication{
		Type: "MDM",
	}
}

func sampleACMECredential(d int) *ddm.ACMECredential {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.ACMECredential{
		DirectoryURL:     "s",
		ClientIdentifier: "s",
		KeySize:          int64(1),
		KeyType:          "RSA",
		HardwareBound:    true,
		Subject:          [][][]string{[][]string{[]string{"s"}}},
		SubjectAltName:   sampleACMECredentialSubjectAltName(d + 1),
		UsageFlags:       new(int64(1)),
		ExtendedKeyUsage: []string{"s"},
		Attest:           new(true),
	}
}

func sampleACMECredentialSubjectAltName(d int) *ddm.ACMECredentialSubjectAltName {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.ACMECredentialSubjectAltName{
		Rfc822Name:                new("s"),
		DNSName:                   new("s"),
		UniformResourceIdentifier: new("s"),
		NtPrincipalName:           new("s"),
	}
}

func sampleIdentityCredential(d int) *ddm.IdentityCredential {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.IdentityCredential{
		Password: "s",
		Identity: []byte{1, 2, 3},
	}
}

func sampleSCEPCredential(d int) *ddm.SCEPCredential {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.SCEPCredential{
		URL:            "s",
		Name:           new("s"),
		Subject:        [][][]string{[][]string{[]string{"s"}}},
		Challenge:      new("s"),
		Keysize:        new(int64(1024)),
		KeyType:        new("s"),
		KeyUsage:       new(int64(1)),
		CAFingerprint:  []byte{1, 2, 3},
		Retries:        new(int64(1)),
		RetryDelay:     new(int64(1)),
		SubjectAltName: sampleSCEPCredentialSubjectAltName(d + 1),
	}
}

func sampleSCEPCredentialSubjectAltName(d int) *ddm.SCEPCredentialSubjectAltName {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.SCEPCredentialSubjectAltName{
		Rfc822Name:                new("s"),
		DNSName:                   new("s"),
		UniformResourceIdentifier: new("s"),
		NtPrincipalName:           new("s"),
	}
}

func sampleUserNameAndPasswordCredential(d int) *ddm.UserNameAndPasswordCredential {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.UserNameAndPasswordCredential{
		UserName: "s",
		Password: new("s"),
	}
}

func sampleAssetData(d int) *ddm.AssetData {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AssetData{
		Reference:      conformance.Deref(sampleAssetDataReference(d + 1)),
		Authentication: sampleAssetDataAuthentication(d + 1),
	}
}

func sampleAssetDataReference(d int) *ddm.AssetDataReference {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AssetDataReference{
		DataURL:     "s",
		ContentType: new("s"),
		Size:        new(int64(1)),
		HashSHA256:  new("s"),
	}
}

func sampleAssetDataAuthentication(d int) *ddm.AssetDataAuthentication {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AssetDataAuthentication{
		Type: "MDM",
	}
}

func sampleAssetUserIdentity(d int) *ddm.AssetUserIdentity {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AssetUserIdentity{
		FullName:     new("s"),
		EmailAddress: new("s"),
	}
}

func sampleAccountCalDAV(d int) *ddm.AccountCalDAV {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AccountCalDAV{
		VisibleName:                             new("s"),
		HostName:                                "s",
		Port:                                    new(int64(1)),
		Path:                                    new("s"),
		AuthenticationCredentialsAssetReference: new("s"),
	}
}

func sampleAccountCardDAV(d int) *ddm.AccountCardDAV {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AccountCardDAV{
		VisibleName:                             new("s"),
		HostName:                                "s",
		Port:                                    new(int64(1)),
		Path:                                    new("s"),
		AuthenticationCredentialsAssetReference: new("s"),
	}
}

func sampleAccountExchange(d int) *ddm.AccountExchange {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AccountExchange{
		VisibleName:                             new("s"),
		EnabledProtocolTypes:                    []string{"EAS"},
		UserIdentityAssetReference:              new("s"),
		HostName:                                new("s"),
		Port:                                    new(int64(1)),
		Path:                                    new("s"),
		ExternalHostName:                        new("s"),
		ExternalPort:                            new(int64(1)),
		ExternalPath:                            new("s"),
		OAuth:                                   sampleAccountExchangeOAuth(d + 1),
		AuthenticationCredentialsAssetReference: new("s"),
		AuthenticationIdentityAssetReference:    new("s"),
		SMIME:                                   sampleAccountExchangeSMIME(d + 1),
		MailServiceActive:                       new(true),
		LockMailService:                         new(true),
		ContactsServiceActive:                   new(true),
		LockContactsService:                     new(true),
		CalendarServiceActive:                   new(true),
		LockCalendarService:                     new(true),
		RemindersServiceActive:                  new(true),
		LockRemindersService:                    new(true),
		NotesServiceActive:                      new(true),
		LockNotesService:                        new(true),
	}
}

func sampleAccountExchangeOAuth(d int) *ddm.AccountExchangeOAuth {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AccountExchangeOAuth{
		Enabled:         true,
		SignInURL:       new("s"),
		TokenRequestURL: new("s"),
	}
}

func sampleAccountExchangeSMIME(d int) *ddm.AccountExchangeSMIME {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AccountExchangeSMIME{
		Signing:    sampleAccountExchangeSMIMESigning(d + 1),
		Encryption: sampleAccountExchangeSMIMEEncryption(d + 1),
	}
}

func sampleAccountExchangeSMIMESigning(d int) *ddm.AccountExchangeSMIMESigning {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AccountExchangeSMIMESigning{
		Enabled:                  true,
		IdentityAssetReference:   new("s"),
		UserOverrideable:         new(true),
		IdentityUserOverrideable: new(true),
	}
}

func sampleAccountExchangeSMIMEEncryption(d int) *ddm.AccountExchangeSMIMEEncryption {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AccountExchangeSMIMEEncryption{
		Enabled:                  true,
		IdentityAssetReference:   new("s"),
		UserOverrideable:         new(true),
		IdentityUserOverrideable: new(true),
		PerMessageSwitchEnabled:  new(true),
	}
}

func sampleAccountGoogle(d int) *ddm.AccountGoogle {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AccountGoogle{
		VisibleName:                new("s"),
		UserIdentityAssetReference: "s",
	}
}

func sampleAccountLDAP(d int) *ddm.AccountLDAP {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AccountLDAP{
		VisibleName:                             new("s"),
		HostName:                                "s",
		Port:                                    new(int64(1)),
		AuthenticationCredentialsAssetReference: new("s"),
		SearchSettings:                          conformance.SliceOf(sampleAccountLDAPSearchSettings(d + 1)),
	}
}

func sampleAccountLDAPSearchSettings(d int) *ddm.AccountLDAPSearchSettings {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AccountLDAPSearchSettings{
		VisibleDescription: new("s"),
		SearchBase:         "s",
		Scope:              new("Base"),
	}
}

func sampleAccountMail(d int) *ddm.AccountMail {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AccountMail{
		VisibleName:                new("s"),
		UserIdentityAssetReference: new("s"),
		IncomingServer:             conformance.Deref(sampleAccountMailIncomingServer(d + 1)),
		OutgoingServer:             conformance.Deref(sampleAccountMailOutgoingServer(d + 1)),
		SMIME:                      sampleAccountMailSMIME(d + 1),
	}
}

func sampleAccountMailIncomingServer(d int) *ddm.AccountMailIncomingServer {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AccountMailIncomingServer{
		ServerType:                              "IMAP",
		HostName:                                "s",
		Port:                                    new(int64(1)),
		AuthenticationMethod:                    "None",
		AuthenticationCredentialsAssetReference: new("s"),
		IMAPPathPrefix:                          new("s"),
	}
}

func sampleAccountMailOutgoingServer(d int) *ddm.AccountMailOutgoingServer {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AccountMailOutgoingServer{
		HostName:                                "s",
		Port:                                    new(int64(1)),
		AuthenticationMethod:                    "None",
		AuthenticationCredentialsAssetReference: new("s"),
	}
}

func sampleAccountMailSMIME(d int) *ddm.AccountMailSMIME {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AccountMailSMIME{
		Signing:    sampleAccountMailSMIMESigning(d + 1),
		Encryption: sampleAccountMailSMIMEEncryption(d + 1),
	}
}

func sampleAccountMailSMIMESigning(d int) *ddm.AccountMailSMIMESigning {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AccountMailSMIMESigning{
		Enabled:                  true,
		IdentityAssetReference:   new("s"),
		UserOverrideable:         new(true),
		IdentityUserOverrideable: new(true),
	}
}

func sampleAccountMailSMIMEEncryption(d int) *ddm.AccountMailSMIMEEncryption {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AccountMailSMIMEEncryption{
		Enabled:                  true,
		IdentityAssetReference:   new("s"),
		UserOverrideable:         new(true),
		IdentityUserOverrideable: new(true),
		PerMessageSwitchEnabled:  new(true),
	}
}

func sampleAccountSubscribedCalendar(d int) *ddm.AccountSubscribedCalendar {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AccountSubscribedCalendar{
		VisibleName:                             new("s"),
		CalendarURL:                             "s",
		AuthenticationCredentialsAssetReference: new("s"),
	}
}

func sampleAppManaged(d int) *ddm.AppManaged {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AppManaged{
		AppStoreID:                    new("s"),
		BundleID:                      new("s"),
		ManifestURL:                   new("s"),
		AppComposedIdentifier:         new("s"),
		IOSApp:                        new(true),
		InstallBehavior:               sampleAppManagedInstallBehavior(d + 1),
		UpdateBehavior:                sampleAppManagedUpdateBehavior(d + 1),
		IncludeInBackup:               new(true),
		Attributes:                    sampleAppManagedAttributes(d + 1),
		AppConfig:                     sampleAppManagedAppConfigDictionary(d + 1),
		ExtensionConfigs:              map[string]ddm.AppManagedAppConfigDictionary{"k": conformance.Deref(sampleAppManagedAppConfigDictionary(d + 1))},
		LegacyAppConfigAssetReference: new("s"),
	}
}

func sampleAppManagedInstallBehavior(d int) *ddm.AppManagedInstallBehavior {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AppManagedInstallBehavior{
		Install:                    new("Optional"),
		License:                    sampleAppManagedInstallBehaviorLicense(d + 1),
		Version:                    new(int64(1)),
		AllowDownloadsOverCellular: new("AlwaysOn"),
	}
}

func sampleAppManagedInstallBehaviorLicense(d int) *ddm.AppManagedInstallBehaviorLicense {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AppManagedInstallBehaviorLicense{
		Assignment: new("Device"),
		VPPType:    new("Device"),
	}
}

func sampleAppManagedUpdateBehavior(d int) *ddm.AppManagedUpdateBehavior {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AppManagedUpdateBehavior{
		AutomaticAppUpdates: "AlwaysOn",
	}
}

func sampleAppManagedAttributes(d int) *ddm.AppManagedAttributes {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AppManagedAttributes{
		AssociatedDomains:                      []string{"s"},
		AssociatedDomainsEnableDirectDownloads: new(true),
		CellularSliceUUID:                      new("s"),
		ContentFilterUUID:                      new("s"),
		DNSProxyUUID:                           new("s"),
		Hideable:                               new(true),
		Lockable:                               new(true),
		RelayUUID:                              new("s"),
		TapToPayScreenLock:                     new(true),
		VPNUUID:                                new("s"),
	}
}

func sampleAppManagedAppConfigDictionary(d int) *ddm.AppManagedAppConfigDictionary {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AppManagedAppConfigDictionary{
		DataAssetReference: new("s"),
		Passwords:          conformance.SliceOf(sampleAppManagedCredentialConfig(d + 1)),
		Identities:         conformance.SliceOf(sampleAppManagedCredentialConfig(d + 1)),
		Certificates:       conformance.SliceOf(sampleAppManagedCredentialConfig(d + 1)),
	}
}

func sampleAppManagedCredentialConfig(d int) *ddm.AppManagedCredentialConfig {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AppManagedCredentialConfig{
		Identifier:     "s",
		AssetReference: "s",
	}
}

func sampleAudioAccessorySettings(d int) *ddm.AudioAccessorySettings {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AudioAccessorySettings{
		TemporaryPairing: sampleAudioAccessorySettingsTemporaryPairing(d + 1),
	}
}

func sampleAudioAccessorySettingsTemporaryPairing(d int) *ddm.AudioAccessorySettingsTemporaryPairing {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AudioAccessorySettingsTemporaryPairing{
		Disabled:      new(true),
		Configuration: sampleAudioAccessorySettingsTemporaryPairingConfiguration(d + 1),
	}
}

func sampleAudioAccessorySettingsTemporaryPairingConfiguration(d int) *ddm.AudioAccessorySettingsTemporaryPairingConfiguration {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AudioAccessorySettingsTemporaryPairingConfiguration{
		UnpairingTime: conformance.Deref(sampleAudioAccessorySettingsTemporaryPairingConfigurationUnpairingTime(d + 1)),
	}
}

func sampleAudioAccessorySettingsTemporaryPairingConfigurationUnpairingTime(d int) *ddm.AudioAccessorySettingsTemporaryPairingConfigurationUnpairingTime {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.AudioAccessorySettingsTemporaryPairingConfigurationUnpairingTime{
		Policy: "None",
		Hour:   new(int64(0)),
	}
}

func sampleDiskManagementSettings(d int) *ddm.DiskManagementSettings {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.DiskManagementSettings{
		Restrictions: sampleDiskManagementSettingsRestrictions(d + 1),
	}
}

func sampleDiskManagementSettingsRestrictions(d int) *ddm.DiskManagementSettingsRestrictions {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.DiskManagementSettingsRestrictions{
		ExternalStorage: new("Allowed"),
		NetworkStorage:  new("Allowed"),
	}
}

func sampleExternalIntelligenceSettings(d int) *ddm.ExternalIntelligenceSettings {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.ExternalIntelligenceSettings{
		Enabled:             new(true),
		AllowSignIn:         new(true),
		AllowedWorkspaceIDs: []string{"s"},
	}
}

func sampleIntelligenceSettings(d int) *ddm.IntelligenceSettings {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.IntelligenceSettings{
		AllowAppleIntelligenceReport:        new(true),
		AllowGenmoji:                        new(true),
		AllowImagePlayground:                new(true),
		AllowImageWand:                      new(true),
		AllowPersonalizedHandwritingResults: new(true),
		AllowVisualIntelligenceSummary:      new(true),
		AllowWritingTools:                   new(true),
		Apps:                                sampleIntelligenceSettingsApps(d + 1),
		ForceOnDeviceOnlyDictation:          new(true),
		ForceOnDeviceOnlyTranslation:        new(true),
	}
}

func sampleIntelligenceSettingsApps(d int) *ddm.IntelligenceSettingsApps {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.IntelligenceSettingsApps{
		Mail:   sampleIntelligenceSettingsAppsMail(d + 1),
		Notes:  sampleIntelligenceSettingsAppsNotes(d + 1),
		Safari: sampleIntelligenceSettingsAppsSafari(d + 1),
	}
}

func sampleIntelligenceSettingsAppsMail(d int) *ddm.IntelligenceSettingsAppsMail {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.IntelligenceSettingsAppsMail{
		AllowSmartReplies: new(true),
		AllowSummary:      new(true),
	}
}

func sampleIntelligenceSettingsAppsNotes(d int) *ddm.IntelligenceSettingsAppsNotes {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.IntelligenceSettingsAppsNotes{
		AllowTranscription:        new(true),
		AllowTranscriptionSummary: new(true),
	}
}

func sampleIntelligenceSettingsAppsSafari(d int) *ddm.IntelligenceSettingsAppsSafari {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.IntelligenceSettingsAppsSafari{
		AllowSummary: new(true),
	}
}

func sampleKeyboardSettings(d int) *ddm.KeyboardSettings {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.KeyboardSettings{
		AllowAutoCorrection:          new(true),
		AllowDefinitionLookup:        new(true),
		AllowDictation:               new(true),
		AllowMathKeyboardSuggestions: new(true),
		AllowPredictiveText:          new(true),
		AllowSlideToType:             new(true),
		AllowSpellCheck:              new(true),
		AllowTextReplacement:         new(true),
	}
}

func sampleLegacyInteractiveProfile(d int) *ddm.LegacyInteractiveProfile {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.LegacyInteractiveProfile{
		ProfileURL:  "s",
		VisibleName: "s",
	}
}

func sampleLegacyProfile(d int) *ddm.LegacyProfile {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.LegacyProfile{
		ProfileURL: "s",
	}
}

func sampleManagementStatusSubscriptions(d int) *ddm.ManagementStatusSubscriptions {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.ManagementStatusSubscriptions{
		StatusItems: conformance.SliceOf(sampleManagementStatusSubscriptionsStatusItems(d + 1)),
	}
}

func sampleManagementStatusSubscriptionsStatusItems(d int) *ddm.ManagementStatusSubscriptionsStatusItems {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.ManagementStatusSubscriptionsStatusItems{
		Name: "s",
	}
}

func sampleManagementTest(d int) *ddm.ManagementTest {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.ManagementTest{
		Echo:                   "s",
		EchoDataAssetReference: new("s"),
		ReturnStatus:           new("Installed"),
	}
}

func sampleMathSettings(d int) *ddm.MathSettings {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.MathSettings{
		Calculator:     sampleMathSettingsCalculator(d + 1),
		SystemBehavior: sampleMathSettingsSystemBehavior(d + 1),
	}
}

func sampleMathSettingsCalculator(d int) *ddm.MathSettingsCalculator {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.MathSettingsCalculator{
		BasicMode:      sampleMathSettingsCalculatorBasicMode(d + 1),
		ScientificMode: sampleMathSettingsCalculatorScientificMode(d + 1),
		ProgrammerMode: sampleMathSettingsCalculatorProgrammerMode(d + 1),
		MathNotesMode:  sampleMathSettingsCalculatorMathNotesMode(d + 1),
		InputModes:     sampleMathSettingsCalculatorInputModes(d + 1),
	}
}

func sampleMathSettingsCalculatorBasicMode(d int) *ddm.MathSettingsCalculatorBasicMode {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.MathSettingsCalculatorBasicMode{
		AddSquareRoot: true,
	}
}

func sampleMathSettingsCalculatorScientificMode(d int) *ddm.MathSettingsCalculatorScientificMode {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.MathSettingsCalculatorScientificMode{
		Enabled: true,
	}
}

func sampleMathSettingsCalculatorProgrammerMode(d int) *ddm.MathSettingsCalculatorProgrammerMode {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.MathSettingsCalculatorProgrammerMode{
		Enabled: true,
	}
}

func sampleMathSettingsCalculatorMathNotesMode(d int) *ddm.MathSettingsCalculatorMathNotesMode {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.MathSettingsCalculatorMathNotesMode{
		Enabled: true,
	}
}

func sampleMathSettingsCalculatorInputModes(d int) *ddm.MathSettingsCalculatorInputModes {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.MathSettingsCalculatorInputModes{
		UnitConversion: true,
		RPN:            true,
	}
}

func sampleMathSettingsSystemBehavior(d int) *ddm.MathSettingsSystemBehavior {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.MathSettingsSystemBehavior{
		KeyboardSuggestions: true,
		MathNotes:           true,
	}
}

func sampleMigrationAssistantSettings(d int) *ddm.MigrationAssistantSettings {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.MigrationAssistantSettings{
		ShouldDoManagedMigration:             true,
		ExcludedAccounts:                     []string{"s"},
		ExcludedPaths:                        []string{"s"},
		RequiredPaths:                        []string{"s"},
		ShouldMigrateSecurityPrivacySettings: true,
	}
}

func samplePackage(d int) *ddm.Package {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.Package{
		ManifestURL:     "s",
		InstallBehavior: samplePackageInstallBehavior(d + 1),
	}
}

func samplePackageInstallBehavior(d int) *ddm.PackageInstallBehavior {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.PackageInstallBehavior{
		Install: new("Optional"),
	}
}

func samplePasscodeSettings(d int) *ddm.PasscodeSettings {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.PasscodeSettings{
		RequirePasscode:              new(true),
		RequireAlphanumericPasscode:  new(true),
		RequireComplexPasscode:       new(true),
		MinimumLength:                new(int64(0)),
		MinimumComplexCharacters:     new(int64(0)),
		MaximumFailedAttempts:        new(int64(2)),
		FailedAttemptsResetInMinutes: new(int64(1)),
		MaximumGracePeriodInMinutes:  new(int64(1)),
		MaximumInactivityInMinutes:   new(int64(0)),
		MaximumPasscodeAgeInDays:     new(int64(0)),
		PasscodeReuseLimit:           new(int64(1)),
		ChangeAtNextAuth:             new(true),
		CustomRegex:                  samplePasscodeSettingsCustomRegex(d + 1),
	}
}

func samplePasscodeSettingsCustomRegex(d int) *ddm.PasscodeSettingsCustomRegex {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.PasscodeSettingsCustomRegex{
		Regex:       "s",
		Description: map[string]string{"k": "s"},
	}
}

func sampleSafariBookmarks(d int) *ddm.SafariBookmarks {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.SafariBookmarks{
		ManagedBookmarks: conformance.SliceOf(sampleSafariBookmarksManagedBookmarks(d + 1)),
	}
}

func sampleSafariBookmarksManagedBookmarks(d int) *ddm.SafariBookmarksManagedBookmarks {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.SafariBookmarksManagedBookmarks{
		GroupIdentifier: "s",
		Title:           "s",
		Bookmarks:       conformance.SliceOf(sampleSafariBookmarksBookmarksItem(d + 1)),
	}
}

func sampleSafariBookmarksBookmarksItem(d int) *ddm.SafariBookmarksBookmarksItem {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.SafariBookmarksBookmarksItem{
		Title:  "s",
		URL:    new("s"),
		Folder: conformance.SliceOf(sampleSafariBookmarksBookmarksItem(d + 1)),
	}
}

func sampleSafariExtensionSettings(d int) *ddm.SafariExtensionSettings {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.SafariExtensionSettings{
		ManagedExtensions: map[string]ddm.SafariExtensionSettingsExtensionDictionary{"k": conformance.Deref(sampleSafariExtensionSettingsExtensionDictionary(d + 1))},
	}
}

func sampleSafariExtensionSettingsExtensionDictionary(d int) *ddm.SafariExtensionSettingsExtensionDictionary {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.SafariExtensionSettingsExtensionDictionary{
		State:           new("Allowed"),
		PrivateBrowsing: new("Allowed"),
		AllowedDomains:  []string{"s"},
		DeniedDomains:   []string{"s"},
	}
}

func sampleSafariSettings(d int) *ddm.SafariSettings {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.SafariSettings{
		AcceptCookies:              new("Never"),
		AllowDisablingFraudWarning: new(true),
		AllowHistoryClearing:       new(true),
		AllowJavaScript:            new(true),
		AllowPrivateBrowsing:       new(true),
		AllowPopups:                new(true),
		AllowSummary:               new(true),
		NewTabStartPage:            sampleSafariSettingsNewTabStartPage(d + 1),
	}
}

func sampleSafariSettingsNewTabStartPage(d int) *ddm.SafariSettingsNewTabStartPage {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.SafariSettingsNewTabStartPage{
		PageType:            "Start",
		HomepageURL:         new("s"),
		ExtensionIdentifier: new("s"),
	}
}

func sampleScreenSharingConnectionGroup(d int) *ddm.ScreenSharingConnectionGroup {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.ScreenSharingConnectionGroup{
		ConnectionGroupUUID: "s",
		GroupName:           "s",
		Members:             []string{"s"},
	}
}

func sampleScreenSharingConnection(d int) *ddm.ScreenSharingConnection {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.ScreenSharingConnection{
		ConnectionUUID:                          "s",
		DisplayName:                             "s",
		HostName:                                "s",
		Port:                                    new(int64(1)),
		DisplayConfiguration:                    conformance.Deref(sampleScreenSharingConnectionDisplayConfiguration(d + 1)),
		AuthenticationCredentialsAssetReference: new("s"),
	}
}

func sampleScreenSharingConnectionDisplayConfiguration(d int) *ddm.ScreenSharingConnectionDisplayConfiguration {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.ScreenSharingConnectionDisplayConfiguration{
		DisplayType: "Virtual1",
	}
}

func sampleScreenSharingHostSettings(d int) *ddm.ScreenSharingHostSettings {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.ScreenSharingHostSettings{
		MaximumVirtualDisplays:            new(int64(0)),
		PortBase:                          new(int64(1024)),
		PreventCopyFilesFromHost:          new(true),
		PreventCopyFilesToHost:            new(true),
		PreventHighPerformanceConnections: new(true),
	}
}

func sampleSecurityCertificate(d int) *ddm.SecurityCertificate {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.SecurityCertificate{
		CredentialAssetReference: "s",
	}
}

func sampleSecurityIdentity(d int) *ddm.SecurityIdentity {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.SecurityIdentity{
		CredentialAssetReference: "s",
		AllowAllAppsAccess:       new(true),
		KeyIsExtractable:         new(true),
	}
}

func sampleSecurityPasskeyAttestation(d int) *ddm.SecurityPasskeyAttestation {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.SecurityPasskeyAttestation{
		AttestationIdentityAssetReference:   "s",
		AttestationIdentityKeyIsExtractable: new(true),
		RelyingParties:                      []string{"s"},
	}
}

func sampleServicesBackgroundTasks(d int) *ddm.ServicesBackgroundTasks {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.ServicesBackgroundTasks{
		TaskType:                 "s",
		TaskDescription:          new("s"),
		ExecutableAssetReference: new("s"),
		LaunchdConfigurations:    conformance.SliceOf(sampleServicesBackgroundTasksLaunchdConfigurations(d + 1)),
	}
}

func sampleServicesBackgroundTasksLaunchdConfigurations(d int) *ddm.ServicesBackgroundTasksLaunchdConfigurations {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.ServicesBackgroundTasksLaunchdConfigurations{
		FileAssetReference: "s",
		Context:            "daemon",
	}
}

func sampleServicesConfigurationFiles(d int) *ddm.ServicesConfigurationFiles {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.ServicesConfigurationFiles{
		ServiceType:        "s",
		DataAssetReference: "s",
	}
}

func sampleSiriSettings(d int) *ddm.SiriSettings {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.SiriSettings{
		Enabled:                   new(true),
		AllowUserGeneratedContent: new(true),
		AllowWhileLocked:          new(true),
		ForceProfanityFilter:      new(true),
	}
}

func sampleSoftwareUpdateEnforcementSpecific(d int) *ddm.SoftwareUpdateEnforcementSpecific {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.SoftwareUpdateEnforcementSpecific{
		TargetOSVersion:     "s",
		TargetBuildVersion:  new("s"),
		TargetLocalDateTime: "s",
		DetailsURL:          new("s"),
	}
}

func sampleSoftwareUpdateSettings(d int) *ddm.SoftwareUpdateSettings {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.SoftwareUpdateSettings{
		Notifications:              new(true),
		Deferrals:                  sampleSoftwareUpdateSettingsDeferrals(d + 1),
		RecommendedCadence:         new("All"),
		AutomaticActions:           sampleSoftwareUpdateSettingsAutomaticActions(d + 1),
		RapidSecurityResponse:      sampleSoftwareUpdateSettingsRapidSecurityResponse(d + 1),
		AllowStandardUserOSUpdates: new(true),
		Beta:                       sampleSoftwareUpdateSettingsBeta(d + 1),
	}
}

func sampleSoftwareUpdateSettingsDeferrals(d int) *ddm.SoftwareUpdateSettingsDeferrals {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.SoftwareUpdateSettingsDeferrals{
		CombinedPeriodInDays: new(int64(1)),
		MajorPeriodInDays:    new(int64(1)),
		MinorPeriodInDays:    new(int64(1)),
		SystemPeriodInDays:   new(int64(1)),
	}
}

func sampleSoftwareUpdateSettingsAutomaticActions(d int) *ddm.SoftwareUpdateSettingsAutomaticActions {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.SoftwareUpdateSettingsAutomaticActions{
		Download:              new("Allowed"),
		InstallOSUpdates:      new("Allowed"),
		InstallSecurityUpdate: new("Allowed"),
	}
}

func sampleSoftwareUpdateSettingsRapidSecurityResponse(d int) *ddm.SoftwareUpdateSettingsRapidSecurityResponse {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.SoftwareUpdateSettingsRapidSecurityResponse{
		Enable:         new(true),
		EnableRollback: new(true),
	}
}

func sampleSoftwareUpdateSettingsBeta(d int) *ddm.SoftwareUpdateSettingsBeta {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.SoftwareUpdateSettingsBeta{
		ProgramEnrollment: new("Allowed"),
		OfferPrograms:     conformance.SliceOf(sampleSoftwareUpdateSettingsBetaOfferPrograms(d + 1)),
		RequireProgram:    sampleSoftwareUpdateSettingsBetaRequireProgram(d + 1),
	}
}

func sampleSoftwareUpdateSettingsBetaOfferPrograms(d int) *ddm.SoftwareUpdateSettingsBetaOfferPrograms {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.SoftwareUpdateSettingsBetaOfferPrograms{
		Description: "s",
		Token:       "s",
	}
}

func sampleSoftwareUpdateSettingsBetaRequireProgram(d int) *ddm.SoftwareUpdateSettingsBetaRequireProgram {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.SoftwareUpdateSettingsBetaRequireProgram{
		Description: "s",
		Token:       "s",
	}
}

func sampleWatchEnrollment(d int) *ddm.WatchEnrollment {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.WatchEnrollment{
		EnrollmentProfileURL:             "s",
		AnchorCertificateAssetReferences: []string{"s"},
	}
}

func sampleDeclarationBase(d int) *ddm.DeclarationBase {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.DeclarationBase{
		Type:        "s",
		Identifier:  "s",
		ServerToken: "s",
		Payload:     map[string]any{"k": "v"},
	}
}

func sampleManagementOrganizationInformation(d int) *ddm.ManagementOrganizationInformation {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.ManagementOrganizationInformation{
		Name:  "s",
		Email: new("s"),
		URL:   new("s"),
		Proof: sampleManagementOrganizationInformationProof(d + 1),
	}
}

func sampleManagementOrganizationInformationProof(d int) *ddm.ManagementOrganizationInformationProof {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.ManagementOrganizationInformationProof{
		IdentityToken: new("s"),
	}
}

func sampleManagementProperties(d int) *ddm.ManagementProperties {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.ManagementProperties{
		ANY: any("x"),
	}
}

func sampleManagementServerCapabilities(d int) *ddm.ManagementServerCapabilities {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddm.ManagementServerCapabilities{
		Version:           "s",
		SupportedFeatures: map[string]any{"k": any("x")},
	}
}

func TestConformanceRoundTrip(t *testing.T) {
	t.Parallel()
	t.Run("ActivationSimple", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleActivationSimple(0), func() any { return new(ddm.ActivationSimple) }, true)
	})
	t.Run("AssetCredentialACME", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAssetCredentialACME(0), func() any { return new(ddm.AssetCredentialACME) }, true)
	})
	t.Run("AssetCredentialCertificate", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAssetCredentialCertificate(0), func() any { return new(ddm.AssetCredentialCertificate) }, true)
	})
	t.Run("AssetCredentialIdentity", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAssetCredentialIdentity(0), func() any { return new(ddm.AssetCredentialIdentity) }, true)
	})
	t.Run("AssetCredentialSCEP", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAssetCredentialSCEP(0), func() any { return new(ddm.AssetCredentialSCEP) }, true)
	})
	t.Run("AssetCredentialUserNameAndPassword", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAssetCredentialUserNameAndPassword(0), func() any { return new(ddm.AssetCredentialUserNameAndPassword) }, true)
	})
	t.Run("ACMECredential", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleACMECredential(0), func() any { return new(ddm.ACMECredential) }, true)
	})
	t.Run("IdentityCredential", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleIdentityCredential(0), func() any { return new(ddm.IdentityCredential) }, true)
	})
	t.Run("SCEPCredential", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleSCEPCredential(0), func() any { return new(ddm.SCEPCredential) }, true)
	})
	t.Run("UserNameAndPasswordCredential", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleUserNameAndPasswordCredential(0), func() any { return new(ddm.UserNameAndPasswordCredential) }, true)
	})
	t.Run("AssetData", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAssetData(0), func() any { return new(ddm.AssetData) }, true)
	})
	t.Run("AssetUserIdentity", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAssetUserIdentity(0), func() any { return new(ddm.AssetUserIdentity) }, true)
	})
	t.Run("AccountCalDAV", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAccountCalDAV(0), func() any { return new(ddm.AccountCalDAV) }, true)
	})
	t.Run("AccountCardDAV", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAccountCardDAV(0), func() any { return new(ddm.AccountCardDAV) }, true)
	})
	t.Run("AccountExchange", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAccountExchange(0), func() any { return new(ddm.AccountExchange) }, true)
	})
	t.Run("AccountGoogle", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAccountGoogle(0), func() any { return new(ddm.AccountGoogle) }, true)
	})
	t.Run("AccountLDAP", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAccountLDAP(0), func() any { return new(ddm.AccountLDAP) }, true)
	})
	t.Run("AccountMail", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAccountMail(0), func() any { return new(ddm.AccountMail) }, true)
	})
	t.Run("AccountSubscribedCalendar", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAccountSubscribedCalendar(0), func() any { return new(ddm.AccountSubscribedCalendar) }, true)
	})
	t.Run("AppManaged", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAppManaged(0), func() any { return new(ddm.AppManaged) }, true)
	})
	t.Run("AudioAccessorySettings", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleAudioAccessorySettings(0), func() any { return new(ddm.AudioAccessorySettings) }, true)
	})
	t.Run("DiskManagementSettings", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleDiskManagementSettings(0), func() any { return new(ddm.DiskManagementSettings) }, true)
	})
	t.Run("ExternalIntelligenceSettings", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleExternalIntelligenceSettings(0), func() any { return new(ddm.ExternalIntelligenceSettings) }, true)
	})
	t.Run("IntelligenceSettings", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleIntelligenceSettings(0), func() any { return new(ddm.IntelligenceSettings) }, true)
	})
	t.Run("KeyboardSettings", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleKeyboardSettings(0), func() any { return new(ddm.KeyboardSettings) }, true)
	})
	t.Run("LegacyInteractiveProfile", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleLegacyInteractiveProfile(0), func() any { return new(ddm.LegacyInteractiveProfile) }, true)
	})
	t.Run("LegacyProfile", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleLegacyProfile(0), func() any { return new(ddm.LegacyProfile) }, true)
	})
	t.Run("ManagementStatusSubscriptions", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleManagementStatusSubscriptions(0), func() any { return new(ddm.ManagementStatusSubscriptions) }, true)
	})
	t.Run("ManagementTest", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleManagementTest(0), func() any { return new(ddm.ManagementTest) }, true)
	})
	t.Run("MathSettings", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleMathSettings(0), func() any { return new(ddm.MathSettings) }, true)
	})
	t.Run("MigrationAssistantSettings", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleMigrationAssistantSettings(0), func() any { return new(ddm.MigrationAssistantSettings) }, true)
	})
	t.Run("Package", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, samplePackage(0), func() any { return new(ddm.Package) }, true)
	})
	t.Run("PasscodeSettings", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, samplePasscodeSettings(0), func() any { return new(ddm.PasscodeSettings) }, true)
	})
	t.Run("SafariBookmarks", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleSafariBookmarks(0), func() any { return new(ddm.SafariBookmarks) }, true)
	})
	t.Run("SafariExtensionSettings", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleSafariExtensionSettings(0), func() any { return new(ddm.SafariExtensionSettings) }, true)
	})
	t.Run("SafariSettings", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleSafariSettings(0), func() any { return new(ddm.SafariSettings) }, true)
	})
	t.Run("ScreenSharingConnectionGroup", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleScreenSharingConnectionGroup(0), func() any { return new(ddm.ScreenSharingConnectionGroup) }, true)
	})
	t.Run("ScreenSharingConnection", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleScreenSharingConnection(0), func() any { return new(ddm.ScreenSharingConnection) }, true)
	})
	t.Run("ScreenSharingHostSettings", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleScreenSharingHostSettings(0), func() any { return new(ddm.ScreenSharingHostSettings) }, true)
	})
	t.Run("SecurityCertificate", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleSecurityCertificate(0), func() any { return new(ddm.SecurityCertificate) }, true)
	})
	t.Run("SecurityIdentity", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleSecurityIdentity(0), func() any { return new(ddm.SecurityIdentity) }, true)
	})
	t.Run("SecurityPasskeyAttestation", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleSecurityPasskeyAttestation(0), func() any { return new(ddm.SecurityPasskeyAttestation) }, true)
	})
	t.Run("ServicesBackgroundTasks", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleServicesBackgroundTasks(0), func() any { return new(ddm.ServicesBackgroundTasks) }, true)
	})
	t.Run("ServicesConfigurationFiles", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleServicesConfigurationFiles(0), func() any { return new(ddm.ServicesConfigurationFiles) }, true)
	})
	t.Run("SiriSettings", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleSiriSettings(0), func() any { return new(ddm.SiriSettings) }, true)
	})
	t.Run("SoftwareUpdateEnforcementSpecific", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleSoftwareUpdateEnforcementSpecific(0), func() any { return new(ddm.SoftwareUpdateEnforcementSpecific) }, true)
	})
	t.Run("SoftwareUpdateSettings", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleSoftwareUpdateSettings(0), func() any { return new(ddm.SoftwareUpdateSettings) }, true)
	})
	t.Run("WatchEnrollment", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleWatchEnrollment(0), func() any { return new(ddm.WatchEnrollment) }, true)
	})
	t.Run("DeclarationBase", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleDeclarationBase(0), func() any { return new(ddm.DeclarationBase) }, true)
	})
	t.Run("ManagementOrganizationInformation", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleManagementOrganizationInformation(0), func() any { return new(ddm.ManagementOrganizationInformation) }, true)
	})
	t.Run("ManagementProperties", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleManagementProperties(0), func() any { return new(ddm.ManagementProperties) }, true)
	})
	t.Run("ManagementServerCapabilities", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleManagementServerCapabilities(0), func() any { return new(ddm.ManagementServerCapabilities) }, true)
	})
}

func TestConformanceValidate(t *testing.T) {
	t.Parallel()
	conformance.Validates(t, "ActivationSimple", sampleActivationSimple(0), new(ddm.ActivationSimple))
	conformance.Validates(t, "AssetCredentialACME", sampleAssetCredentialACME(0), new(ddm.AssetCredentialACME))
	conformance.Validates(t, "AssetCredentialCertificate", sampleAssetCredentialCertificate(0), new(ddm.AssetCredentialCertificate))
	conformance.Validates(t, "AssetCredentialIdentity", sampleAssetCredentialIdentity(0), new(ddm.AssetCredentialIdentity))
	conformance.Validates(t, "AssetCredentialSCEP", sampleAssetCredentialSCEP(0), new(ddm.AssetCredentialSCEP))
	conformance.Validates(t, "AssetCredentialUserNameAndPassword", sampleAssetCredentialUserNameAndPassword(0), new(ddm.AssetCredentialUserNameAndPassword))
	conformance.Validates(t, "ACMECredential", sampleACMECredential(0), new(ddm.ACMECredential))
	conformance.Validates(t, "IdentityCredential", sampleIdentityCredential(0), new(ddm.IdentityCredential))
	conformance.Validates(t, "SCEPCredential", sampleSCEPCredential(0), new(ddm.SCEPCredential))
	conformance.Validates(t, "UserNameAndPasswordCredential", sampleUserNameAndPasswordCredential(0), new(ddm.UserNameAndPasswordCredential))
	conformance.Validates(t, "AssetData", sampleAssetData(0), new(ddm.AssetData))
	conformance.Validates(t, "AssetUserIdentity", sampleAssetUserIdentity(0), new(ddm.AssetUserIdentity))
	conformance.Validates(t, "AccountCalDAV", sampleAccountCalDAV(0), new(ddm.AccountCalDAV))
	conformance.Validates(t, "AccountCardDAV", sampleAccountCardDAV(0), new(ddm.AccountCardDAV))
	conformance.Validates(t, "AccountExchange", sampleAccountExchange(0), new(ddm.AccountExchange))
	conformance.Validates(t, "AccountGoogle", sampleAccountGoogle(0), new(ddm.AccountGoogle))
	conformance.Validates(t, "AccountLDAP", sampleAccountLDAP(0), new(ddm.AccountLDAP))
	conformance.Validates(t, "AccountMail", sampleAccountMail(0), new(ddm.AccountMail))
	conformance.Validates(t, "AccountSubscribedCalendar", sampleAccountSubscribedCalendar(0), new(ddm.AccountSubscribedCalendar))
	conformance.Validates(t, "AppManaged", sampleAppManaged(0), new(ddm.AppManaged))
	conformance.Validates(t, "AudioAccessorySettings", sampleAudioAccessorySettings(0), new(ddm.AudioAccessorySettings))
	conformance.Validates(t, "DiskManagementSettings", sampleDiskManagementSettings(0), new(ddm.DiskManagementSettings))
	conformance.Validates(t, "ExternalIntelligenceSettings", sampleExternalIntelligenceSettings(0), new(ddm.ExternalIntelligenceSettings))
	conformance.Validates(t, "IntelligenceSettings", sampleIntelligenceSettings(0), new(ddm.IntelligenceSettings))
	conformance.Validates(t, "KeyboardSettings", sampleKeyboardSettings(0), new(ddm.KeyboardSettings))
	conformance.Validates(t, "LegacyInteractiveProfile", sampleLegacyInteractiveProfile(0), new(ddm.LegacyInteractiveProfile))
	conformance.Validates(t, "LegacyProfile", sampleLegacyProfile(0), new(ddm.LegacyProfile))
	conformance.Validates(t, "ManagementStatusSubscriptions", sampleManagementStatusSubscriptions(0), new(ddm.ManagementStatusSubscriptions))
	conformance.Validates(t, "ManagementTest", sampleManagementTest(0), new(ddm.ManagementTest))
	conformance.Validates(t, "MathSettings", sampleMathSettings(0), new(ddm.MathSettings))
	conformance.Validates(t, "MigrationAssistantSettings", sampleMigrationAssistantSettings(0), new(ddm.MigrationAssistantSettings))
	conformance.Validates(t, "Package", samplePackage(0), new(ddm.Package))
	conformance.Validates(t, "PasscodeSettings", samplePasscodeSettings(0), new(ddm.PasscodeSettings))
	conformance.Validates(t, "SafariBookmarks", sampleSafariBookmarks(0), new(ddm.SafariBookmarks))
	conformance.Validates(t, "SafariExtensionSettings", sampleSafariExtensionSettings(0), new(ddm.SafariExtensionSettings))
	conformance.Validates(t, "SafariSettings", sampleSafariSettings(0), new(ddm.SafariSettings))
	conformance.Validates(t, "ScreenSharingConnectionGroup", sampleScreenSharingConnectionGroup(0), new(ddm.ScreenSharingConnectionGroup))
	conformance.Validates(t, "ScreenSharingConnection", sampleScreenSharingConnection(0), new(ddm.ScreenSharingConnection))
	conformance.Validates(t, "ScreenSharingHostSettings", sampleScreenSharingHostSettings(0), new(ddm.ScreenSharingHostSettings))
	conformance.Validates(t, "SecurityCertificate", sampleSecurityCertificate(0), new(ddm.SecurityCertificate))
	conformance.Validates(t, "SecurityIdentity", sampleSecurityIdentity(0), new(ddm.SecurityIdentity))
	conformance.Validates(t, "SecurityPasskeyAttestation", sampleSecurityPasskeyAttestation(0), new(ddm.SecurityPasskeyAttestation))
	conformance.Validates(t, "ServicesBackgroundTasks", sampleServicesBackgroundTasks(0), new(ddm.ServicesBackgroundTasks))
	conformance.Validates(t, "ServicesConfigurationFiles", sampleServicesConfigurationFiles(0), new(ddm.ServicesConfigurationFiles))
	conformance.Validates(t, "SiriSettings", sampleSiriSettings(0), new(ddm.SiriSettings))
	conformance.Validates(t, "SoftwareUpdateEnforcementSpecific", sampleSoftwareUpdateEnforcementSpecific(0), new(ddm.SoftwareUpdateEnforcementSpecific))
	conformance.Validates(t, "SoftwareUpdateSettings", sampleSoftwareUpdateSettings(0), new(ddm.SoftwareUpdateSettings))
	conformance.Validates(t, "WatchEnrollment", sampleWatchEnrollment(0), new(ddm.WatchEnrollment))
	conformance.Validates(t, "DeclarationBase", sampleDeclarationBase(0), new(ddm.DeclarationBase))
	conformance.Validates(t, "ManagementOrganizationInformation", sampleManagementOrganizationInformation(0), new(ddm.ManagementOrganizationInformation))
	conformance.Validates(t, "ManagementProperties", sampleManagementProperties(0), new(ddm.ManagementProperties))
	conformance.Validates(t, "ManagementServerCapabilities", sampleManagementServerCapabilities(0), new(ddm.ManagementServerCapabilities))
}

func TestConformanceRegistry(t *testing.T) {
	t.Parallel()
	if len(ddm.Registry) != 51 {
		t.Fatalf("registry has %d entries, want 51", len(ddm.Registry))
	}
	for name, en := range ddm.Registry {
		v := en.New()
		if v == nil || v.DeclarationTypeName() != en.ID || v.SchemaPath() != en.Schema {
			t.Errorf("registry entry %q is inconsistent: %+v", name, en)
		}
		var _ ddm.Declaration = v
		found := false
		for _, x := range ddm.ByID(en.ID) {
			if x.Schema == en.Schema {
				found = true
			}
		}
		if !found {
			t.Errorf("ByID(%q) does not contain %s", en.ID, name)
		}
	}
	if ids := ddm.IDs(); len(ids) == 0 || len(ids) > len(ddm.Registry) {
		t.Errorf("IDs() = %d", len(ids))
	}
	if len(ddm.ByID("no-such-id")) != 0 {
		t.Error("ByID(no-such-id) should be empty")
	}
	if ddm.Support("nope") != nil {
		t.Error("Support(nope) should be nil")
	}
	if ddm.Support("ActivationSimple") == nil {
		t.Error("missing support entry for ActivationSimple")
	}
	if ddm.Support("AssetCredentialACME") == nil {
		t.Error("missing support entry for AssetCredentialACME")
	}
	if ddm.Support("AssetCredentialCertificate") == nil {
		t.Error("missing support entry for AssetCredentialCertificate")
	}
	if ddm.Support("AssetCredentialIdentity") == nil {
		t.Error("missing support entry for AssetCredentialIdentity")
	}
	if ddm.Support("AssetCredentialSCEP") == nil {
		t.Error("missing support entry for AssetCredentialSCEP")
	}
	if ddm.Support("AssetCredentialUserNameAndPassword") == nil {
		t.Error("missing support entry for AssetCredentialUserNameAndPassword")
	}
	if ddm.Support("ACMECredential") == nil {
		t.Error("missing support entry for ACMECredential")
	}
	if ddm.Support("IdentityCredential") == nil {
		t.Error("missing support entry for IdentityCredential")
	}
	if ddm.Support("SCEPCredential") == nil {
		t.Error("missing support entry for SCEPCredential")
	}
	if ddm.Support("UserNameAndPasswordCredential") == nil {
		t.Error("missing support entry for UserNameAndPasswordCredential")
	}
	if ddm.Support("AssetData") == nil {
		t.Error("missing support entry for AssetData")
	}
	if ddm.Support("AssetUserIdentity") == nil {
		t.Error("missing support entry for AssetUserIdentity")
	}
	if ddm.Support("AccountCalDAV") == nil {
		t.Error("missing support entry for AccountCalDAV")
	}
	if ddm.Support("AccountCardDAV") == nil {
		t.Error("missing support entry for AccountCardDAV")
	}
	if ddm.Support("AccountExchange") == nil {
		t.Error("missing support entry for AccountExchange")
	}
	if ddm.Support("AccountGoogle") == nil {
		t.Error("missing support entry for AccountGoogle")
	}
	if ddm.Support("AccountLDAP") == nil {
		t.Error("missing support entry for AccountLDAP")
	}
	if ddm.Support("AccountMail") == nil {
		t.Error("missing support entry for AccountMail")
	}
	if ddm.Support("AccountSubscribedCalendar") == nil {
		t.Error("missing support entry for AccountSubscribedCalendar")
	}
	if ddm.Support("AppManaged") == nil {
		t.Error("missing support entry for AppManaged")
	}
	if ddm.Support("AudioAccessorySettings") == nil {
		t.Error("missing support entry for AudioAccessorySettings")
	}
	if ddm.Support("DiskManagementSettings") == nil {
		t.Error("missing support entry for DiskManagementSettings")
	}
	if ddm.Support("ExternalIntelligenceSettings") == nil {
		t.Error("missing support entry for ExternalIntelligenceSettings")
	}
	if ddm.Support("IntelligenceSettings") == nil {
		t.Error("missing support entry for IntelligenceSettings")
	}
	if ddm.Support("KeyboardSettings") == nil {
		t.Error("missing support entry for KeyboardSettings")
	}
	if ddm.Support("LegacyInteractiveProfile") == nil {
		t.Error("missing support entry for LegacyInteractiveProfile")
	}
	if ddm.Support("LegacyProfile") == nil {
		t.Error("missing support entry for LegacyProfile")
	}
	if ddm.Support("ManagementStatusSubscriptions") == nil {
		t.Error("missing support entry for ManagementStatusSubscriptions")
	}
	if ddm.Support("ManagementTest") == nil {
		t.Error("missing support entry for ManagementTest")
	}
	if ddm.Support("MathSettings") == nil {
		t.Error("missing support entry for MathSettings")
	}
	if ddm.Support("MigrationAssistantSettings") == nil {
		t.Error("missing support entry for MigrationAssistantSettings")
	}
	if ddm.Support("Package") == nil {
		t.Error("missing support entry for Package")
	}
	if ddm.Support("PasscodeSettings") == nil {
		t.Error("missing support entry for PasscodeSettings")
	}
	if ddm.Support("SafariBookmarks") == nil {
		t.Error("missing support entry for SafariBookmarks")
	}
	if ddm.Support("SafariExtensionSettings") == nil {
		t.Error("missing support entry for SafariExtensionSettings")
	}
	if ddm.Support("SafariSettings") == nil {
		t.Error("missing support entry for SafariSettings")
	}
	if ddm.Support("ScreenSharingConnectionGroup") == nil {
		t.Error("missing support entry for ScreenSharingConnectionGroup")
	}
	if ddm.Support("ScreenSharingConnection") == nil {
		t.Error("missing support entry for ScreenSharingConnection")
	}
	if ddm.Support("ScreenSharingHostSettings") == nil {
		t.Error("missing support entry for ScreenSharingHostSettings")
	}
	if ddm.Support("SecurityCertificate") == nil {
		t.Error("missing support entry for SecurityCertificate")
	}
	if ddm.Support("SecurityIdentity") == nil {
		t.Error("missing support entry for SecurityIdentity")
	}
	if ddm.Support("SecurityPasskeyAttestation") == nil {
		t.Error("missing support entry for SecurityPasskeyAttestation")
	}
	if ddm.Support("ServicesBackgroundTasks") == nil {
		t.Error("missing support entry for ServicesBackgroundTasks")
	}
	if ddm.Support("ServicesConfigurationFiles") == nil {
		t.Error("missing support entry for ServicesConfigurationFiles")
	}
	if ddm.Support("SiriSettings") == nil {
		t.Error("missing support entry for SiriSettings")
	}
	if ddm.Support("SoftwareUpdateEnforcementSpecific") == nil {
		t.Error("missing support entry for SoftwareUpdateEnforcementSpecific")
	}
	if ddm.Support("SoftwareUpdateSettings") == nil {
		t.Error("missing support entry for SoftwareUpdateSettings")
	}
	if ddm.Support("WatchEnrollment") == nil {
		t.Error("missing support entry for WatchEnrollment")
	}
	if ddm.Support("DeclarationBase") == nil {
		t.Error("missing support entry for DeclarationBase")
	}
	if ddm.Support("ManagementOrganizationInformation") == nil {
		t.Error("missing support entry for ManagementOrganizationInformation")
	}
	if ddm.Support("ManagementProperties") == nil {
		t.Error("missing support entry for ManagementProperties")
	}
	if ddm.Support("ManagementServerCapabilities") == nil {
		t.Error("missing support entry for ManagementServerCapabilities")
	}
}
