// Code generated by admgen; DO NOT EDIT.
// Source: apple/device-management@67045e2fa06f528b196c01edee6a8bf88b844beb

package ddm

// ReasonDetail is one key Apple documents in the details dictionary of a
// reason. The keys a reason carries depend on the reason.
type ReasonDetail struct {
	// Key is the wire key inside the details dictionary.
	Key string
	// Type is Apple's declared type for the value, such as "<string>".
	Type string
	// Description is Apple's prose for the key.
	Description string
}

// ReasonEntry is one reason code as a single schema declares it. Apple
// scopes the vocabulary to the schema, so a code that two schemas
// declare has one entry per schema and the prose differs between them.
type ReasonEntry struct {
	// Code is the wire value, matching the Code field of a status report reason.
	Code string
	// Description is Apple's prose for the code in this schema.
	Description string
	// Schema is the YAML path in apple/device-management that declares it.
	Schema string
	// Details are the keys Apple documents in the reason's details dictionary.
	Details []ReasonDetail
}

// Reason codes.
const (
	// ReasonErrorActivationFailed is Apple's "Error.ActivationFailed": A
	// configuration or asset cannot be activated due to an activation that
	// failed.
	ReasonErrorActivationFailed = "Error.ActivationFailed"
	// ReasonErrorAssetCannotBeDeserialized is Apple's
	// "Error.AssetCannotBeDeserialized": The asset data does not conform to
	// the expected data type.
	ReasonErrorAssetCannotBeDeserialized = "Error.AssetCannotBeDeserialized"
	// ReasonErrorAssetCannotBeDownloaded is Apple's
	// "Error.AssetCannotBeDownloaded": The asset data cannot be downloaded.
	ReasonErrorAssetCannotBeDownloaded = "Error.AssetCannotBeDownloaded"
	// ReasonErrorAssetCannotBeVerified is Apple's
	// "Error.AssetCannotBeVerified": The downloaded asset data cannot be
	// verified.
	ReasonErrorAssetCannotBeVerified = "Error.AssetCannotBeVerified"
	// ReasonErrorConfigurationCannotBeApplied is Apple's
	// "Error.ConfigurationCannotBeApplied": The configuration cannot be
	// applied to the device.
	ReasonErrorConfigurationCannotBeApplied = "Error.ConfigurationCannotBeApplied"
	// ReasonErrorConfigurationCannotBeDeserialized is Apple's
	// "Error.ConfigurationCannotBeDeserialized": The configuration is not
	// valid.
	ReasonErrorConfigurationCannotBeDeserialized = "Error.ConfigurationCannotBeDeserialized"
	// ReasonErrorConfigurationFailed is Apple's "Error.ConfigurationFailed":
	// An asset cannot be activated due to a configuration that failed.
	ReasonErrorConfigurationFailed = "Error.ConfigurationFailed"
	// ReasonErrorConfigurationIsInvalid is Apple's
	// "Error.ConfigurationIsInvalid": The configuration is not valid for
	// applying to the device.
	ReasonErrorConfigurationIsInvalid = "Error.ConfigurationIsInvalid"
	// ReasonErrorConfigurationNotSupported is Apple's
	// "Error.ConfigurationNotSupported": The configuration is not supported
	// for this platform, scope, or enrollment type.
	ReasonErrorConfigurationNotSupported = "Error.ConfigurationNotSupported"
	// ReasonErrorInvalidPayload is Apple's "Error.InvalidPayload": A
	// declaration is not fully loaded.
	ReasonErrorInvalidPayload = "Error.InvalidPayload"
	// ReasonErrorMissingAssets is Apple's "Error.MissingAssets": A
	// configuration being activated references assets that are not present.
	ReasonErrorMissingAssets = "Error.MissingAssets"
	// ReasonErrorMissingConfigurations is Apple's
	// "Error.MissingConfigurations": An activation being activated
	// references configurations that are not present.
	ReasonErrorMissingConfigurations = "Error.MissingConfigurations"
	// ReasonErrorMissingState is Apple's "Error.MissingState": A declaration
	// is missing internal state information.
	ReasonErrorMissingState = "Error.MissingState"
	// ReasonErrorPredicateFailed is Apple's "Error.PredicateFailed": A
	// predicate evaluation failed.
	ReasonErrorPredicateFailed = "Error.PredicateFailed"
	// ReasonErrorUnableToEvaluatePredicate is Apple's
	// "Error.UnableToEvaluatePredicate": A predicate cannot be evaluated.
	ReasonErrorUnableToEvaluatePredicate = "Error.UnableToEvaluatePredicate"
	// ReasonErrorUnableToParsePredicate is Apple's
	// "Error.UnableToParsePredicate": A predicate expression cannot be
	// parsed.
	ReasonErrorUnableToParsePredicate = "Error.UnableToParsePredicate"
	// ReasonErrorUnableToParsePredicateWithCustomOperator is Apple's
	// "Error.UnableToParsePredicateWithCustomOperator": A predicate
	// expression with a custom operator cannot be parsed.
	ReasonErrorUnableToParsePredicateWithCustomOperator = "Error.UnableToParsePredicateWithCustomOperator"
	// ReasonErrorUnknown is Apple's "Error.Unknown": An unrecognized NSError
	// was generated.
	ReasonErrorUnknown = "Error.Unknown"
	// ReasonErrorUnknownDeclarationType is Apple's
	// "Error.UnknownDeclarationType": The declaration type is not known.
	ReasonErrorUnknownDeclarationType = "Error.UnknownDeclarationType"
	// ReasonErrorUnknownPayloadKeys is Apple's "Error.UnknownPayloadKeys": A
	// declaration contains unknown payloads keys.
	ReasonErrorUnknownPayloadKeys = "Error.UnknownPayloadKeys"
	// ReasonInfoNotReferencedByActivation is Apple's
	// "Info.NotReferencedByActivation": A configuration is not referenced in
	// any activation.
	ReasonInfoNotReferencedByActivation = "Info.NotReferencedByActivation"
	// ReasonInfoNotReferencedByConfiguration is Apple's
	// "Info.NotReferencedByConfiguration": An asset is not referenced in any
	// configuration.
	ReasonInfoNotReferencedByConfiguration = "Info.NotReferencedByConfiguration"
	// ReasonInfoPredicate is Apple's "Info.Predicate": A predicate evaluated
	// to false.
	ReasonInfoPredicate = "Info.Predicate"
	// ReasonInfoUnsupportedSettings is Apple's "Info.UnsupportedSettings":
	// Unsupported settings in a configuration.
	ReasonInfoUnsupportedSettings = "Info.UnsupportedSettings"
)

// Reasons maps each reason code to every schema declaration of it. A
// code absent from the map is one Apple's schema does not define, which
// makes the map the bound on the vocabulary for a caller labelling by
// code.
var Reasons = map[string][]ReasonEntry{
	ReasonErrorActivationFailed: {
		{Code: ReasonErrorActivationFailed, Description: "A configuration or asset cannot be activated due to an activation that failed.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "Identifier", Type: "<string>", Description: "The `Identifier` of the declaration."},
			{Key: "ServerToken", Type: "<string>", Description: "The `ServerToken` of the declaration."},
		}},
	},
	ReasonErrorAssetCannotBeDeserialized: {
		{Code: ReasonErrorAssetCannotBeDeserialized, Description: "The asset data does not conform to the expected data type.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "Error", Type: "<string>", Description: "Description of the underlying NSError."},
		}},
	},
	ReasonErrorAssetCannotBeDownloaded: {
		{Code: ReasonErrorAssetCannotBeDownloaded, Description: "The asset data cannot be downloaded.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "Error", Type: "<string>", Description: "Description of the underlying NSError."},
		}},
	},
	ReasonErrorAssetCannotBeVerified: {
		{Code: ReasonErrorAssetCannotBeVerified, Description: "The downloaded asset data cannot be verified.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "Error", Type: "<string>", Description: "Description of the underlying NSError."},
		}},
	},
	ReasonErrorConfigurationCannotBeApplied: {
		{Code: ReasonErrorConfigurationCannotBeApplied, Description: "The configuration cannot be applied to the device.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "Error", Type: "<string>", Description: "Description of the underlying NSError."},
		}},
	},
	ReasonErrorConfigurationCannotBeDeserialized: {
		{Code: ReasonErrorConfigurationCannotBeDeserialized, Description: "The configuration is not valid.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "Error", Type: "<string>", Description: "Description of the underlying NSError."},
		}},
	},
	ReasonErrorConfigurationFailed: {
		{Code: ReasonErrorConfigurationFailed, Description: "An asset cannot be activated due to a configuration that failed.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "Identifier", Type: "<string>", Description: "The `Identifier` of the declaration."},
			{Key: "ServerToken", Type: "<string>", Description: "The `ServerToken` of the declaration."},
		}},
	},
	ReasonErrorConfigurationIsInvalid: {
		{Code: ReasonErrorConfigurationIsInvalid, Description: "The configuration is not valid for applying to the device.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "Error", Type: "<string>", Description: "Description of the underlying NSError."},
		}},
	},
	ReasonErrorConfigurationNotSupported: {
		{Code: ReasonErrorConfigurationNotSupported, Description: "The configuration is not supported for this platform, scope, or enrollment type.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "Identifier", Type: "<string>", Description: "The `Identifier` of the configuration."},
			{Key: "ServerToken", Type: "<string>", Description: "The `ServerToken` of the configuration."},
		}},
	},
	ReasonErrorInvalidPayload: {
		{Code: ReasonErrorInvalidPayload, Description: "A declaration is not fully loaded.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "Identifier", Type: "<string>", Description: "The `Identifier` of the declaration."},
			{Key: "ServerToken", Type: "<string>", Description: "The `ServerToken` of the declaration."},
		}},
	},
	ReasonErrorMissingAssets: {
		{Code: ReasonErrorMissingAssets, Description: "A configuration being activated references assets that are not present.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "Identifier", Type: "<string>", Description: "The `Identifier` of the configuration."},
			{Key: "ServerToken", Type: "<string>", Description: "The `ServerToken` of the configuration."},
			{Key: "AssetIdentifiers", Type: "<array>", Description: "Array of strings containing each missing asset `Identifier` value."},
		}},
	},
	ReasonErrorMissingConfigurations: {
		{Code: ReasonErrorMissingConfigurations, Description: "An activation being activated references configurations that are not present.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "Identifier", Type: "<string>", Description: "The `Identifier` of the activation."},
			{Key: "ServerToken", Type: "<string>", Description: "The `ServerToken` of the activation."},
			{Key: "ConfigurationIdentifiers", Type: "<array>", Description: "Array of strings containing each missing configuration `Identifier` value."},
		}},
	},
	ReasonErrorMissingState: {
		{Code: ReasonErrorMissingState, Description: "A declaration is missing internal state information.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "Identifier", Type: "<string>", Description: "The `Identifier` of the declaration."},
			{Key: "ServerToken", Type: "<string>", Description: "The `ServerToken` of the declaration."},
		}},
	},
	ReasonErrorPredicateFailed: {
		{Code: ReasonErrorPredicateFailed, Description: "A predicate evaluation failed.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "Identifier", Type: "<string>", Description: "The `Identifier` of the activation whose predicate failed."},
			{Key: "ServerToken", Type: "<string>", Description: "The `ServerToken` of the activation whose predicate failed."},
			{Key: "Predicate", Type: "<string>", Description: "The predicate description of the predicate that failed."},
			{Key: "Domain", Type: "<string>", Description: "Underlying NSError's domain."},
			{Key: "Code", Type: "<string>", Description: "Underlying NSError's code."},
		}},
	},
	ReasonErrorUnableToEvaluatePredicate: {
		{Code: ReasonErrorUnableToEvaluatePredicate, Description: "A predicate cannot be evaluated.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "Identifier", Type: "<string>", Description: "The `Identifier` of the activation whose predicate failed to evaluate."},
			{Key: "ServerToken", Type: "<string>", Description: "The `ServerToken` of the activation whose predicate failed to evaluate."},
			{Key: "Predicate", Type: "<string>", Description: "The predicate description of the predicate that failed to evaluate."},
		}},
	},
	ReasonErrorUnableToParsePredicate: {
		{Code: ReasonErrorUnableToParsePredicate, Description: "A predicate expression cannot be parsed.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "Identifier", Type: "<string>", Description: "The `Identifier` of the activation whose predicate failed to parse."},
			{Key: "ServerToken", Type: "<string>", Description: "The `ServerToken` of the activation whose predicate failed to parse."},
			{Key: "Predicate", Type: "<string>", Description: "The predicate description of the predicate that failed to parse."},
		}},
	},
	ReasonErrorUnableToParsePredicateWithCustomOperator: {
		{Code: ReasonErrorUnableToParsePredicateWithCustomOperator, Description: "A predicate expression with a custom operator cannot be parsed.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "Identifier", Type: "<string>", Description: "The `Identifier` of the activation whose predicate failed to parse."},
			{Key: "ServerToken", Type: "<string>", Description: "The `ServerToken` of the activation whose predicate failed to parse."},
			{Key: "Predicate", Type: "<string>", Description: "The predicate description of the predicate that failed to parse."},
		}},
	},
	ReasonErrorUnknown: {
		{Code: ReasonErrorUnknown, Description: "An unrecognized NSError was generated.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "Domain", Type: "<string>", Description: "NSError's domain."},
			{Key: "Code", Type: "<string>", Description: "NSError's code."},
		}},
	},
	ReasonErrorUnknownDeclarationType: {
		{Code: ReasonErrorUnknownDeclarationType, Description: "The declaration type is not known.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "UnknownDeclarationType", Type: "<string>", Description: "The `Type` of the declaration."},
		}},
	},
	ReasonErrorUnknownPayloadKeys: {
		{Code: ReasonErrorUnknownPayloadKeys, Description: "A declaration contains unknown payloads keys.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "UnknownPayloadKeys", Type: "<array>", Description: "Array of strings containing each unknown key-path."},
		}},
	},
	ReasonInfoNotReferencedByActivation: {
		{Code: ReasonInfoNotReferencedByActivation, Description: "A configuration is not referenced in any activation.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "Identifier", Type: "<string>", Description: "The `Identifier` of the configuration."},
			{Key: "ServerToken", Type: "<string>", Description: "The `ServerToken` of the configuration."},
		}},
	},
	ReasonInfoNotReferencedByConfiguration: {
		{Code: ReasonInfoNotReferencedByConfiguration, Description: "An asset is not referenced in any configuration.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "Identifier", Type: "<string>", Description: "The `Identifier` of the asset."},
			{Key: "ServerToken", Type: "<string>", Description: "The `ServerToken` of the asset."},
		}},
	},
	ReasonInfoPredicate: {
		{Code: ReasonInfoPredicate, Description: "A predicate evaluated to false.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "Identifier", Type: "<string>", Description: "The `Identifier` of the activation whose predicate is false."},
			{Key: "ServerToken", Type: "<string>", Description: "The `ServerToken` of the activation whose predicate is false."},
			{Key: "Predicate", Type: "<string>", Description: "The predicate description of the predicate that is false."},
		}},
	},
	ReasonInfoUnsupportedSettings: {
		{Code: ReasonInfoUnsupportedSettings, Description: "Unsupported settings in a configuration.", Schema: "declarative/declarations/declarationbase.yaml", Details: []ReasonDetail{
			{Key: "Settings", Type: "<array>", Description: "Array of strings containing each unsupported setting key-path."},
		}},
	},
}

// ReasonCodes returns the distinct reason codes in sorted order.
func ReasonCodes() []string {
	out := make([]string, 0, len(Reasons))
	for code := range Reasons {
		out = append(out, code)
	}
	sortStrings(out)
	return out
}
