// Code generated by admgen; DO NOT EDIT.
// Source: apple/device-management@67045e2fa06f528b196c01edee6a8bf88b844beb

package ddmproto_test

import (
	"testing"

	"github.com/deploymenttheory/go-apple-mdm/schema/ddmproto"
	"github.com/deploymenttheory/go-apple-mdm/schema/internal/conformance"
)

func sampleDeclarationItemsResponse(d int) *ddmproto.DeclarationItemsResponse {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddmproto.DeclarationItemsResponse{
		Declarations:      conformance.Deref(sampleDeclarationItemsResponseDeclarations(d + 1)),
		DeclarationsToken: "s",
	}
}

func sampleDeclarationItemsResponseDeclarations(d int) *ddmproto.DeclarationItemsResponseDeclarations {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddmproto.DeclarationItemsResponseDeclarations{
		Activations:    conformance.SliceOf(sampleDeclarationItemsResponseDeclarationItem(d + 1)),
		Configurations: conformance.SliceOf(sampleDeclarationItemsResponseDeclarationItem(d + 1)),
		Assets:         conformance.SliceOf(sampleDeclarationItemsResponseDeclarationItem(d + 1)),
		Management:     conformance.SliceOf(sampleDeclarationItemsResponseDeclarationItem(d + 1)),
	}
}

func sampleDeclarationItemsResponseDeclarationItem(d int) *ddmproto.DeclarationItemsResponseDeclarationItem {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddmproto.DeclarationItemsResponseDeclarationItem{
		Identifier:  "s",
		ServerToken: "s",
	}
}

func sampleStatusReport(d int) *ddmproto.StatusReport {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddmproto.StatusReport{
		StatusItems: map[string]any{"k": "v"},
		Errors:      conformance.SliceOf(sampleStatusReportErrors(d + 1)),
		FullReport:  new(true),
	}
}

func sampleStatusReportErrors(d int) *ddmproto.StatusReportErrors {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddmproto.StatusReportErrors{
		StatusItem: "s",
		Reasons:    conformance.SliceOf(sampleStatusReportStatusReason(d + 1)),
	}
}

func sampleStatusReportStatusReason(d int) *ddmproto.StatusReportStatusReason {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddmproto.StatusReportStatusReason{
		Code:        "s",
		Description: new("s"),
		Details:     map[string]any{"k": "v"},
	}
}

func sampleTokensResponse(d int) *ddmproto.TokensResponse {
	if d > 12 {
		return nil
	}
	_ = d
	return &ddmproto.TokensResponse{
		SyncTokens: map[string]any{"k": "v"},
	}
}

func TestConformanceRoundTrip(t *testing.T) {
	t.Parallel()
	t.Run("DeclarationItemsResponse", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleDeclarationItemsResponse(0), func() any { return new(ddmproto.DeclarationItemsResponse) }, true)
	})
	t.Run("StatusReport", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleStatusReport(0), func() any { return new(ddmproto.StatusReport) }, true)
	})
	t.Run("TokensResponse", func(t *testing.T) {
		t.Parallel()
		conformance.RoundTrip(t, sampleTokensResponse(0), func() any { return new(ddmproto.TokensResponse) }, true)
	})
}

func TestConformanceValidate(t *testing.T) {
	t.Parallel()
	conformance.Validates(t, "DeclarationItemsResponse", sampleDeclarationItemsResponse(0), new(ddmproto.DeclarationItemsResponse))
	conformance.Validates(t, "StatusReport", sampleStatusReport(0), new(ddmproto.StatusReport))
	conformance.Validates(t, "TokensResponse", sampleTokensResponse(0), new(ddmproto.TokensResponse))
}

func TestConformanceRegistry(t *testing.T) {
	t.Parallel()
	if len(ddmproto.Registry) != 3 {
		t.Fatalf("registry has %d entries, want 3", len(ddmproto.Registry))
	}
	for name, en := range ddmproto.Registry {
		v := en.New()
		if v == nil || v.TypeName() != en.ID || v.SchemaPath() != en.Schema {
			t.Errorf("registry entry %q is inconsistent: %+v", name, en)
		}
		var _ ddmproto.Object = v
		found := false
		for _, x := range ddmproto.ByID(en.ID) {
			if x.Schema == en.Schema {
				found = true
			}
		}
		if !found {
			t.Errorf("ByID(%q) does not contain %s", en.ID, name)
		}
	}
	if ids := ddmproto.IDs(); len(ids) == 0 || len(ids) > len(ddmproto.Registry) {
		t.Errorf("IDs() = %d", len(ids))
	}
	if len(ddmproto.ByID("no-such-id")) != 0 {
		t.Error("ByID(no-such-id) should be empty")
	}
	if ddmproto.Support("nope") != nil {
		t.Error("Support(nope) should be nil")
	}
	if ddmproto.Support("DeclarationItemsResponse") == nil {
		t.Error("missing support entry for DeclarationItemsResponse")
	}
	if ddmproto.Support("StatusReport") == nil {
		t.Error("missing support entry for StatusReport")
	}
	if ddmproto.Support("TokensResponse") == nil {
		t.Error("missing support entry for TokensResponse")
	}
}
