// Code generated by admgen; DO NOT EDIT.
// Source: apple/device-management@67045e2fa06f528b196c01edee6a8bf88b844beb

// Package ddmproto contains declarative device management protocol messages generated from Apple's device
// management schema (declarative/protocol/ in
// https://github.com/apple/device-management).
//
// Documentation: https://developer.apple.com/documentation/devicemanagement/declarativemanagementrequest
//
// This package holds 3 schema files and 7 types. Every type carries
// plist and json struct tags with Apple's wire keys, a Validate method
// driven by the schema's constraints, and support metadata queryable through
// Support(path) or the schema/support package.
package ddmproto
