// Code generated by admgen; DO NOT EDIT.
// Source: apple/device-management@67045e2fa06f528b196c01edee6a8bf88b844beb

package ddmproto

import (
	"github.com/deploymenttheory/go-apple-mdm/schema/support"
)

// Object is implemented by every top-level type in this package.
type Object interface {
	// TypeName returns the wire identifier from Apple's schema.
	TypeName() string
	// SchemaPath returns the schema file the type was generated from.
	SchemaPath() string
	// Validate checks the value against the schema for the target.
	Validate(t support.Target) error
}

// Entry describes one schema in the Registry.
type Entry struct {
	// ID is the wire identifier: RequestType, MessageType, PayloadType,
	// DeclarationType, StatusItemType, error code, or type name.
	ID string
	// Schema is the YAML path in apple/device-management.
	Schema string
	Title  string
	// New returns a zero value of the type as Object.
	New func() Object
	// NewResponse returns a zero response value, or nil when the schema
	// defines no response keys.
	NewResponse func() any
}

// Wire identifiers.
const (
	// TypeDeclarationItemsResponse: Declaration Items Response
	TypeDeclarationItemsResponse = "DeclarationItemsResponse"
	// TypeStatusReport: Status Report
	TypeStatusReport = "StatusReport"
	// TypeTokensResponse: Tokens Response
	TypeTokensResponse = "TokensResponse" // #nosec G101 -- Apple wire identifier, not a credential
)

// Registry maps Go type names to constructors, one entry per schema file.
// Several schemas may share a wire identifier (for example six profile
// payloads use com.apple.MCX), so look up by identifier with ByID.
var Registry = map[string]Entry{
	"DeclarationItemsResponse": {ID: "DeclarationItemsResponse", Schema: "declarative/protocol/declarationitemsresponse.yaml", Title: "Declaration Items Response", New: func() Object { return new(DeclarationItemsResponse) }},
	"StatusReport":             {ID: "StatusReport", Schema: "declarative/protocol/statusreport.yaml", Title: "Status Report", New: func() Object { return new(StatusReport) }},
	"TokensResponse":           {ID: "TokensResponse", Schema: "declarative/protocol/tokensresponse.yaml", Title: "Tokens Response", New: func() Object { return new(TokensResponse) }},
}

// IDs returns the distinct wire identifiers in sorted order.
func IDs() []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(Registry))
	for _, en := range Registry {
		if !seen[en.ID] {
			seen[en.ID] = true
			out = append(out, en.ID)
		}
	}
	sortStrings(out)
	return out
}

// ByID returns every entry with the given wire identifier, sorted by type name.
func ByID(id string) []Entry {
	var names []string
	for name, en := range Registry {
		if en.ID == id {
			names = append(names, name)
		}
	}
	sortStrings(names)
	out := make([]Entry, 0, len(names))
	for _, n := range names {
		out = append(out, Registry[n])
	}
	return out
}

func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j-1] > s[j]; j-- {
			s[j-1], s[j] = s[j], s[j-1]
		}
	}
}

// TypeName returns "DeclarationItemsResponse".
func (*DeclarationItemsResponse) TypeName() string { return "DeclarationItemsResponse" }

// TypeName returns "StatusReport".
func (*StatusReport) TypeName() string { return "StatusReport" }

// TypeName returns "TokensResponse".
func (*TokensResponse) TypeName() string { return "TokensResponse" }
