// Code generated by admgen; DO NOT EDIT.
// Source: apple/device-management@67045e2fa06f528b196c01edee6a8bf88b844beb

package ddmproto

// DeclarationItemsResponse: The set of available declarations on the server.
//
// DeclarationItemsResponse corresponds to declarative/protocol/declarationitemsresponse.yaml (Declaration Items Response).
type DeclarationItemsResponse struct {
	// The set of available declarations on the server.
	Declarations DeclarationItemsResponseDeclarations `plist:"Declarations,omitempty" json:"Declarations,omitempty"`
	// The current value of the declarations token. Clients use this to detect when
	// declarations change so they can refetch the token.
	DeclarationsToken string `plist:"DeclarationsToken" json:"DeclarationsToken"`
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*DeclarationItemsResponse) SchemaPath() string {
	return "declarative/protocol/declarationitemsresponse.yaml"
}

// DeclarationItemsResponseDeclarations: The set of available declarations on the server.
type DeclarationItemsResponseDeclarations struct {
	// The list of available activation declarations on the server.
	Activations []DeclarationItemsResponseDeclarationItem `plist:"Activations,omitempty" json:"Activations,omitempty"`
	// The list of available configuration declarations on the server.
	Configurations []DeclarationItemsResponseDeclarationItem `plist:"Configurations,omitempty" json:"Configurations,omitempty"`
	// The list of available asset declarations on the server.
	Assets []DeclarationItemsResponseDeclarationItem `plist:"Assets,omitempty" json:"Assets,omitempty"`
	// The list of available management declarations on the server.
	Management []DeclarationItemsResponseDeclarationItem `plist:"Management,omitempty" json:"Management,omitempty"`
}

// DeclarationItemsResponseDeclarationItem: Information about an available declaration on the
// server.
type DeclarationItemsResponseDeclarationItem struct {
	// The declaration's identifier.
	Identifier string `plist:"Identifier" json:"Identifier"`
	// The 'ServerToken' value of the declaration. The client uses this to determine if the
	// actual payload is different from the one on the client. Servers must compute the token
	// over the entire declaration content to ensure the value always changes whenever there's
	// any change to the content.
	ServerToken string `plist:"ServerToken" json:"ServerToken"`
}

// StatusReport: Status sent by the client.
//
// StatusReport corresponds to declarative/protocol/statusreport.yaml (Status Report).
type StatusReport struct {
	// The status items for this report.
	StatusItems map[string]any `plist:"StatusItems,omitempty" json:"StatusItems,omitempty"`
	// An array of errors for this status report.
	Errors []StatusReportErrors `plist:"Errors,omitempty" json:"Errors,omitempty"`
	// The system sets this to `true` to indicate that the status report contains the full set
	// of current status, and is not an incremental report. A full status report includes the
	// full set of items in any status array item, not just the changes. Servers use this to
	// replace their entire status for the device, rather than do an incremental update to the
	// existing status. The system sets this to `true` when sending a "safety sync" status
	// report, which is typically sent every 24 hours or so.
	FullReport *bool `plist:"FullReport,omitempty" json:"FullReport,omitempty"`
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*StatusReport) SchemaPath() string { return "declarative/protocol/statusreport.yaml" }

// StatusReportErrors: Error information for a status item that cannot be returned.
type StatusReportErrors struct {
	// The status item that this error pertains to.
	StatusItem string `plist:"StatusItem" json:"StatusItem"`
	// An array of reasons for the error.
	Reasons []StatusReportStatusReason `plist:"Reasons,omitempty" json:"Reasons,omitempty"`
}

// StatusReportStatusReason: Information about a status error.
type StatusReportStatusReason struct {
	// The error code for this error.
	Code string `plist:"Code" json:"Code"`
	// The description for this error.
	Description *string `plist:"Description,omitempty" json:"Description,omitempty"`
	// A dictionary that contains further details about this error.
	Details map[string]any `plist:"Details,omitempty" json:"Details,omitempty"`
}

// TokensResponse: The server's synchronization tokens.
//
// TokensResponse corresponds to declarative/protocol/tokensresponse.yaml (Tokens Response).
type TokensResponse struct {
	// A dictionary of synchronization tokens that describes the state of different types of
	// data on the server. The client uses these tokens to determine which endpoints it needs
	// to use to fetch new or updated data on the server.
	SyncTokens map[string]any `plist:"SyncTokens,omitempty" json:"SyncTokens,omitempty"`
}

// SchemaPath returns the Apple schema file this type was generated from.
func (*TokensResponse) SchemaPath() string { return "declarative/protocol/tokensresponse.yaml" }
