// Code generated by admgen; DO NOT EDIT.
// Source: apple/device-management@67045e2fa06f528b196c01edee6a8bf88b844beb

package other

import (
	"github.com/deploymenttheory/go-apple-dm/schema/support"
	"github.com/deploymenttheory/go-apple-dm/schema/validation"
)

// Validate checks x against the schema. With a non-zero target it also checks
// that every present key is supported on that OS version and enrollment context.
func (x *EnrollmentSSODocument) Validate(t support.Target) error {
	c := validation.New(t)
	x.validate(c, "")
	return c.Err()
}

func (x *EnrollmentSSODocument) validate(c *validation.Collector, p string) {
	{
		path := validation.Join(p, "iTunesStoreID")
		present := x.ITunesStoreID != nil
		_, _ = path, present
		c.Support(path, present, supportTable["EnrollmentSSODocument.iTunesStoreID"])
	}
	{
		path := validation.Join(p, "AppIDs")
		present := len(x.AppIDs) > 0
		_, _ = path, present
		c.Support(path, present, supportTable["EnrollmentSSODocument.AppIDs"])
	}
	{
		path := validation.Join(p, "AssociatedDomains")
		present := len(x.AssociatedDomains) > 0
		_, _ = path, present
		c.Support(path, present, supportTable["EnrollmentSSODocument.AssociatedDomains"])
	}
	{
		path := validation.Join(p, "AssociatedDomainsEnableDirectDownloads")
		present := x.AssociatedDomainsEnableDirectDownloads != nil
		_, _ = path, present
		c.Support(path, present, supportTable["EnrollmentSSODocument.AssociatedDomainsEnableDirectDownloads"])
	}
	{
		path := validation.Join(p, "ConfigurationProfile")
		present := len(x.ConfigurationProfile) > 0
		_, _ = path, present
		c.Support(path, present, supportTable["EnrollmentSSODocument.ConfigurationProfile"])
	}
	{
		path := validation.Join(p, "Declarations")
		present := len(x.Declarations) > 0
		_, _ = path, present
		c.Support(path, present, supportTable["EnrollmentSSODocument.Declarations"])
	}
}

// Validate checks x against the schema. With a non-zero target it also checks
// that every present key is supported on that OS version and enrollment context.
func (x *MachineInfo) Validate(t support.Target) error {
	c := validation.New(t)
	x.validate(c, "")
	return c.Err()
}

func (x *MachineInfo) validate(c *validation.Collector, p string) {
	{
		path := validation.Join(p, "UDID")
		present := x.UDID != ""
		_, _ = path, present
		c.Support(path, present, supportTable["MachineInfo.UDID"])
		c.Required(path, present)
	}
	{
		path := validation.Join(p, "SERIAL")
		present := x.SERIAL != ""
		_, _ = path, present
		c.Support(path, present, supportTable["MachineInfo.SERIAL"])
		c.Required(path, present)
	}
	{
		path := validation.Join(p, "PRODUCT")
		present := x.PRODUCT != ""
		_, _ = path, present
		c.Support(path, present, supportTable["MachineInfo.PRODUCT"])
		c.Required(path, present)
	}
	{
		path := validation.Join(p, "VERSION")
		present := x.VERSION != ""
		_, _ = path, present
		c.Support(path, present, supportTable["MachineInfo.VERSION"])
		c.Required(path, present)
	}
	{
		path := validation.Join(p, "OS_VERSION")
		present := x.OSVERSION != ""
		_, _ = path, present
		c.Support(path, present, supportTable["MachineInfo.OS_VERSION"])
		c.Required(path, present)
	}
	{
		path := validation.Join(p, "SUPPLEMENTAL_BUILD_VERSION")
		present := x.SUPPLEMENTALBUILDVERSION != nil
		_, _ = path, present
		c.Support(path, present, supportTable["MachineInfo.SUPPLEMENTAL_BUILD_VERSION"])
	}
	{
		path := validation.Join(p, "SUPPLEMENTAL_OS_VERSION_EXTRA")
		present := x.SUPPLEMENTALOSVERSIONEXTRA != nil
		_, _ = path, present
		c.Support(path, present, supportTable["MachineInfo.SUPPLEMENTAL_OS_VERSION_EXTRA"])
	}
	{
		path := validation.Join(p, "IMEI")
		present := x.IMEI != nil
		_, _ = path, present
		c.Support(path, present, supportTable["MachineInfo.IMEI"])
	}
	{
		path := validation.Join(p, "MEID")
		present := x.MEID != nil
		_, _ = path, present
		c.Support(path, present, supportTable["MachineInfo.MEID"])
	}
	{
		path := validation.Join(p, "LANGUAGE")
		present := x.LANGUAGE != nil
		_, _ = path, present
		c.Support(path, present, supportTable["MachineInfo.LANGUAGE"])
	}
	{
		path := validation.Join(p, "MDM_CAN_REQUEST_SOFTWARE_UPDATE")
		present := x.MDMCANREQUESTSOFTWAREUPDATE != nil
		_, _ = path, present
		c.Support(path, present, supportTable["MachineInfo.MDM_CAN_REQUEST_SOFTWARE_UPDATE"])
	}
	{
		path := validation.Join(p, "PAIRING_TOKEN")
		present := len(x.PAIRINGTOKEN) > 0
		_, _ = path, present
		c.Support(path, present, supportTable["MachineInfo.PAIRING_TOKEN"])
	}
	{
		path := validation.Join(p, "SOFTWARE_UPDATE_DEVICE_ID")
		present := x.SOFTWAREUPDATEDEVICEID != nil
		_, _ = path, present
		c.Support(path, present, supportTable["MachineInfo.SOFTWARE_UPDATE_DEVICE_ID"])
	}
	{
		path := validation.Join(p, "MDM_CAN_REQUEST_PSSO_CONFIG")
		present := x.MDMCANREQUESTPSSOCONFIG != nil
		_, _ = path, present
		c.Support(path, present, supportTable["MachineInfo.MDM_CAN_REQUEST_PSSO_CONFIG"])
	}
	{
		path := validation.Join(p, "MANDATORY_SOFTWARE_UPDATE_REQUIRED")
		present := x.MANDATORYSOFTWAREUPDATEREQUIRED != nil
		_, _ = path, present
		c.Support(path, present, supportTable["MachineInfo.MANDATORY_SOFTWARE_UPDATE_REQUIRED"])
	}
}

// Validate checks x against the schema. With a non-zero target it also checks
// that every present key is supported on that OS version and enrollment context.
func (x *ManifestURL) Validate(t support.Target) error {
	c := validation.New(t)
	x.validate(c, "")
	return c.Err()
}

func (x *ManifestURL) validate(c *validation.Collector, p string) {
	{
		path := validation.Join(p, "items")
		present := len(x.Items) > 0
		_, _ = path, present
		c.Support(path, present, supportTable["ManifestURL.items"])
		c.Required(path, present)
		for i := range x.Items {
			x.Items[i].validate(c, validation.Index(path, i))
		}
	}
}

func (x *ManifestURLItems) validate(c *validation.Collector, p string) {
	{
		path := validation.Join(p, "assets")
		present := len(x.Assets) > 0
		_, _ = path, present
		c.Support(path, present, supportTable["ManifestURL.items.items-item.assets"])
		c.Required(path, present)
		for i := range x.Assets {
			x.Assets[i].validate(c, validation.Index(path, i))
		}
	}
	{
		path := validation.Join(p, "metadata")
		present := true
		_, _ = path, present
		c.Support(path, present, supportTable["ManifestURL.items.items-item.metadata"])
		c.Required(path, present)
		if present {
			x.Metadata.validate(c, path)
		}
	}
}

func (x *ManifestURLItemsAssets) validate(c *validation.Collector, p string) {
	{
		path := validation.Join(p, "kind")
		present := x.Kind != ""
		_, _ = path, present
		c.Support(path, present, supportTable["ManifestURL.items.items-item.assets.assets-item.kind"])
		c.Required(path, present)
		if present {
			c.Enum(path, true, x.Kind, []any{"asset-pack-manifest", "display-image", "full-size-image", "software-package"})
		}
	}
	{
		path := validation.Join(p, "md5")
		present := x.Md5 != nil
		_, _ = path, present
		c.Support(path, present, supportTable["ManifestURL.items.items-item.assets.assets-item.md5"])
	}
	{
		path := validation.Join(p, "md5-size")
		present := x.Md5Size != nil
		_, _ = path, present
		c.Support(path, present, supportTable["ManifestURL.items.items-item.assets.assets-item.md5-size"])
	}
	{
		path := validation.Join(p, "md5s")
		present := len(x.Md5s) > 0
		_, _ = path, present
		c.Support(path, present, supportTable["ManifestURL.items.items-item.assets.assets-item.md5s"])
	}
	{
		path := validation.Join(p, "sha256")
		present := x.Sha256 != nil
		_, _ = path, present
		c.Support(path, present, supportTable["ManifestURL.items.items-item.assets.assets-item.sha256"])
	}
	{
		path := validation.Join(p, "sha256-size")
		present := x.Sha256Size != nil
		_, _ = path, present
		c.Support(path, present, supportTable["ManifestURL.items.items-item.assets.assets-item.sha256-size"])
	}
	{
		path := validation.Join(p, "sha256s")
		present := len(x.Sha256s) > 0
		_, _ = path, present
		c.Support(path, present, supportTable["ManifestURL.items.items-item.assets.assets-item.sha256s"])
	}
	{
		path := validation.Join(p, "url")
		present := x.Url != ""
		_, _ = path, present
		c.Support(path, present, supportTable["ManifestURL.items.items-item.assets.assets-item.url"])
		c.Required(path, present)
	}
	{
		path := validation.Join(p, "needs-shine")
		present := x.NeedsShine != nil
		_, _ = path, present
		c.Support(path, present, supportTable["ManifestURL.items.items-item.assets.assets-item.needs-shine"])
	}
}

func (x *ManifestURLItemsMetadata) validate(c *validation.Collector, p string) {
	{
		path := validation.Join(p, "bundle-identifier")
		present := x.BundleIdentifier != ""
		_, _ = path, present
		c.Support(path, present, supportTable["ManifestURL.items.items-item.metadata.bundle-identifier"])
		c.Required(path, present)
	}
	{
		path := validation.Join(p, "bundle-version")
		present := x.BundleVersion != nil
		_, _ = path, present
		c.Support(path, present, supportTable["ManifestURL.items.items-item.metadata.bundle-version"])
	}
	{
		path := validation.Join(p, "kind")
		present := x.Kind != ""
		_, _ = path, present
		c.Support(path, present, supportTable["ManifestURL.items.items-item.metadata.kind"])
		c.Required(path, present)
		if present {
			c.Enum(path, true, x.Kind, []any{"software"})
		}
	}
	{
		path := validation.Join(p, "sizeInBytes")
		present := x.SizeInBytes != nil
		_, _ = path, present
		c.Support(path, present, supportTable["ManifestURL.items.items-item.metadata.sizeInBytes"])
	}
	{
		path := validation.Join(p, "subtitle")
		present := x.Subtitle != nil
		_, _ = path, present
		c.Support(path, present, supportTable["ManifestURL.items.items-item.metadata.subtitle"])
	}
	{
		path := validation.Join(p, "title")
		present := x.Title != ""
		_, _ = path, present
		c.Support(path, present, supportTable["ManifestURL.items.items-item.metadata.title"])
		c.Required(path, present)
	}
	{
		path := validation.Join(p, "items")
		present := len(x.Items) > 0
		_, _ = path, present
		c.Support(path, present, supportTable["ManifestURL.items.items-item.metadata.items"])
		for i := range x.Items {
			x.Items[i].validate(c, validation.Index(path, i))
		}
	}
}

func (x *ManifestURLItemsMetadataItems) validate(c *validation.Collector, p string) {
	{
		path := validation.Join(p, "bundle-identifier")
		present := x.BundleIdentifier != nil
		_, _ = path, present
		c.Support(path, present, supportTable["ManifestURL.items.items-item.metadata.items.metadata-items-item.bundle-identifier"])
	}
	{
		path := validation.Join(p, "bundle-version")
		present := x.BundleVersion != nil
		_, _ = path, present
		c.Support(path, present, supportTable["ManifestURL.items.items-item.metadata.items.metadata-items-item.bundle-version"])
	}
}

// Validate checks x against the schema. With a non-zero target it also checks
// that every present key is supported on that OS version and enrollment context.
func (x *PasswordHash) Validate(t support.Target) error {
	c := validation.New(t)
	x.validate(c, "")
	return c.Err()
}

func (x *PasswordHash) validate(c *validation.Collector, p string) {
	{
		path := validation.Join(p, "SALTED-SHA512-PBKDF2")
		present := true
		_, _ = path, present
		c.Support(path, present, supportTable["PasswordHash.SALTED-SHA512-PBKDF2"])
		c.Required(path, present)
		if present {
			x.SALTEDSHA512PBKDF2.validate(c, path)
		}
	}
}

func (x *PasswordHashSALTEDSHA512PBKDF2) validate(c *validation.Collector, p string) {
	{
		path := validation.Join(p, "entropy")
		present := len(x.Entropy) > 0
		_, _ = path, present
		c.Support(path, present, supportTable["PasswordHash.SALTED-SHA512-PBKDF2.entropy"])
		c.Required(path, present)
	}
	{
		path := validation.Join(p, "iterations")
		present := true
		_, _ = path, present
		c.Support(path, present, supportTable["PasswordHash.SALTED-SHA512-PBKDF2.iterations"])
		c.Required(path, present)
	}
	{
		path := validation.Join(p, "salt")
		present := len(x.Salt) > 0
		_, _ = path, present
		c.Support(path, present, supportTable["PasswordHash.SALTED-SHA512-PBKDF2.salt"])
		c.Required(path, present)
	}
}

// Validate checks x against the schema. With a non-zero target it also checks
// that every present key is supported on that OS version and enrollment context.
func (x *SkipKeys) Validate(t support.Target) error {
	c := validation.New(t)
	x.validate(c, "")
	return c.Err()
}

func (x *SkipKeys) validate(c *validation.Collector, p string) {
	{
		path := validation.Join(p, "Accessibility")
		present := x.Accessibility != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.Accessibility"])
	}
	{
		path := validation.Join(p, "ActionButton")
		present := x.ActionButton != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.ActionButton"])
	}
	{
		path := validation.Join(p, "Android")
		present := x.Android != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.Android"])
	}
	{
		path := validation.Join(p, "Appearance")
		present := x.Appearance != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.Appearance"])
	}
	{
		path := validation.Join(p, "AppleID")
		present := x.AppleID != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.AppleID"])
	}
	{
		path := validation.Join(p, "AppStore")
		present := x.AppStore != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.AppStore"])
	}
	{
		path := validation.Join(p, "Biometric")
		present := x.Biometric != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.Biometric"])
	}
	{
		path := validation.Join(p, "CameraButton")
		present := x.CameraButton != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.CameraButton"])
	}
	{
		path := validation.Join(p, "DeviceToDeviceMigration")
		present := x.DeviceToDeviceMigration != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.DeviceToDeviceMigration"])
	}
	{
		path := validation.Join(p, "Diagnostics")
		present := x.Diagnostics != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.Diagnostics"])
	}
	{
		path := validation.Join(p, "DisplayTone")
		present := x.DisplayTone != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.DisplayTone"])
	}
	{
		path := validation.Join(p, "EnableLockdownMode")
		present := x.EnableLockdownMode != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.EnableLockdownMode"])
	}
	{
		path := validation.Join(p, "FileVault")
		present := x.FileVault != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.FileVault"])
	}
	{
		path := validation.Join(p, "HomeButtonSensitivity")
		present := x.HomeButtonSensitivity != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.HomeButtonSensitivity"])
	}
	{
		path := validation.Join(p, "iCloudDiagnostics")
		present := x.ICloudDiagnostics != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.iCloudDiagnostics"])
	}
	{
		path := validation.Join(p, "iCloudStorage")
		present := x.ICloudStorage != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.iCloudStorage"])
	}
	{
		path := validation.Join(p, "iMessageAndFaceTime")
		present := x.IMessageAndFaceTime != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.iMessageAndFaceTime"])
	}
	{
		path := validation.Join(p, "Intelligence")
		present := x.Intelligence != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.Intelligence"])
	}
	{
		path := validation.Join(p, "Keyboard")
		present := x.Keyboard != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.Keyboard"])
	}
	{
		path := validation.Join(p, "Location")
		present := x.Location != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.Location"])
	}
	{
		path := validation.Join(p, "MessagingActivationUsingPhoneNumber")
		present := x.MessagingActivationUsingPhoneNumber != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.MessagingActivationUsingPhoneNumber"])
	}
	{
		path := validation.Join(p, "Multitasking")
		present := x.Multitasking != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.Multitasking"])
	}
	{
		path := validation.Join(p, "OnBoarding")
		present := x.OnBoarding != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.OnBoarding"])
	}
	{
		path := validation.Join(p, "OSShowcase")
		present := x.OSShowcase != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.OSShowcase"])
	}
	{
		path := validation.Join(p, "Passcode")
		present := x.Passcode != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.Passcode"])
	}
	{
		path := validation.Join(p, "Payment")
		present := x.Payment != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.Payment"])
	}
	{
		path := validation.Join(p, "Privacy")
		present := x.Privacy != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.Privacy"])
	}
	{
		path := validation.Join(p, "Restore")
		present := x.Restore != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.Restore"])
	}
	{
		path := validation.Join(p, "RestoreCompleted")
		present := x.RestoreCompleted != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.RestoreCompleted"])
	}
	{
		path := validation.Join(p, "ScreenSaver")
		present := x.ScreenSaver != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.ScreenSaver"])
	}
	{
		path := validation.Join(p, "Safety")
		present := x.Safety != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.Safety"])
	}
	{
		path := validation.Join(p, "SafetyAndHandling")
		present := x.SafetyAndHandling != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.SafetyAndHandling"])
	}
	{
		path := validation.Join(p, "ScreenTime")
		present := x.ScreenTime != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.ScreenTime"])
	}
	{
		path := validation.Join(p, "SIMSetup")
		present := x.SIMSetup != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.SIMSetup"])
	}
	{
		path := validation.Join(p, "Siri")
		present := x.Siri != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.Siri"])
	}
	{
		path := validation.Join(p, "SoftwareUpdate")
		present := x.SoftwareUpdate != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.SoftwareUpdate"])
	}
	{
		path := validation.Join(p, "SpokenLanguage")
		present := x.SpokenLanguage != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.SpokenLanguage"])
	}
	{
		path := validation.Join(p, "TapToSetup")
		present := x.TapToSetup != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.TapToSetup"])
	}
	{
		path := validation.Join(p, "TermsOfAddress")
		present := x.TermsOfAddress != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.TermsOfAddress"])
	}
	{
		path := validation.Join(p, "Tips")
		present := x.Tips != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.Tips"])
	}
	{
		path := validation.Join(p, "TOS")
		present := x.TOS != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.TOS"])
	}
	{
		path := validation.Join(p, "TVHomeScreenSync")
		present := x.TVHomeScreenSync != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.TVHomeScreenSync"])
	}
	{
		path := validation.Join(p, "TVProviderSignIn")
		present := x.TVProviderSignIn != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.TVProviderSignIn"])
	}
	{
		path := validation.Join(p, "TVRoom")
		present := x.TVRoom != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.TVRoom"])
	}
	{
		path := validation.Join(p, "UnlockWithWatch")
		present := x.UnlockWithWatch != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.UnlockWithWatch"])
	}
	{
		path := validation.Join(p, "UpdateCompleted")
		present := x.UpdateCompleted != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.UpdateCompleted"])
	}
	{
		path := validation.Join(p, "Wallpaper")
		present := x.Wallpaper != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.Wallpaper"])
	}
	{
		path := validation.Join(p, "WatchMigration")
		present := x.WatchMigration != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.WatchMigration"])
	}
	{
		path := validation.Join(p, "WebContentFiltering")
		present := x.WebContentFiltering != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.WebContentFiltering"])
	}
	{
		path := validation.Join(p, "Welcome")
		present := x.Welcome != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.Welcome"])
	}
	{
		path := validation.Join(p, "Zoom")
		present := x.Zoom != nil
		_, _ = path, present
		c.Support(path, present, supportTable["SkipKeys.Zoom"])
	}
}
