// Code generated by schemagen; DO NOT EDIT.
// Source: apple/device-management@b0180185a5e4077070710033341b71d0cbe1a18a

package ddm

import (
	"github.com/deploymenttheory/go-apple-dm/devicemanagement/schema/support"
)

// Declaration is implemented by every top-level type in this package.
type Declaration interface {
	// DeclarationTypeName returns the wire identifier from Apple's schema.
	DeclarationTypeName() string
	// SchemaPath returns the schema file the type was generated from.
	SchemaPath() string
	// Validate checks the value against the schema for the target.
	Validate(t support.Target) error
}

// Kind classifies a declaration.
type Kind string

// Declaration kinds.
const (
	KindActivation    Kind = "activation"
	KindAsset         Kind = "asset"
	KindConfiguration Kind = "configuration"
	KindManagement    Kind = "management"
	KindCredential    Kind = "credential"
	KindBase          Kind = "base"
)

// Entry describes one schema in the Registry.
type Entry struct {
	// ID is the wire identifier: RequestType, MessageType, PayloadType,
	// DeclarationType, StatusItemType, error code, or type name.
	ID string
	// Schema is the YAML path in apple/device-management.
	Schema string
	Title  string
	Kind   Kind
	// New returns a zero value of the type as Declaration.
	New func() Declaration
	// NewResponse returns a zero response value, or nil when the schema
	// defines no response keys.
	NewResponse func() any
}

// Wire identifiers.
const (
	// DeclarationTypeActivationSimple: Activation:Simple
	DeclarationTypeActivationSimple = "com.apple.activation.simple"
	// DeclarationTypeAssetCredentialACME: Asset:Credential ACME
	DeclarationTypeAssetCredentialACME = "com.apple.asset.credential.acme" // #nosec G101 -- Apple wire identifier, not a credential
	// DeclarationTypeAssetCredentialCertificate: Asset:Credential Certificate
	DeclarationTypeAssetCredentialCertificate = "com.apple.asset.credential.certificate" // #nosec G101 -- Apple wire identifier, not a credential
	// DeclarationTypeAssetCredentialIdentity: Asset:Credential Identity
	DeclarationTypeAssetCredentialIdentity = "com.apple.asset.credential.identity" // #nosec G101 -- Apple wire identifier, not a credential
	// DeclarationTypeAssetCredentialSCEP: Asset:Credential SCEP
	DeclarationTypeAssetCredentialSCEP = "com.apple.asset.credential.scep" // #nosec G101 -- Apple wire identifier, not a credential
	// DeclarationTypeAssetCredentialUserNameAndPassword: Asset:Credential User Name and Password
	DeclarationTypeAssetCredentialUserNameAndPassword = "com.apple.asset.credential.userpassword" // #nosec G101 -- Apple wire identifier, not a credential
	// CredentialTypeACMECredential: ACME Credential
	CredentialTypeACMECredential = "com.apple.credential.acme" // #nosec G101 -- Apple wire identifier, not a credential
	// CredentialTypeIdentityCredential: Identity Credential
	CredentialTypeIdentityCredential = "com.apple.credential.identity" // #nosec G101 -- Apple wire identifier, not a credential
	// CredentialTypeSCEPCredential: SCEP Credential
	CredentialTypeSCEPCredential = "com.apple.credential.scep" // #nosec G101 -- Apple wire identifier, not a credential
	// CredentialTypeUserNameAndPasswordCredential: User Name and Password Credential
	CredentialTypeUserNameAndPasswordCredential = "com.apple.credential.usernameandpassword" // #nosec G101 -- Apple wire identifier, not a credential
	// DeclarationTypeAssetData: Asset:Data
	DeclarationTypeAssetData = "com.apple.asset.data"
	// DeclarationTypeAssetUserIdentity: Asset:User Identity
	DeclarationTypeAssetUserIdentity = "com.apple.asset.useridentity"
	// DeclarationTypeAccessibilitySettings: Accessibility Settings
	DeclarationTypeAccessibilitySettings = "com.apple.configuration.accessibility.settings"
	// DeclarationTypeAccountCalDAV: Account:CalDAV
	DeclarationTypeAccountCalDAV = "com.apple.configuration.account.caldav"
	// DeclarationTypeAccountCardDAV: Account:CardDAV
	DeclarationTypeAccountCardDAV = "com.apple.configuration.account.carddav"
	// DeclarationTypeAccountExchange: Account:Exchange
	DeclarationTypeAccountExchange = "com.apple.configuration.account.exchange"
	// DeclarationTypeAccountGoogle: Account:Google
	DeclarationTypeAccountGoogle = "com.apple.configuration.account.google"
	// DeclarationTypeAccountLDAP: Account:LDAP
	DeclarationTypeAccountLDAP = "com.apple.configuration.account.ldap"
	// DeclarationTypeAccountMail: Account:Mail
	DeclarationTypeAccountMail = "com.apple.configuration.account.mail"
	// DeclarationTypeAccountSubscribedCalendar: Account:Subscribed Calendar
	DeclarationTypeAccountSubscribedCalendar = "com.apple.configuration.account.subscribed-calendar"
	// DeclarationTypeAppManaged: App:Managed
	DeclarationTypeAppManaged = "com.apple.configuration.app.managed"
	// DeclarationTypeAppSettings: App:Settings
	DeclarationTypeAppSettings = "com.apple.configuration.app.settings"
	// DeclarationTypeAudioAccessorySettings: Audio Accessory:Settings
	DeclarationTypeAudioAccessorySettings = "com.apple.configuration.audio-accessory.settings"
	// DeclarationTypeContentCaching: Content Caching
	DeclarationTypeContentCaching = "com.apple.configuration.content-cache.settings"
	// DeclarationTypeDiskManagementSettings: Disk Management:Settings
	DeclarationTypeDiskManagementSettings = "com.apple.configuration.diskmanagement.settings"
	// DeclarationTypeExtensibleSSO: Extensible SSO
	DeclarationTypeExtensibleSSO = "com.apple.configuration.extensible-sso"
	// DeclarationTypeExternalIntelligenceSettings: External Intelligence Settings
	DeclarationTypeExternalIntelligenceSettings = "com.apple.configuration.external-intelligence.settings"
	// DeclarationTypeIntelligenceSettings: Intelligence Settings
	DeclarationTypeIntelligenceSettings = "com.apple.configuration.intelligence.settings"
	// DeclarationTypeKeyboardSettings: Keyboard Settings
	DeclarationTypeKeyboardSettings = "com.apple.configuration.keyboard.settings"
	// DeclarationTypeLegacyInteractiveProfile: Legacy Interactive Profile
	DeclarationTypeLegacyInteractiveProfile = "com.apple.configuration.legacy.interactive"
	// DeclarationTypeLegacyProfile: Legacy Profile
	DeclarationTypeLegacyProfile = "com.apple.configuration.legacy"
	// DeclarationTypeManagementStatusSubscriptions: Management:Status Subscriptions
	DeclarationTypeManagementStatusSubscriptions = "com.apple.configuration.management.status-subscriptions"
	// DeclarationTypeManagementTest: Management:Test
	DeclarationTypeManagementTest = "com.apple.configuration.management.test"
	// DeclarationTypeMathSettings: Math Settings
	DeclarationTypeMathSettings = "com.apple.configuration.math.settings"
	// DeclarationTypeMigrationAssistantSettings: Migration Assistant Settings
	DeclarationTypeMigrationAssistantSettings = "com.apple.configuration.migration-assistant.settings"
	// DeclarationTypeNetworkDNSProxy: Network:DNS Proxy
	DeclarationTypeNetworkDNSProxy = "com.apple.configuration.network.dns-proxy"
	// DeclarationTypeNetworkDNSSettings: Network:DNS Settings
	DeclarationTypeNetworkDNSSettings = "com.apple.configuration.network.dns-settings"
	// DeclarationTypeNetworkRelay: Network:Relay
	DeclarationTypeNetworkRelay = "com.apple.configuration.network.relay"
	// DeclarationTypeNetworkVPNAlwaysOn: Network:VPN:AlwaysOn
	DeclarationTypeNetworkVPNAlwaysOn = "com.apple.configuration.network.vpn.always-on"
	// DeclarationTypeNetworkVPNIKEV2: Network:VPN:IKEV2
	DeclarationTypeNetworkVPNIKEV2 = "com.apple.configuration.network.vpn.ikev2"
	// DeclarationTypeNetworkVPNIPSec: Network:VPN:IPSec
	DeclarationTypeNetworkVPNIPSec = "com.apple.configuration.network.vpn.ipsec"
	// DeclarationTypeNetworkVPNVPNPlugin: Network:VPN:VPN Plugin
	DeclarationTypeNetworkVPNVPNPlugin = "com.apple.configuration.network.vpn.vpn-plugin"
	// DeclarationTypePackage: Package
	DeclarationTypePackage = "com.apple.configuration.package"
	// DeclarationTypePasscodeSettings: Passcode:Settings
	DeclarationTypePasscodeSettings = "com.apple.configuration.passcode.settings" // #nosec G101 -- Apple wire identifier, not a credential
	// DeclarationTypeSafariBookmarks: Safari:Bookmarks
	DeclarationTypeSafariBookmarks = "com.apple.configuration.safari.bookmarks"
	// DeclarationTypeSafariExtensionSettings: Safari:Extension Settings
	DeclarationTypeSafariExtensionSettings = "com.apple.configuration.safari.extensions.settings"
	// DeclarationTypeSafariSettings: Safari:Settings
	DeclarationTypeSafariSettings = "com.apple.configuration.safari.settings"
	// DeclarationTypeScreenSharingConnectionGroup: Screen Sharing:Connection Group
	DeclarationTypeScreenSharingConnectionGroup = "com.apple.configuration.screensharing.connection.group"
	// DeclarationTypeScreenSharingConnection: Screen Sharing:Connection
	DeclarationTypeScreenSharingConnection = "com.apple.configuration.screensharing.connection"
	// DeclarationTypeScreenSharingHostSettings: Screen Sharing:Host Settings
	DeclarationTypeScreenSharingHostSettings = "com.apple.configuration.screensharing.host.settings"
	// DeclarationTypeSecurityCertificate: Security:Certificate
	DeclarationTypeSecurityCertificate = "com.apple.configuration.security.certificate"
	// DeclarationTypeSecurityIdentity: Security:Identity
	DeclarationTypeSecurityIdentity = "com.apple.configuration.security.identity"
	// DeclarationTypeSecurityPasskeyAttestation: Security:Passkey:Attestation
	DeclarationTypeSecurityPasskeyAttestation = "com.apple.configuration.security.passkey.attestation" // #nosec G101 -- Apple wire identifier, not a credential
	// DeclarationTypeServicesBackgroundTasks: Services Background Tasks
	DeclarationTypeServicesBackgroundTasks = "com.apple.configuration.services.background-tasks"
	// DeclarationTypeServicesConfigurationFiles: Services Configuration Files
	DeclarationTypeServicesConfigurationFiles = "com.apple.configuration.services.configuration-files"
	// DeclarationTypeSiriSettings: Siri Settings
	DeclarationTypeSiriSettings = "com.apple.configuration.siri.settings"
	// DeclarationTypeSoftwareUpdateEnforcementSpecific: Software Update:Enforcement:Specific
	DeclarationTypeSoftwareUpdateEnforcementSpecific = "com.apple.configuration.softwareupdate.enforcement.specific"
	// DeclarationTypeSoftwareUpdateSettings: Software Update:Settings
	DeclarationTypeSoftwareUpdateSettings = "com.apple.configuration.softwareupdate.settings"
	// DeclarationTypeWatchEnrollment: Watch:Enrollment
	DeclarationTypeWatchEnrollment = "com.apple.configuration.watch.enrollment"
	// DeclarationTypeWebContentFilterPlugin: WebContentFilter:Plugin
	DeclarationTypeWebContentFilterPlugin = "com.apple.configuration.webcontent-filter.plugin"
	// DeclarationTypeManagementOrganizationInformation: Management:Organization Information
	DeclarationTypeManagementOrganizationInformation = "com.apple.management.organization-info"
	// DeclarationTypeManagementProperties: Management:Properties
	DeclarationTypeManagementProperties = "com.apple.management.properties"
	// DeclarationTypeManagementServerCapabilities: Management:Server Capabilities
	DeclarationTypeManagementServerCapabilities = "com.apple.management.server-capabilities"
)

// Registry maps Go type names to constructors, one entry per schema file.
// Several schemas may share a wire identifier (for example six profile
// payloads use com.apple.MCX), so look up by identifier with ByID.
var Registry = map[string]Entry{
	"ACMECredential":                     {ID: "com.apple.credential.acme", Schema: "declarative/declarations/assets/credentials/acme.yaml", Title: "ACME Credential", Kind: KindCredential, New: func() Declaration { return new(ACMECredential) }},
	"AccessibilitySettings":              {ID: "com.apple.configuration.accessibility.settings", Schema: "declarative/declarations/configurations/accessibility.settings.yaml", Title: "Accessibility Settings", Kind: KindConfiguration, New: func() Declaration { return new(AccessibilitySettings) }},
	"AccountCalDAV":                      {ID: "com.apple.configuration.account.caldav", Schema: "declarative/declarations/configurations/account.caldav.yaml", Title: "Account:CalDAV", Kind: KindConfiguration, New: func() Declaration { return new(AccountCalDAV) }},
	"AccountCardDAV":                     {ID: "com.apple.configuration.account.carddav", Schema: "declarative/declarations/configurations/account.carddav.yaml", Title: "Account:CardDAV", Kind: KindConfiguration, New: func() Declaration { return new(AccountCardDAV) }},
	"AccountExchange":                    {ID: "com.apple.configuration.account.exchange", Schema: "declarative/declarations/configurations/account.exchange.yaml", Title: "Account:Exchange", Kind: KindConfiguration, New: func() Declaration { return new(AccountExchange) }},
	"AccountGoogle":                      {ID: "com.apple.configuration.account.google", Schema: "declarative/declarations/configurations/account.google.yaml", Title: "Account:Google", Kind: KindConfiguration, New: func() Declaration { return new(AccountGoogle) }},
	"AccountLDAP":                        {ID: "com.apple.configuration.account.ldap", Schema: "declarative/declarations/configurations/account.ldap.yaml", Title: "Account:LDAP", Kind: KindConfiguration, New: func() Declaration { return new(AccountLDAP) }},
	"AccountMail":                        {ID: "com.apple.configuration.account.mail", Schema: "declarative/declarations/configurations/account.mail.yaml", Title: "Account:Mail", Kind: KindConfiguration, New: func() Declaration { return new(AccountMail) }},
	"AccountSubscribedCalendar":          {ID: "com.apple.configuration.account.subscribed-calendar", Schema: "declarative/declarations/configurations/account.subscribed-calendar.yaml", Title: "Account:Subscribed Calendar", Kind: KindConfiguration, New: func() Declaration { return new(AccountSubscribedCalendar) }},
	"ActivationSimple":                   {ID: "com.apple.activation.simple", Schema: "declarative/declarations/activations/simple.yaml", Title: "Activation:Simple", Kind: KindActivation, New: func() Declaration { return new(ActivationSimple) }},
	"AppManaged":                         {ID: "com.apple.configuration.app.managed", Schema: "declarative/declarations/configurations/app.managed.yaml", Title: "App:Managed", Kind: KindConfiguration, New: func() Declaration { return new(AppManaged) }},
	"AppSettings":                        {ID: "com.apple.configuration.app.settings", Schema: "declarative/declarations/configurations/app.settings.yaml", Title: "App:Settings", Kind: KindConfiguration, New: func() Declaration { return new(AppSettings) }},
	"AssetCredentialACME":                {ID: "com.apple.asset.credential.acme", Schema: "declarative/declarations/assets/credential.acme.yaml", Title: "Asset:Credential ACME", Kind: KindAsset, New: func() Declaration { return new(AssetCredentialACME) }},
	"AssetCredentialCertificate":         {ID: "com.apple.asset.credential.certificate", Schema: "declarative/declarations/assets/credential.certificate.yaml", Title: "Asset:Credential Certificate", Kind: KindAsset, New: func() Declaration { return new(AssetCredentialCertificate) }},
	"AssetCredentialIdentity":            {ID: "com.apple.asset.credential.identity", Schema: "declarative/declarations/assets/credential.identity.yaml", Title: "Asset:Credential Identity", Kind: KindAsset, New: func() Declaration { return new(AssetCredentialIdentity) }},
	"AssetCredentialSCEP":                {ID: "com.apple.asset.credential.scep", Schema: "declarative/declarations/assets/credential.scep.yaml", Title: "Asset:Credential SCEP", Kind: KindAsset, New: func() Declaration { return new(AssetCredentialSCEP) }},
	"AssetCredentialUserNameAndPassword": {ID: "com.apple.asset.credential.userpassword", Schema: "declarative/declarations/assets/credential.userpassword.yaml", Title: "Asset:Credential User Name and Password", Kind: KindAsset, New: func() Declaration { return new(AssetCredentialUserNameAndPassword) }},
	"AssetData":                          {ID: "com.apple.asset.data", Schema: "declarative/declarations/assets/data.yaml", Title: "Asset:Data", Kind: KindAsset, New: func() Declaration { return new(AssetData) }},
	"AssetUserIdentity":                  {ID: "com.apple.asset.useridentity", Schema: "declarative/declarations/assets/useridentity.yaml", Title: "Asset:User Identity", Kind: KindAsset, New: func() Declaration { return new(AssetUserIdentity) }},
	"AudioAccessorySettings":             {ID: "com.apple.configuration.audio-accessory.settings", Schema: "declarative/declarations/configurations/audio-accessory.settings.yaml", Title: "Audio Accessory:Settings", Kind: KindConfiguration, New: func() Declaration { return new(AudioAccessorySettings) }},
	"ContentCaching":                     {ID: "com.apple.configuration.content-cache.settings", Schema: "declarative/declarations/configurations/content-cache.settings.yaml", Title: "Content Caching", Kind: KindConfiguration, New: func() Declaration { return new(ContentCaching) }},
	"DiskManagementSettings":             {ID: "com.apple.configuration.diskmanagement.settings", Schema: "declarative/declarations/configurations/diskmanagement.settings.yaml", Title: "Disk Management:Settings", Kind: KindConfiguration, New: func() Declaration { return new(DiskManagementSettings) }},
	"ExtensibleSSO":                      {ID: "com.apple.configuration.extensible-sso", Schema: "declarative/declarations/configurations/extensible-sso.yaml", Title: "Extensible SSO", Kind: KindConfiguration, New: func() Declaration { return new(ExtensibleSSO) }},
	"ExternalIntelligenceSettings":       {ID: "com.apple.configuration.external-intelligence.settings", Schema: "declarative/declarations/configurations/external-intelligence.settings.yaml", Title: "External Intelligence Settings", Kind: KindConfiguration, New: func() Declaration { return new(ExternalIntelligenceSettings) }},
	"IdentityCredential":                 {ID: "com.apple.credential.identity", Schema: "declarative/declarations/assets/credentials/identity.yaml", Title: "Identity Credential", Kind: KindCredential, New: func() Declaration { return new(IdentityCredential) }},
	"IntelligenceSettings":               {ID: "com.apple.configuration.intelligence.settings", Schema: "declarative/declarations/configurations/intelligence.settings.yaml", Title: "Intelligence Settings", Kind: KindConfiguration, New: func() Declaration { return new(IntelligenceSettings) }},
	"KeyboardSettings":                   {ID: "com.apple.configuration.keyboard.settings", Schema: "declarative/declarations/configurations/keyboard.settings.yaml", Title: "Keyboard Settings", Kind: KindConfiguration, New: func() Declaration { return new(KeyboardSettings) }},
	"LegacyInteractiveProfile":           {ID: "com.apple.configuration.legacy.interactive", Schema: "declarative/declarations/configurations/legacy.interactive.yaml", Title: "Legacy Interactive Profile", Kind: KindConfiguration, New: func() Declaration { return new(LegacyInteractiveProfile) }},
	"LegacyProfile":                      {ID: "com.apple.configuration.legacy", Schema: "declarative/declarations/configurations/legacy.yaml", Title: "Legacy Profile", Kind: KindConfiguration, New: func() Declaration { return new(LegacyProfile) }},
	"ManagementOrganizationInformation":  {ID: "com.apple.management.organization-info", Schema: "declarative/declarations/management/organization-info.yaml", Title: "Management:Organization Information", Kind: KindManagement, New: func() Declaration { return new(ManagementOrganizationInformation) }},
	"ManagementProperties":               {ID: "com.apple.management.properties", Schema: "declarative/declarations/management/properties.yaml", Title: "Management:Properties", Kind: KindManagement, New: func() Declaration { return new(ManagementProperties) }},
	"ManagementServerCapabilities":       {ID: "com.apple.management.server-capabilities", Schema: "declarative/declarations/management/server-capabilities.yaml", Title: "Management:Server Capabilities", Kind: KindManagement, New: func() Declaration { return new(ManagementServerCapabilities) }},
	"ManagementStatusSubscriptions":      {ID: "com.apple.configuration.management.status-subscriptions", Schema: "declarative/declarations/configurations/management.status-subscriptions.yaml", Title: "Management:Status Subscriptions", Kind: KindConfiguration, New: func() Declaration { return new(ManagementStatusSubscriptions) }},
	"ManagementTest":                     {ID: "com.apple.configuration.management.test", Schema: "declarative/declarations/configurations/management.test.yaml", Title: "Management:Test", Kind: KindConfiguration, New: func() Declaration { return new(ManagementTest) }},
	"MathSettings":                       {ID: "com.apple.configuration.math.settings", Schema: "declarative/declarations/configurations/math.settings.yaml", Title: "Math Settings", Kind: KindConfiguration, New: func() Declaration { return new(MathSettings) }},
	"MigrationAssistantSettings":         {ID: "com.apple.configuration.migration-assistant.settings", Schema: "declarative/declarations/configurations/migration-assistant.settings.yaml", Title: "Migration Assistant Settings", Kind: KindConfiguration, New: func() Declaration { return new(MigrationAssistantSettings) }},
	"NetworkDNSProxy":                    {ID: "com.apple.configuration.network.dns-proxy", Schema: "declarative/declarations/configurations/network.dns-proxy.yaml", Title: "Network:DNS Proxy", Kind: KindConfiguration, New: func() Declaration { return new(NetworkDNSProxy) }},
	"NetworkDNSSettings":                 {ID: "com.apple.configuration.network.dns-settings", Schema: "declarative/declarations/configurations/network.dns-settings.yaml", Title: "Network:DNS Settings", Kind: KindConfiguration, New: func() Declaration { return new(NetworkDNSSettings) }},
	"NetworkRelay":                       {ID: "com.apple.configuration.network.relay", Schema: "declarative/declarations/configurations/network.relay.yaml", Title: "Network:Relay", Kind: KindConfiguration, New: func() Declaration { return new(NetworkRelay) }},
	"NetworkVPNAlwaysOn":                 {ID: "com.apple.configuration.network.vpn.always-on", Schema: "declarative/declarations/configurations/network.vpn.always-on.yaml", Title: "Network:VPN:AlwaysOn", Kind: KindConfiguration, New: func() Declaration { return new(NetworkVPNAlwaysOn) }},
	"NetworkVPNIKEV2":                    {ID: "com.apple.configuration.network.vpn.ikev2", Schema: "declarative/declarations/configurations/network.vpn.ikev2.yaml", Title: "Network:VPN:IKEV2", Kind: KindConfiguration, New: func() Declaration { return new(NetworkVPNIKEV2) }},
	"NetworkVPNIPSec":                    {ID: "com.apple.configuration.network.vpn.ipsec", Schema: "declarative/declarations/configurations/network.vpn.ipsec.yaml", Title: "Network:VPN:IPSec", Kind: KindConfiguration, New: func() Declaration { return new(NetworkVPNIPSec) }},
	"NetworkVPNVPNPlugin":                {ID: "com.apple.configuration.network.vpn.vpn-plugin", Schema: "declarative/declarations/configurations/network.vpn.vpn-plugin.yaml", Title: "Network:VPN:VPN Plugin", Kind: KindConfiguration, New: func() Declaration { return new(NetworkVPNVPNPlugin) }},
	"Package":                            {ID: "com.apple.configuration.package", Schema: "declarative/declarations/configurations/package.yaml", Title: "Package", Kind: KindConfiguration, New: func() Declaration { return new(Package) }},
	"PasscodeSettings":                   {ID: "com.apple.configuration.passcode.settings", Schema: "declarative/declarations/configurations/passcode.settings.yaml", Title: "Passcode:Settings", Kind: KindConfiguration, New: func() Declaration { return new(PasscodeSettings) }},
	"SCEPCredential":                     {ID: "com.apple.credential.scep", Schema: "declarative/declarations/assets/credentials/scep.yaml", Title: "SCEP Credential", Kind: KindCredential, New: func() Declaration { return new(SCEPCredential) }},
	"SafariBookmarks":                    {ID: "com.apple.configuration.safari.bookmarks", Schema: "declarative/declarations/configurations/safari.bookmarks.yaml", Title: "Safari:Bookmarks", Kind: KindConfiguration, New: func() Declaration { return new(SafariBookmarks) }},
	"SafariExtensionSettings":            {ID: "com.apple.configuration.safari.extensions.settings", Schema: "declarative/declarations/configurations/safari.extensions.settings.yaml", Title: "Safari:Extension Settings", Kind: KindConfiguration, New: func() Declaration { return new(SafariExtensionSettings) }},
	"SafariSettings":                     {ID: "com.apple.configuration.safari.settings", Schema: "declarative/declarations/configurations/safari.settings.yaml", Title: "Safari:Settings", Kind: KindConfiguration, New: func() Declaration { return new(SafariSettings) }},
	"ScreenSharingConnection":            {ID: "com.apple.configuration.screensharing.connection", Schema: "declarative/declarations/configurations/screensharing.connection.yaml", Title: "Screen Sharing:Connection", Kind: KindConfiguration, New: func() Declaration { return new(ScreenSharingConnection) }},
	"ScreenSharingConnectionGroup":       {ID: "com.apple.configuration.screensharing.connection.group", Schema: "declarative/declarations/configurations/screensharing.connection.group.yaml", Title: "Screen Sharing:Connection Group", Kind: KindConfiguration, New: func() Declaration { return new(ScreenSharingConnectionGroup) }},
	"ScreenSharingHostSettings":          {ID: "com.apple.configuration.screensharing.host.settings", Schema: "declarative/declarations/configurations/screensharing.host.settings.yaml", Title: "Screen Sharing:Host Settings", Kind: KindConfiguration, New: func() Declaration { return new(ScreenSharingHostSettings) }},
	"SecurityCertificate":                {ID: "com.apple.configuration.security.certificate", Schema: "declarative/declarations/configurations/security.certificate.yaml", Title: "Security:Certificate", Kind: KindConfiguration, New: func() Declaration { return new(SecurityCertificate) }},
	"SecurityIdentity":                   {ID: "com.apple.configuration.security.identity", Schema: "declarative/declarations/configurations/security.identity.yaml", Title: "Security:Identity", Kind: KindConfiguration, New: func() Declaration { return new(SecurityIdentity) }},
	"SecurityPasskeyAttestation":         {ID: "com.apple.configuration.security.passkey.attestation", Schema: "declarative/declarations/configurations/security.passkey.attestation.yaml", Title: "Security:Passkey:Attestation", Kind: KindConfiguration, New: func() Declaration { return new(SecurityPasskeyAttestation) }},
	"ServicesBackgroundTasks":            {ID: "com.apple.configuration.services.background-tasks", Schema: "declarative/declarations/configurations/services.background-tasks.yaml", Title: "Services Background Tasks", Kind: KindConfiguration, New: func() Declaration { return new(ServicesBackgroundTasks) }},
	"ServicesConfigurationFiles":         {ID: "com.apple.configuration.services.configuration-files", Schema: "declarative/declarations/configurations/services.configuration-files.yaml", Title: "Services Configuration Files", Kind: KindConfiguration, New: func() Declaration { return new(ServicesConfigurationFiles) }},
	"SiriSettings":                       {ID: "com.apple.configuration.siri.settings", Schema: "declarative/declarations/configurations/siri.settings.yaml", Title: "Siri Settings", Kind: KindConfiguration, New: func() Declaration { return new(SiriSettings) }},
	"SoftwareUpdateEnforcementSpecific":  {ID: "com.apple.configuration.softwareupdate.enforcement.specific", Schema: "declarative/declarations/configurations/softwareupdate.enforcement.specific.yaml", Title: "Software Update:Enforcement:Specific", Kind: KindConfiguration, New: func() Declaration { return new(SoftwareUpdateEnforcementSpecific) }},
	"SoftwareUpdateSettings":             {ID: "com.apple.configuration.softwareupdate.settings", Schema: "declarative/declarations/configurations/softwareupdate.settings.yaml", Title: "Software Update:Settings", Kind: KindConfiguration, New: func() Declaration { return new(SoftwareUpdateSettings) }},
	"UserNameAndPasswordCredential":      {ID: "com.apple.credential.usernameandpassword", Schema: "declarative/declarations/assets/credentials/usernameandpassword.yaml", Title: "User Name and Password Credential", Kind: KindCredential, New: func() Declaration { return new(UserNameAndPasswordCredential) }},
	"WatchEnrollment":                    {ID: "com.apple.configuration.watch.enrollment", Schema: "declarative/declarations/configurations/watch.enrollment.yaml", Title: "Watch:Enrollment", Kind: KindConfiguration, New: func() Declaration { return new(WatchEnrollment) }},
	"WebContentFilterPlugin":             {ID: "com.apple.configuration.webcontent-filter.plugin", Schema: "declarative/declarations/configurations/webcontent-filter.plugin.yaml", Title: "WebContentFilter:Plugin", Kind: KindConfiguration, New: func() Declaration { return new(WebContentFilterPlugin) }},
}

// IDs returns the distinct wire identifiers in sorted order.
func IDs() []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(Registry))
	for _, en := range Registry {
		if !seen[en.ID] {
			seen[en.ID] = true
			out = append(out, en.ID)
		}
	}
	sortStrings(out)
	return out
}

// ByID returns every entry with the given wire identifier, sorted by type name.
func ByID(id string) []Entry {
	var names []string
	for name, en := range Registry {
		if en.ID == id {
			names = append(names, name)
		}
	}
	sortStrings(names)
	out := make([]Entry, 0, len(names))
	for _, n := range names {
		out = append(out, Registry[n])
	}
	return out
}

func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j-1] > s[j]; j-- {
			s[j-1], s[j] = s[j], s[j-1]
		}
	}
}

// DeclarationTypeName returns "com.apple.activation.simple".
func (*ActivationSimple) DeclarationTypeName() string { return "com.apple.activation.simple" }

// DeclarationKind returns the declaration kind.
func (*ActivationSimple) DeclarationKind() Kind { return KindActivation }

// DeclarationTypeName returns "com.apple.asset.credential.acme".
func (*AssetCredentialACME) DeclarationTypeName() string { return "com.apple.asset.credential.acme" }

// DeclarationKind returns the declaration kind.
func (*AssetCredentialACME) DeclarationKind() Kind { return KindAsset }

// DeclarationTypeName returns "com.apple.asset.credential.certificate".
func (*AssetCredentialCertificate) DeclarationTypeName() string {
	return "com.apple.asset.credential.certificate"
}

// DeclarationKind returns the declaration kind.
func (*AssetCredentialCertificate) DeclarationKind() Kind { return KindAsset }

// DeclarationTypeName returns "com.apple.asset.credential.identity".
func (*AssetCredentialIdentity) DeclarationTypeName() string {
	return "com.apple.asset.credential.identity"
}

// DeclarationKind returns the declaration kind.
func (*AssetCredentialIdentity) DeclarationKind() Kind { return KindAsset }

// DeclarationTypeName returns "com.apple.asset.credential.scep".
func (*AssetCredentialSCEP) DeclarationTypeName() string { return "com.apple.asset.credential.scep" }

// DeclarationKind returns the declaration kind.
func (*AssetCredentialSCEP) DeclarationKind() Kind { return KindAsset }

// DeclarationTypeName returns "com.apple.asset.credential.userpassword".
func (*AssetCredentialUserNameAndPassword) DeclarationTypeName() string {
	return "com.apple.asset.credential.userpassword"
}

// DeclarationKind returns the declaration kind.
func (*AssetCredentialUserNameAndPassword) DeclarationKind() Kind { return KindAsset }

// DeclarationTypeName returns "com.apple.credential.acme".
func (*ACMECredential) DeclarationTypeName() string { return "com.apple.credential.acme" }

// DeclarationKind returns the declaration kind.
func (*ACMECredential) DeclarationKind() Kind { return KindCredential }

// DeclarationTypeName returns "com.apple.credential.identity".
func (*IdentityCredential) DeclarationTypeName() string { return "com.apple.credential.identity" }

// DeclarationKind returns the declaration kind.
func (*IdentityCredential) DeclarationKind() Kind { return KindCredential }

// DeclarationTypeName returns "com.apple.credential.scep".
func (*SCEPCredential) DeclarationTypeName() string { return "com.apple.credential.scep" }

// DeclarationKind returns the declaration kind.
func (*SCEPCredential) DeclarationKind() Kind { return KindCredential }

// DeclarationTypeName returns "com.apple.credential.usernameandpassword".
func (*UserNameAndPasswordCredential) DeclarationTypeName() string {
	return "com.apple.credential.usernameandpassword"
}

// DeclarationKind returns the declaration kind.
func (*UserNameAndPasswordCredential) DeclarationKind() Kind { return KindCredential }

// DeclarationTypeName returns "com.apple.asset.data".
func (*AssetData) DeclarationTypeName() string { return "com.apple.asset.data" }

// DeclarationKind returns the declaration kind.
func (*AssetData) DeclarationKind() Kind { return KindAsset }

// DeclarationTypeName returns "com.apple.asset.useridentity".
func (*AssetUserIdentity) DeclarationTypeName() string { return "com.apple.asset.useridentity" }

// DeclarationKind returns the declaration kind.
func (*AssetUserIdentity) DeclarationKind() Kind { return KindAsset }

// DeclarationTypeName returns "com.apple.configuration.accessibility.settings".
func (*AccessibilitySettings) DeclarationTypeName() string {
	return "com.apple.configuration.accessibility.settings"
}

// DeclarationKind returns the declaration kind.
func (*AccessibilitySettings) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.account.caldav".
func (*AccountCalDAV) DeclarationTypeName() string { return "com.apple.configuration.account.caldav" }

// DeclarationKind returns the declaration kind.
func (*AccountCalDAV) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.account.carddav".
func (*AccountCardDAV) DeclarationTypeName() string { return "com.apple.configuration.account.carddav" }

// DeclarationKind returns the declaration kind.
func (*AccountCardDAV) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.account.exchange".
func (*AccountExchange) DeclarationTypeName() string {
	return "com.apple.configuration.account.exchange"
}

// DeclarationKind returns the declaration kind.
func (*AccountExchange) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.account.google".
func (*AccountGoogle) DeclarationTypeName() string { return "com.apple.configuration.account.google" }

// DeclarationKind returns the declaration kind.
func (*AccountGoogle) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.account.ldap".
func (*AccountLDAP) DeclarationTypeName() string { return "com.apple.configuration.account.ldap" }

// DeclarationKind returns the declaration kind.
func (*AccountLDAP) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.account.mail".
func (*AccountMail) DeclarationTypeName() string { return "com.apple.configuration.account.mail" }

// DeclarationKind returns the declaration kind.
func (*AccountMail) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.account.subscribed-calendar".
func (*AccountSubscribedCalendar) DeclarationTypeName() string {
	return "com.apple.configuration.account.subscribed-calendar"
}

// DeclarationKind returns the declaration kind.
func (*AccountSubscribedCalendar) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.app.managed".
func (*AppManaged) DeclarationTypeName() string { return "com.apple.configuration.app.managed" }

// DeclarationKind returns the declaration kind.
func (*AppManaged) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.app.settings".
func (*AppSettings) DeclarationTypeName() string { return "com.apple.configuration.app.settings" }

// DeclarationKind returns the declaration kind.
func (*AppSettings) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.audio-accessory.settings".
func (*AudioAccessorySettings) DeclarationTypeName() string {
	return "com.apple.configuration.audio-accessory.settings"
}

// DeclarationKind returns the declaration kind.
func (*AudioAccessorySettings) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.content-cache.settings".
func (*ContentCaching) DeclarationTypeName() string {
	return "com.apple.configuration.content-cache.settings"
}

// DeclarationKind returns the declaration kind.
func (*ContentCaching) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.diskmanagement.settings".
func (*DiskManagementSettings) DeclarationTypeName() string {
	return "com.apple.configuration.diskmanagement.settings"
}

// DeclarationKind returns the declaration kind.
func (*DiskManagementSettings) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.extensible-sso".
func (*ExtensibleSSO) DeclarationTypeName() string { return "com.apple.configuration.extensible-sso" }

// DeclarationKind returns the declaration kind.
func (*ExtensibleSSO) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.external-intelligence.settings".
func (*ExternalIntelligenceSettings) DeclarationTypeName() string {
	return "com.apple.configuration.external-intelligence.settings"
}

// DeclarationKind returns the declaration kind.
func (*ExternalIntelligenceSettings) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.intelligence.settings".
func (*IntelligenceSettings) DeclarationTypeName() string {
	return "com.apple.configuration.intelligence.settings"
}

// DeclarationKind returns the declaration kind.
func (*IntelligenceSettings) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.keyboard.settings".
func (*KeyboardSettings) DeclarationTypeName() string {
	return "com.apple.configuration.keyboard.settings"
}

// DeclarationKind returns the declaration kind.
func (*KeyboardSettings) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.legacy.interactive".
func (*LegacyInteractiveProfile) DeclarationTypeName() string {
	return "com.apple.configuration.legacy.interactive"
}

// DeclarationKind returns the declaration kind.
func (*LegacyInteractiveProfile) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.legacy".
func (*LegacyProfile) DeclarationTypeName() string { return "com.apple.configuration.legacy" }

// DeclarationKind returns the declaration kind.
func (*LegacyProfile) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.management.status-subscriptions".
func (*ManagementStatusSubscriptions) DeclarationTypeName() string {
	return "com.apple.configuration.management.status-subscriptions"
}

// DeclarationKind returns the declaration kind.
func (*ManagementStatusSubscriptions) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.management.test".
func (*ManagementTest) DeclarationTypeName() string { return "com.apple.configuration.management.test" }

// DeclarationKind returns the declaration kind.
func (*ManagementTest) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.math.settings".
func (*MathSettings) DeclarationTypeName() string { return "com.apple.configuration.math.settings" }

// DeclarationKind returns the declaration kind.
func (*MathSettings) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.migration-assistant.settings".
func (*MigrationAssistantSettings) DeclarationTypeName() string {
	return "com.apple.configuration.migration-assistant.settings"
}

// DeclarationKind returns the declaration kind.
func (*MigrationAssistantSettings) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.network.dns-proxy".
func (*NetworkDNSProxy) DeclarationTypeName() string {
	return "com.apple.configuration.network.dns-proxy"
}

// DeclarationKind returns the declaration kind.
func (*NetworkDNSProxy) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.network.dns-settings".
func (*NetworkDNSSettings) DeclarationTypeName() string {
	return "com.apple.configuration.network.dns-settings"
}

// DeclarationKind returns the declaration kind.
func (*NetworkDNSSettings) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.network.relay".
func (*NetworkRelay) DeclarationTypeName() string { return "com.apple.configuration.network.relay" }

// DeclarationKind returns the declaration kind.
func (*NetworkRelay) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.network.vpn.always-on".
func (*NetworkVPNAlwaysOn) DeclarationTypeName() string {
	return "com.apple.configuration.network.vpn.always-on"
}

// DeclarationKind returns the declaration kind.
func (*NetworkVPNAlwaysOn) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.network.vpn.ikev2".
func (*NetworkVPNIKEV2) DeclarationTypeName() string {
	return "com.apple.configuration.network.vpn.ikev2"
}

// DeclarationKind returns the declaration kind.
func (*NetworkVPNIKEV2) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.network.vpn.ipsec".
func (*NetworkVPNIPSec) DeclarationTypeName() string {
	return "com.apple.configuration.network.vpn.ipsec"
}

// DeclarationKind returns the declaration kind.
func (*NetworkVPNIPSec) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.network.vpn.vpn-plugin".
func (*NetworkVPNVPNPlugin) DeclarationTypeName() string {
	return "com.apple.configuration.network.vpn.vpn-plugin"
}

// DeclarationKind returns the declaration kind.
func (*NetworkVPNVPNPlugin) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.package".
func (*Package) DeclarationTypeName() string { return "com.apple.configuration.package" }

// DeclarationKind returns the declaration kind.
func (*Package) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.passcode.settings".
func (*PasscodeSettings) DeclarationTypeName() string {
	return "com.apple.configuration.passcode.settings"
}

// DeclarationKind returns the declaration kind.
func (*PasscodeSettings) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.safari.bookmarks".
func (*SafariBookmarks) DeclarationTypeName() string {
	return "com.apple.configuration.safari.bookmarks"
}

// DeclarationKind returns the declaration kind.
func (*SafariBookmarks) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.safari.extensions.settings".
func (*SafariExtensionSettings) DeclarationTypeName() string {
	return "com.apple.configuration.safari.extensions.settings"
}

// DeclarationKind returns the declaration kind.
func (*SafariExtensionSettings) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.safari.settings".
func (*SafariSettings) DeclarationTypeName() string { return "com.apple.configuration.safari.settings" }

// DeclarationKind returns the declaration kind.
func (*SafariSettings) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.screensharing.connection.group".
func (*ScreenSharingConnectionGroup) DeclarationTypeName() string {
	return "com.apple.configuration.screensharing.connection.group"
}

// DeclarationKind returns the declaration kind.
func (*ScreenSharingConnectionGroup) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.screensharing.connection".
func (*ScreenSharingConnection) DeclarationTypeName() string {
	return "com.apple.configuration.screensharing.connection"
}

// DeclarationKind returns the declaration kind.
func (*ScreenSharingConnection) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.screensharing.host.settings".
func (*ScreenSharingHostSettings) DeclarationTypeName() string {
	return "com.apple.configuration.screensharing.host.settings"
}

// DeclarationKind returns the declaration kind.
func (*ScreenSharingHostSettings) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.security.certificate".
func (*SecurityCertificate) DeclarationTypeName() string {
	return "com.apple.configuration.security.certificate"
}

// DeclarationKind returns the declaration kind.
func (*SecurityCertificate) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.security.identity".
func (*SecurityIdentity) DeclarationTypeName() string {
	return "com.apple.configuration.security.identity"
}

// DeclarationKind returns the declaration kind.
func (*SecurityIdentity) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.security.passkey.attestation".
func (*SecurityPasskeyAttestation) DeclarationTypeName() string {
	return "com.apple.configuration.security.passkey.attestation"
}

// DeclarationKind returns the declaration kind.
func (*SecurityPasskeyAttestation) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.services.background-tasks".
func (*ServicesBackgroundTasks) DeclarationTypeName() string {
	return "com.apple.configuration.services.background-tasks"
}

// DeclarationKind returns the declaration kind.
func (*ServicesBackgroundTasks) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.services.configuration-files".
func (*ServicesConfigurationFiles) DeclarationTypeName() string {
	return "com.apple.configuration.services.configuration-files"
}

// DeclarationKind returns the declaration kind.
func (*ServicesConfigurationFiles) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.siri.settings".
func (*SiriSettings) DeclarationTypeName() string { return "com.apple.configuration.siri.settings" }

// DeclarationKind returns the declaration kind.
func (*SiriSettings) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.softwareupdate.enforcement.specific".
func (*SoftwareUpdateEnforcementSpecific) DeclarationTypeName() string {
	return "com.apple.configuration.softwareupdate.enforcement.specific"
}

// DeclarationKind returns the declaration kind.
func (*SoftwareUpdateEnforcementSpecific) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.softwareupdate.settings".
func (*SoftwareUpdateSettings) DeclarationTypeName() string {
	return "com.apple.configuration.softwareupdate.settings"
}

// DeclarationKind returns the declaration kind.
func (*SoftwareUpdateSettings) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.watch.enrollment".
func (*WatchEnrollment) DeclarationTypeName() string {
	return "com.apple.configuration.watch.enrollment"
}

// DeclarationKind returns the declaration kind.
func (*WatchEnrollment) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "com.apple.configuration.webcontent-filter.plugin".
func (*WebContentFilterPlugin) DeclarationTypeName() string {
	return "com.apple.configuration.webcontent-filter.plugin"
}

// DeclarationKind returns the declaration kind.
func (*WebContentFilterPlugin) DeclarationKind() Kind { return KindConfiguration }

// DeclarationTypeName returns "".
func (*DeclarationBase) DeclarationTypeName() string { return "" }

// DeclarationKind returns the declaration kind.
func (*DeclarationBase) DeclarationKind() Kind { return KindBase }

// DeclarationTypeName returns "com.apple.management.organization-info".
func (*ManagementOrganizationInformation) DeclarationTypeName() string {
	return "com.apple.management.organization-info"
}

// DeclarationKind returns the declaration kind.
func (*ManagementOrganizationInformation) DeclarationKind() Kind { return KindManagement }

// DeclarationTypeName returns "com.apple.management.properties".
func (*ManagementProperties) DeclarationTypeName() string { return "com.apple.management.properties" }

// DeclarationKind returns the declaration kind.
func (*ManagementProperties) DeclarationKind() Kind { return KindManagement }

// DeclarationTypeName returns "com.apple.management.server-capabilities".
func (*ManagementServerCapabilities) DeclarationTypeName() string {
	return "com.apple.management.server-capabilities"
}

// DeclarationKind returns the declaration kind.
func (*ManagementServerCapabilities) DeclarationKind() Kind { return KindManagement }
