// Code generated by admgen; DO NOT EDIT.
// Source: apple/device-management@67045e2fa06f528b196c01edee6a8bf88b844beb

package commands

import (
	"github.com/deploymenttheory/go-apple-dm/schema/support"
)

// Command is implemented by every top-level type in this package.
type Command interface {
	// RequestTypeName returns the wire identifier from Apple's schema.
	RequestTypeName() string
	// SchemaPath returns the schema file the type was generated from.
	SchemaPath() string
	// Validate checks the value against the schema for the target.
	Validate(t support.Target) error
}

// Response is implemented by every command response type.
type Response interface {
	// ResponseRequestTypeName returns the RequestType this responds to.
	ResponseRequestTypeName() string
	SchemaPath() string
	Validate(t support.Target) error
}

// Entry describes one schema in the Registry.
type Entry struct {
	// ID is the wire identifier: RequestType, MessageType, PayloadType,
	// DeclarationType, StatusItemType, error code, or type name.
	ID string
	// Schema is the YAML path in apple/device-management.
	Schema string
	Title  string
	// New returns a zero value of the type as Command.
	New func() Command
	// NewResponse returns a zero response value.
	NewResponse func() Response
}

// Wire identifiers.
const (
	// RequestTypeAccountConfiguration: Account Configuration Command
	RequestTypeAccountConfiguration = "AccountConfiguration"
	// RequestTypeActiveNSExtensions: Active NSExtensions Command
	RequestTypeActiveNSExtensions = "ActiveNSExtensions"
	// RequestTypeNSExtensionMappings: NSExtension Mappings Command
	RequestTypeNSExtensionMappings = "NSExtensionMappings"
	// RequestTypeInstallEnterpriseApplication: Install Enterprise Application Command
	RequestTypeInstallEnterpriseApplication = "InstallEnterpriseApplication"
	// RequestTypeInstallApplication: Install Application Command
	RequestTypeInstallApplication = "InstallApplication"
	// RequestTypeInstalledApplicationList: Installed Application List Command
	RequestTypeInstalledApplicationList = "InstalledApplicationList"
	// RequestTypeInviteToProgram: Invite To Program Command
	RequestTypeInviteToProgram = "InviteToProgram"
	// RequestTypeManagedApplicationList: Managed Application List Command
	RequestTypeManagedApplicationList = "ManagedApplicationList"
	// RequestTypeApplyRedemptionCode: Apply Redemption Code Command
	RequestTypeApplyRedemptionCode = "ApplyRedemptionCode"
	// RequestTypeRemoveApplication: Remove Application Command
	RequestTypeRemoveApplication = "RemoveApplication"
	// RequestTypeValidateApplications: Validate Applications Command
	RequestTypeValidateApplications = "ValidateApplications"
	// RequestTypeCertificateList: Certificate List Command
	RequestTypeCertificateList = "CertificateList"
	// RequestTypeDeclarativeManagement: Declarative Management Command
	RequestTypeDeclarativeManagement = "DeclarativeManagement"
	// RequestTypeActivationLockBypassCode: Activation Lock Bypass Code Command
	RequestTypeActivationLockBypassCode = "ActivationLockBypassCode" // #nosec G101 -- Apple wire identifier, not a credential
	// RequestTypeClearActivationLockBypassCode: Clear Activation Lock Bypass Code Command
	RequestTypeClearActivationLockBypassCode = "ClearActivationLockBypassCode" // #nosec G101 -- Apple wire identifier, not a credential
	// RequestTypeDeviceConfigured: Device Configured Command
	RequestTypeDeviceConfigured = "DeviceConfigured"
	// RequestTypeEraseDevice: Erase Device Command
	RequestTypeEraseDevice = "EraseDevice"
	// RequestTypeRefreshCellularPlans: Refresh Cellular Plans Command
	RequestTypeRefreshCellularPlans = "RefreshCellularPlans"
	// RequestTypeDeviceLock: Device Lock Command
	RequestTypeDeviceLock = "DeviceLock"
	// RequestTypeDisableLostMode: Disable Lost Mode Command
	RequestTypeDisableLostMode = "DisableLostMode"
	// RequestTypeEnableLostMode: Enable Lost Mode Command
	RequestTypeEnableLostMode = "EnableLostMode"
	// RequestTypeDeviceLocation: Device Location Command
	RequestTypeDeviceLocation = "DeviceLocation"
	// RequestTypePlayLostModeSound: Play Lost Mode Sound Command
	RequestTypePlayLostModeSound = "PlayLostModeSound"
	// RequestTypeRestartDevice: Restart Device Command
	RequestTypeRestartDevice = "RestartDevice"
	// RequestTypeClearRestrictionsPassword: Clear Restrictions Password Command
	RequestTypeClearRestrictionsPassword = "ClearRestrictionsPassword" // #nosec G101 -- Apple wire identifier, not a credential
	// RequestTypeRestrictions: Restrictions Command
	RequestTypeRestrictions = "Restrictions"
	// RequestTypeShutDownDevice: Shut Down Device Command
	RequestTypeShutDownDevice = "ShutDownDevice"
	// RequestTypeContentCachingInformation: Content Caching Information Command
	RequestTypeContentCachingInformation = "ContentCachingInformation"
	// RequestTypeDeviceInformation: Device Information Command
	RequestTypeDeviceInformation = "DeviceInformation"
	// RequestTypeSecurityInfo: Security Info Command
	RequestTypeSecurityInfo = "SecurityInfo"
	// RequestTypeLOMDeviceRequest: LOM Device Request Command
	RequestTypeLOMDeviceRequest = "LOMDeviceRequest"
	// RequestTypeLOMSetupRequest: LOM Setup Request Command
	RequestTypeLOMSetupRequest = "LOMSetupRequest"
	// RequestTypeManagedApplicationAttributes: Managed Application Attributes Command
	RequestTypeManagedApplicationAttributes = "ManagedApplicationAttributes"
	// RequestTypeManagedApplicationConfiguration: Managed Application Configuration Command
	RequestTypeManagedApplicationConfiguration = "ManagedApplicationConfiguration"
	// RequestTypeManagedApplicationFeedback: Managed Application Feedback Command
	RequestTypeManagedApplicationFeedback = "ManagedApplicationFeedback"
	// RequestTypeInstallMedia: Install Media Command
	RequestTypeInstallMedia = "InstallMedia"
	// RequestTypeManagedMediaList: Managed Media List Command
	RequestTypeManagedMediaList = "ManagedMediaList"
	// RequestTypeRemoveMedia: Remove Media Command
	RequestTypeRemoveMedia = "RemoveMedia"
	// RequestTypeRequestMirroring: Request Mirroring Command
	RequestTypeRequestMirroring = "RequestMirroring"
	// RequestTypeStopMirroring: Stop Mirroring Command
	RequestTypeStopMirroring = "StopMirroring"
	// RequestTypeClearPasscode: Clear Passcode Command
	RequestTypeClearPasscode = "ClearPasscode" // #nosec G101 -- Apple wire identifier, not a credential
	// RequestTypeSetFirmwarePassword: Set Firmware Password Command
	RequestTypeSetFirmwarePassword = "SetFirmwarePassword" // #nosec G101 -- Apple wire identifier, not a credential
	// RequestTypeVerifyFirmwarePassword: Verify Firmware Password Command
	RequestTypeVerifyFirmwarePassword = "VerifyFirmwarePassword" // #nosec G101 -- Apple wire identifier, not a credential
	// RequestTypeSetRecoveryLock: Set Recovery Lock Command
	RequestTypeSetRecoveryLock = "SetRecoveryLock"
	// RequestTypeVerifyRecoveryLock: Verify Recovery Lock Command
	RequestTypeVerifyRecoveryLock = "VerifyRecoveryLock"
	// RequestTypeInstallProfile: Install Profile Command
	RequestTypeInstallProfile = "InstallProfile"
	// RequestTypeProfileList: Profile List Command
	RequestTypeProfileList = "ProfileList"
	// RequestTypeInstallProvisioningProfile: Install Provisioning Profile Command
	RequestTypeInstallProvisioningProfile = "InstallProvisioningProfile"
	// RequestTypeProvisioningProfileList: Provisioning Profile List Command
	RequestTypeProvisioningProfileList = "ProvisioningProfileList"
	// RequestTypeRemoveProvisioningProfile: Remove Provisioning Profile Command
	RequestTypeRemoveProvisioningProfile = "RemoveProvisioningProfile"
	// RequestTypeRemoveProfile: Remove Profile Command
	RequestTypeRemoveProfile = "RemoveProfile"
	// RequestTypeDisableRemoteDesktop: Disable Remote Desktop Command
	RequestTypeDisableRemoteDesktop = "DisableRemoteDesktop"
	// RequestTypeEnableRemoteDesktop: Enable Remote Desktop Command
	RequestTypeEnableRemoteDesktop = "EnableRemoteDesktop"
	// RequestTypeRotateFileVaultKey: Rotate FileVault Key Command
	RequestTypeRotateFileVaultKey = "RotateFileVaultKey"
	// RequestTypeSetAutoAdminPassword: Set Auto Admin Password Command
	RequestTypeSetAutoAdminPassword = "SetAutoAdminPassword" // #nosec G101 -- Apple wire identifier, not a credential
	// RequestTypeSettings: Settings Command
	RequestTypeSettings = "Settings"
	// RequestTypeAvailableOSUpdates: Available OS Updates Command
	RequestTypeAvailableOSUpdates = "AvailableOSUpdates"
	// RequestTypeScheduleOSUpdateScan: Schedule OS Update Scan Command
	RequestTypeScheduleOSUpdateScan = "ScheduleOSUpdateScan"
	// RequestTypeScheduleOSUpdate: Schedule OS Update Command
	RequestTypeScheduleOSUpdate = "ScheduleOSUpdate"
	// RequestTypeOSUpdateStatus: OS Update Status Command
	RequestTypeOSUpdateStatus = "OSUpdateStatus"
	// RequestTypeUserConfigured: User Configured Command
	RequestTypeUserConfigured = "UserConfigured"
	// RequestTypeDeleteUser: Delete User Command
	RequestTypeDeleteUser = "DeleteUser"
	// RequestTypeUserList: User List Command
	RequestTypeUserList = "UserList"
	// RequestTypeLogOutUser: Log Out User Command
	RequestTypeLogOutUser = "LogOutUser"
	// RequestTypeUnlockUserAccount: Unlock User Account Command
	RequestTypeUnlockUserAccount = "UnlockUserAccount"
)

// Registry maps Go type names to constructors, one entry per schema file.
// Several schemas may share a wire identifier (for example six profile
// payloads use com.apple.MCX), so look up by identifier with ByID.
var Registry = map[string]Entry{
	"AccountConfiguration":            {ID: "AccountConfiguration", Schema: "mdm/commands/account.configuration.yaml", Title: "Account Configuration Command", New: func() Command { return new(AccountConfiguration) }, NewResponse: func() Response { return new(AccountConfigurationResponse) }},
	"ActivationLockBypassCode":        {ID: "ActivationLockBypassCode", Schema: "mdm/commands/device.activationlock.bypasscode.yaml", Title: "Activation Lock Bypass Code Command", New: func() Command { return new(ActivationLockBypassCode) }, NewResponse: func() Response { return new(ActivationLockBypassCodeResponse) }},
	"ActiveNSExtensions":              {ID: "ActiveNSExtensions", Schema: "mdm/commands/application.extensions.listactive.yaml", Title: "Active NSExtensions Command", New: func() Command { return new(ActiveNSExtensions) }, NewResponse: func() Response { return new(ActiveNSExtensionsResponse) }},
	"ApplyRedemptionCode":             {ID: "ApplyRedemptionCode", Schema: "mdm/commands/application.redemptioncode.yaml", Title: "Apply Redemption Code Command", New: func() Command { return new(ApplyRedemptionCode) }, NewResponse: func() Response { return new(ApplyRedemptionCodeResponse) }},
	"AvailableOSUpdates":              {ID: "AvailableOSUpdates", Schema: "mdm/commands/system.update.available.yaml", Title: "Available OS Updates Command", New: func() Command { return new(AvailableOSUpdates) }, NewResponse: func() Response { return new(AvailableOSUpdatesResponse) }},
	"CertificateList":                 {ID: "CertificateList", Schema: "mdm/commands/certificate.list.yaml", Title: "Certificate List Command", New: func() Command { return new(CertificateList) }, NewResponse: func() Response { return new(CertificateListResponse) }},
	"ClearActivationLockBypassCode":   {ID: "ClearActivationLockBypassCode", Schema: "mdm/commands/device.activationlock.clearbypasscode.yaml", Title: "Clear Activation Lock Bypass Code Command", New: func() Command { return new(ClearActivationLockBypassCode) }, NewResponse: func() Response { return new(ClearActivationLockBypassCodeResponse) }},
	"ClearPasscode":                   {ID: "ClearPasscode", Schema: "mdm/commands/passcode.clear.yaml", Title: "Clear Passcode Command", New: func() Command { return new(ClearPasscode) }, NewResponse: func() Response { return new(ClearPasscodeResponse) }},
	"ClearRestrictionsPassword":       {ID: "ClearRestrictionsPassword", Schema: "mdm/commands/device.restrictions.clearpassword.yaml", Title: "Clear Restrictions Password Command", New: func() Command { return new(ClearRestrictionsPassword) }, NewResponse: func() Response { return new(ClearRestrictionsPasswordResponse) }},
	"ContentCachingInformation":       {ID: "ContentCachingInformation", Schema: "mdm/commands/information.contentcaching.yaml", Title: "Content Caching Information Command", New: func() Command { return new(ContentCachingInformation) }, NewResponse: func() Response { return new(ContentCachingInformationResponse) }},
	"DeclarativeManagement":           {ID: "DeclarativeManagement", Schema: "mdm/commands/declarativemanagement.yaml", Title: "Declarative Management Command", New: func() Command { return new(DeclarativeManagement) }, NewResponse: func() Response { return new(DeclarativeManagementResponse) }},
	"DeleteUser":                      {ID: "DeleteUser", Schema: "mdm/commands/user.delete.yaml", Title: "Delete User Command", New: func() Command { return new(DeleteUser) }, NewResponse: func() Response { return new(DeleteUserResponse) }},
	"DeviceConfigured":                {ID: "DeviceConfigured", Schema: "mdm/commands/device.configured.yaml", Title: "Device Configured Command", New: func() Command { return new(DeviceConfigured) }, NewResponse: func() Response { return new(DeviceConfiguredResponse) }},
	"DeviceInformation":               {ID: "DeviceInformation", Schema: "mdm/commands/information.device.yaml", Title: "Device Information Command", New: func() Command { return new(DeviceInformation) }, NewResponse: func() Response { return new(DeviceInformationResponse) }},
	"DeviceLocation":                  {ID: "DeviceLocation", Schema: "mdm/commands/device.lostmode.location.yaml", Title: "Device Location Command", New: func() Command { return new(DeviceLocation) }, NewResponse: func() Response { return new(DeviceLocationResponse) }},
	"DeviceLock":                      {ID: "DeviceLock", Schema: "mdm/commands/device.lock.yaml", Title: "Device Lock Command", New: func() Command { return new(DeviceLock) }, NewResponse: func() Response { return new(DeviceLockResponse) }},
	"DisableLostMode":                 {ID: "DisableLostMode", Schema: "mdm/commands/device.lostmode.disable.yaml", Title: "Disable Lost Mode Command", New: func() Command { return new(DisableLostMode) }, NewResponse: func() Response { return new(DisableLostModeResponse) }},
	"DisableRemoteDesktop":            {ID: "DisableRemoteDesktop", Schema: "mdm/commands/remotedesktop.disable.yaml", Title: "Disable Remote Desktop Command", New: func() Command { return new(DisableRemoteDesktop) }, NewResponse: func() Response { return new(DisableRemoteDesktopResponse) }},
	"EnableLostMode":                  {ID: "EnableLostMode", Schema: "mdm/commands/device.lostmode.enable.yaml", Title: "Enable Lost Mode Command", New: func() Command { return new(EnableLostMode) }, NewResponse: func() Response { return new(EnableLostModeResponse) }},
	"EnableRemoteDesktop":             {ID: "EnableRemoteDesktop", Schema: "mdm/commands/remotedesktop.enable.yaml", Title: "Enable Remote Desktop Command", New: func() Command { return new(EnableRemoteDesktop) }, NewResponse: func() Response { return new(EnableRemoteDesktopResponse) }},
	"EraseDevice":                     {ID: "EraseDevice", Schema: "mdm/commands/device.erase.yaml", Title: "Erase Device Command", New: func() Command { return new(EraseDevice) }, NewResponse: func() Response { return new(EraseDeviceResponse) }},
	"InstallApplication":              {ID: "InstallApplication", Schema: "mdm/commands/application.install.yaml", Title: "Install Application Command", New: func() Command { return new(InstallApplication) }, NewResponse: func() Response { return new(InstallApplicationResponse) }},
	"InstallEnterpriseApplication":    {ID: "InstallEnterpriseApplication", Schema: "mdm/commands/application.install.enterprise.yaml", Title: "Install Enterprise Application Command", New: func() Command { return new(InstallEnterpriseApplication) }, NewResponse: func() Response { return new(InstallEnterpriseApplicationResponse) }},
	"InstallMedia":                    {ID: "InstallMedia", Schema: "mdm/commands/media.install.yaml", Title: "Install Media Command", New: func() Command { return new(InstallMedia) }, NewResponse: func() Response { return new(InstallMediaResponse) }},
	"InstallProfile":                  {ID: "InstallProfile", Schema: "mdm/commands/profile.install.yaml", Title: "Install Profile Command", New: func() Command { return new(InstallProfile) }, NewResponse: func() Response { return new(InstallProfileResponse) }},
	"InstallProvisioningProfile":      {ID: "InstallProvisioningProfile", Schema: "mdm/commands/profile.provisioning.install.yaml", Title: "Install Provisioning Profile Command", New: func() Command { return new(InstallProvisioningProfile) }, NewResponse: func() Response { return new(InstallProvisioningProfileResponse) }},
	"InstalledApplicationList":        {ID: "InstalledApplicationList", Schema: "mdm/commands/application.installed.list.yaml", Title: "Installed Application List Command", New: func() Command { return new(InstalledApplicationList) }, NewResponse: func() Response { return new(InstalledApplicationListResponse) }},
	"InviteToProgram":                 {ID: "InviteToProgram", Schema: "mdm/commands/application.invitetoprogram.yaml", Title: "Invite To Program Command", New: func() Command { return new(InviteToProgram) }, NewResponse: func() Response { return new(InviteToProgramResponse) }},
	"LOMDeviceRequest":                {ID: "LOMDeviceRequest", Schema: "mdm/commands/lom.devicerequest.yaml", Title: "LOM Device Request Command", New: func() Command { return new(LOMDeviceRequest) }, NewResponse: func() Response { return new(LOMDeviceRequestResponse) }},
	"LOMSetupRequest":                 {ID: "LOMSetupRequest", Schema: "mdm/commands/lom.setuprequest.yaml", Title: "LOM Setup Request Command", New: func() Command { return new(LOMSetupRequest) }, NewResponse: func() Response { return new(LOMSetupRequestResponse) }},
	"LogOutUser":                      {ID: "LogOutUser", Schema: "mdm/commands/user.logout.yaml", Title: "Log Out User Command", New: func() Command { return new(LogOutUser) }, NewResponse: func() Response { return new(LogOutUserResponse) }},
	"ManagedApplicationAttributes":    {ID: "ManagedApplicationAttributes", Schema: "mdm/commands/managed.application.attributes.yaml", Title: "Managed Application Attributes Command", New: func() Command { return new(ManagedApplicationAttributes) }, NewResponse: func() Response { return new(ManagedApplicationAttributesResponse) }},
	"ManagedApplicationConfiguration": {ID: "ManagedApplicationConfiguration", Schema: "mdm/commands/managed.application.configuration.yaml", Title: "Managed Application Configuration Command", New: func() Command { return new(ManagedApplicationConfiguration) }, NewResponse: func() Response { return new(ManagedApplicationConfigurationResponse) }},
	"ManagedApplicationFeedback":      {ID: "ManagedApplicationFeedback", Schema: "mdm/commands/managed.application.feedback.yaml", Title: "Managed Application Feedback Command", New: func() Command { return new(ManagedApplicationFeedback) }, NewResponse: func() Response { return new(ManagedApplicationFeedbackResponse) }},
	"ManagedApplicationList":          {ID: "ManagedApplicationList", Schema: "mdm/commands/application.managed.list.yaml", Title: "Managed Application List Command", New: func() Command { return new(ManagedApplicationList) }, NewResponse: func() Response { return new(ManagedApplicationListResponse) }},
	"ManagedMediaList":                {ID: "ManagedMediaList", Schema: "mdm/commands/media.managed.list.yaml", Title: "Managed Media List Command", New: func() Command { return new(ManagedMediaList) }, NewResponse: func() Response { return new(ManagedMediaListResponse) }},
	"NSExtensionMappings":             {ID: "NSExtensionMappings", Schema: "mdm/commands/application.extensions.mappings.yaml", Title: "NSExtension Mappings Command", New: func() Command { return new(NSExtensionMappings) }, NewResponse: func() Response { return new(NSExtensionMappingsResponse) }},
	"OSUpdateStatus":                  {ID: "OSUpdateStatus", Schema: "mdm/commands/system.update.status.yaml", Title: "OS Update Status Command", New: func() Command { return new(OSUpdateStatus) }, NewResponse: func() Response { return new(OSUpdateStatusResponse) }},
	"PlayLostModeSound":               {ID: "PlayLostModeSound", Schema: "mdm/commands/device.lostmode.playsound.yaml", Title: "Play Lost Mode Sound Command", New: func() Command { return new(PlayLostModeSound) }, NewResponse: func() Response { return new(PlayLostModeSoundResponse) }},
	"ProfileList":                     {ID: "ProfileList", Schema: "mdm/commands/profile.list.yaml", Title: "Profile List Command", New: func() Command { return new(ProfileList) }, NewResponse: func() Response { return new(ProfileListResponse) }},
	"ProvisioningProfileList":         {ID: "ProvisioningProfileList", Schema: "mdm/commands/profile.provisioning.list.yaml", Title: "Provisioning Profile List Command", New: func() Command { return new(ProvisioningProfileList) }, NewResponse: func() Response { return new(ProvisioningProfileListResponse) }},
	"RefreshCellularPlans":            {ID: "RefreshCellularPlans", Schema: "mdm/commands/device.esim.yaml", Title: "Refresh Cellular Plans Command", New: func() Command { return new(RefreshCellularPlans) }, NewResponse: func() Response { return new(RefreshCellularPlansResponse) }},
	"RemoveApplication":               {ID: "RemoveApplication", Schema: "mdm/commands/application.remove.yaml", Title: "Remove Application Command", New: func() Command { return new(RemoveApplication) }, NewResponse: func() Response { return new(RemoveApplicationResponse) }},
	"RemoveMedia":                     {ID: "RemoveMedia", Schema: "mdm/commands/media.remove.yaml", Title: "Remove Media Command", New: func() Command { return new(RemoveMedia) }, NewResponse: func() Response { return new(RemoveMediaResponse) }},
	"RemoveProfile":                   {ID: "RemoveProfile", Schema: "mdm/commands/profile.remove.yaml", Title: "Remove Profile Command", New: func() Command { return new(RemoveProfile) }, NewResponse: func() Response { return new(RemoveProfileResponse) }},
	"RemoveProvisioningProfile":       {ID: "RemoveProvisioningProfile", Schema: "mdm/commands/profile.provisioning.remove.yaml", Title: "Remove Provisioning Profile Command", New: func() Command { return new(RemoveProvisioningProfile) }, NewResponse: func() Response { return new(RemoveProvisioningProfileResponse) }},
	"RequestMirroring":                {ID: "RequestMirroring", Schema: "mdm/commands/mirroring.request.yaml", Title: "Request Mirroring Command", New: func() Command { return new(RequestMirroring) }, NewResponse: func() Response { return new(RequestMirroringResponse) }},
	"RestartDevice":                   {ID: "RestartDevice", Schema: "mdm/commands/device.restart.yaml", Title: "Restart Device Command", New: func() Command { return new(RestartDevice) }, NewResponse: func() Response { return new(RestartDeviceResponse) }},
	"Restrictions":                    {ID: "Restrictions", Schema: "mdm/commands/device.restrictions.list.yaml", Title: "Restrictions Command", New: func() Command { return new(Restrictions) }, NewResponse: func() Response { return new(RestrictionsResponse) }},
	"RotateFileVaultKey":              {ID: "RotateFileVaultKey", Schema: "mdm/commands/rotate.file.vault.key.yaml", Title: "Rotate FileVault Key Command", New: func() Command { return new(RotateFileVaultKey) }, NewResponse: func() Response { return new(RotateFileVaultKeyResponse) }},
	"ScheduleOSUpdate":                {ID: "ScheduleOSUpdate", Schema: "mdm/commands/system.update.schedule.yaml", Title: "Schedule OS Update Command", New: func() Command { return new(ScheduleOSUpdate) }, NewResponse: func() Response { return new(ScheduleOSUpdateResponse) }},
	"ScheduleOSUpdateScan":            {ID: "ScheduleOSUpdateScan", Schema: "mdm/commands/system.update.scan.yaml", Title: "Schedule OS Update Scan Command", New: func() Command { return new(ScheduleOSUpdateScan) }, NewResponse: func() Response { return new(ScheduleOSUpdateScanResponse) }},
	"SecurityInfo":                    {ID: "SecurityInfo", Schema: "mdm/commands/information.security.yaml", Title: "Security Info Command", New: func() Command { return new(SecurityInfo) }, NewResponse: func() Response { return new(SecurityInfoResponse) }},
	"SetAutoAdminPassword":            {ID: "SetAutoAdminPassword", Schema: "mdm/commands/set.auto.admin.password.yaml", Title: "Set Auto Admin Password Command", New: func() Command { return new(SetAutoAdminPassword) }, NewResponse: func() Response { return new(SetAutoAdminPasswordResponse) }},
	"SetFirmwarePassword":             {ID: "SetFirmwarePassword", Schema: "mdm/commands/passcode.firmware.set.yaml", Title: "Set Firmware Password Command", New: func() Command { return new(SetFirmwarePassword) }, NewResponse: func() Response { return new(SetFirmwarePasswordResponse) }},
	"SetRecoveryLock":                 {ID: "SetRecoveryLock", Schema: "mdm/commands/passcode.recovery.set.yaml", Title: "Set Recovery Lock Command", New: func() Command { return new(SetRecoveryLock) }, NewResponse: func() Response { return new(SetRecoveryLockResponse) }},
	"Settings":                        {ID: "Settings", Schema: "mdm/commands/settings.yaml", Title: "Settings Command", New: func() Command { return new(Settings) }, NewResponse: func() Response { return new(SettingsResponse) }},
	"ShutDownDevice":                  {ID: "ShutDownDevice", Schema: "mdm/commands/device.shutdown.yaml", Title: "Shut Down Device Command", New: func() Command { return new(ShutDownDevice) }, NewResponse: func() Response { return new(ShutDownDeviceResponse) }},
	"StopMirroring":                   {ID: "StopMirroring", Schema: "mdm/commands/mirroring.stop.yaml", Title: "Stop Mirroring Command", New: func() Command { return new(StopMirroring) }, NewResponse: func() Response { return new(StopMirroringResponse) }},
	"UnlockUserAccount":               {ID: "UnlockUserAccount", Schema: "mdm/commands/user.unlock.yaml", Title: "Unlock User Account Command", New: func() Command { return new(UnlockUserAccount) }, NewResponse: func() Response { return new(UnlockUserAccountResponse) }},
	"UserConfigured":                  {ID: "UserConfigured", Schema: "mdm/commands/user.configured.yaml", Title: "User Configured Command", New: func() Command { return new(UserConfigured) }, NewResponse: func() Response { return new(UserConfiguredResponse) }},
	"UserList":                        {ID: "UserList", Schema: "mdm/commands/user.list.yaml", Title: "User List Command", New: func() Command { return new(UserList) }, NewResponse: func() Response { return new(UserListResponse) }},
	"ValidateApplications":            {ID: "ValidateApplications", Schema: "mdm/commands/application.validate.yaml", Title: "Validate Applications Command", New: func() Command { return new(ValidateApplications) }, NewResponse: func() Response { return new(ValidateApplicationsResponse) }},
	"VerifyFirmwarePassword":          {ID: "VerifyFirmwarePassword", Schema: "mdm/commands/passcode.firmware.verify.yaml", Title: "Verify Firmware Password Command", New: func() Command { return new(VerifyFirmwarePassword) }, NewResponse: func() Response { return new(VerifyFirmwarePasswordResponse) }},
	"VerifyRecoveryLock":              {ID: "VerifyRecoveryLock", Schema: "mdm/commands/passcode.recovery.verify.yaml", Title: "Verify Recovery Lock Command", New: func() Command { return new(VerifyRecoveryLock) }, NewResponse: func() Response { return new(VerifyRecoveryLockResponse) }},
}

// IDs returns the distinct wire identifiers in sorted order.
func IDs() []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(Registry))
	for _, en := range Registry {
		if !seen[en.ID] {
			seen[en.ID] = true
			out = append(out, en.ID)
		}
	}
	sortStrings(out)
	return out
}

// ByID returns every entry with the given wire identifier, sorted by type name.
func ByID(id string) []Entry {
	var names []string
	for name, en := range Registry {
		if en.ID == id {
			names = append(names, name)
		}
	}
	sortStrings(names)
	out := make([]Entry, 0, len(names))
	for _, n := range names {
		out = append(out, Registry[n])
	}
	return out
}

func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j-1] > s[j]; j-- {
			s[j-1], s[j] = s[j], s[j-1]
		}
	}
}

// RequestTypeName returns "AccountConfiguration".
func (*AccountConfiguration) RequestTypeName() string { return "AccountConfiguration" }

// ResponseRequestTypeName returns "AccountConfiguration".
func (*AccountConfigurationResponse) ResponseRequestTypeName() string { return "AccountConfiguration" }

// RequestTypeName returns "ActiveNSExtensions".
func (*ActiveNSExtensions) RequestTypeName() string { return "ActiveNSExtensions" }

// ResponseRequestTypeName returns "ActiveNSExtensions".
func (*ActiveNSExtensionsResponse) ResponseRequestTypeName() string { return "ActiveNSExtensions" }

// RequestTypeName returns "NSExtensionMappings".
func (*NSExtensionMappings) RequestTypeName() string { return "NSExtensionMappings" }

// ResponseRequestTypeName returns "NSExtensionMappings".
func (*NSExtensionMappingsResponse) ResponseRequestTypeName() string { return "NSExtensionMappings" }

// RequestTypeName returns "InstallEnterpriseApplication".
func (*InstallEnterpriseApplication) RequestTypeName() string { return "InstallEnterpriseApplication" }

// ResponseRequestTypeName returns "InstallEnterpriseApplication".
func (*InstallEnterpriseApplicationResponse) ResponseRequestTypeName() string {
	return "InstallEnterpriseApplication"
}

// RequestTypeName returns "InstallApplication".
func (*InstallApplication) RequestTypeName() string { return "InstallApplication" }

// ResponseRequestTypeName returns "InstallApplication".
func (*InstallApplicationResponse) ResponseRequestTypeName() string { return "InstallApplication" }

// RequestTypeName returns "InstalledApplicationList".
func (*InstalledApplicationList) RequestTypeName() string { return "InstalledApplicationList" }

// ResponseRequestTypeName returns "InstalledApplicationList".
func (*InstalledApplicationListResponse) ResponseRequestTypeName() string {
	return "InstalledApplicationList"
}

// RequestTypeName returns "InviteToProgram".
func (*InviteToProgram) RequestTypeName() string { return "InviteToProgram" }

// ResponseRequestTypeName returns "InviteToProgram".
func (*InviteToProgramResponse) ResponseRequestTypeName() string { return "InviteToProgram" }

// RequestTypeName returns "ManagedApplicationList".
func (*ManagedApplicationList) RequestTypeName() string { return "ManagedApplicationList" }

// ResponseRequestTypeName returns "ManagedApplicationList".
func (*ManagedApplicationListResponse) ResponseRequestTypeName() string {
	return "ManagedApplicationList"
}

// RequestTypeName returns "ApplyRedemptionCode".
func (*ApplyRedemptionCode) RequestTypeName() string { return "ApplyRedemptionCode" }

// ResponseRequestTypeName returns "ApplyRedemptionCode".
func (*ApplyRedemptionCodeResponse) ResponseRequestTypeName() string { return "ApplyRedemptionCode" }

// RequestTypeName returns "RemoveApplication".
func (*RemoveApplication) RequestTypeName() string { return "RemoveApplication" }

// ResponseRequestTypeName returns "RemoveApplication".
func (*RemoveApplicationResponse) ResponseRequestTypeName() string { return "RemoveApplication" }

// RequestTypeName returns "ValidateApplications".
func (*ValidateApplications) RequestTypeName() string { return "ValidateApplications" }

// ResponseRequestTypeName returns "ValidateApplications".
func (*ValidateApplicationsResponse) ResponseRequestTypeName() string { return "ValidateApplications" }

// RequestTypeName returns "CertificateList".
func (*CertificateList) RequestTypeName() string { return "CertificateList" }

// ResponseRequestTypeName returns "CertificateList".
func (*CertificateListResponse) ResponseRequestTypeName() string { return "CertificateList" }

// RequestTypeName returns "DeclarativeManagement".
func (*DeclarativeManagement) RequestTypeName() string { return "DeclarativeManagement" }

// ResponseRequestTypeName returns "DeclarativeManagement".
func (*DeclarativeManagementResponse) ResponseRequestTypeName() string {
	return "DeclarativeManagement"
}

// RequestTypeName returns "ActivationLockBypassCode".
func (*ActivationLockBypassCode) RequestTypeName() string { return "ActivationLockBypassCode" }

// ResponseRequestTypeName returns "ActivationLockBypassCode".
func (*ActivationLockBypassCodeResponse) ResponseRequestTypeName() string {
	return "ActivationLockBypassCode"
}

// RequestTypeName returns "ClearActivationLockBypassCode".
func (*ClearActivationLockBypassCode) RequestTypeName() string {
	return "ClearActivationLockBypassCode"
}

// ResponseRequestTypeName returns "ClearActivationLockBypassCode".
func (*ClearActivationLockBypassCodeResponse) ResponseRequestTypeName() string {
	return "ClearActivationLockBypassCode"
}

// RequestTypeName returns "DeviceConfigured".
func (*DeviceConfigured) RequestTypeName() string { return "DeviceConfigured" }

// ResponseRequestTypeName returns "DeviceConfigured".
func (*DeviceConfiguredResponse) ResponseRequestTypeName() string { return "DeviceConfigured" }

// RequestTypeName returns "EraseDevice".
func (*EraseDevice) RequestTypeName() string { return "EraseDevice" }

// ResponseRequestTypeName returns "EraseDevice".
func (*EraseDeviceResponse) ResponseRequestTypeName() string { return "EraseDevice" }

// RequestTypeName returns "RefreshCellularPlans".
func (*RefreshCellularPlans) RequestTypeName() string { return "RefreshCellularPlans" }

// ResponseRequestTypeName returns "RefreshCellularPlans".
func (*RefreshCellularPlansResponse) ResponseRequestTypeName() string { return "RefreshCellularPlans" }

// RequestTypeName returns "DeviceLock".
func (*DeviceLock) RequestTypeName() string { return "DeviceLock" }

// ResponseRequestTypeName returns "DeviceLock".
func (*DeviceLockResponse) ResponseRequestTypeName() string { return "DeviceLock" }

// RequestTypeName returns "DisableLostMode".
func (*DisableLostMode) RequestTypeName() string { return "DisableLostMode" }

// ResponseRequestTypeName returns "DisableLostMode".
func (*DisableLostModeResponse) ResponseRequestTypeName() string { return "DisableLostMode" }

// RequestTypeName returns "EnableLostMode".
func (*EnableLostMode) RequestTypeName() string { return "EnableLostMode" }

// ResponseRequestTypeName returns "EnableLostMode".
func (*EnableLostModeResponse) ResponseRequestTypeName() string { return "EnableLostMode" }

// RequestTypeName returns "DeviceLocation".
func (*DeviceLocation) RequestTypeName() string { return "DeviceLocation" }

// ResponseRequestTypeName returns "DeviceLocation".
func (*DeviceLocationResponse) ResponseRequestTypeName() string { return "DeviceLocation" }

// RequestTypeName returns "PlayLostModeSound".
func (*PlayLostModeSound) RequestTypeName() string { return "PlayLostModeSound" }

// ResponseRequestTypeName returns "PlayLostModeSound".
func (*PlayLostModeSoundResponse) ResponseRequestTypeName() string { return "PlayLostModeSound" }

// RequestTypeName returns "RestartDevice".
func (*RestartDevice) RequestTypeName() string { return "RestartDevice" }

// ResponseRequestTypeName returns "RestartDevice".
func (*RestartDeviceResponse) ResponseRequestTypeName() string { return "RestartDevice" }

// RequestTypeName returns "ClearRestrictionsPassword".
func (*ClearRestrictionsPassword) RequestTypeName() string { return "ClearRestrictionsPassword" }

// ResponseRequestTypeName returns "ClearRestrictionsPassword".
func (*ClearRestrictionsPasswordResponse) ResponseRequestTypeName() string {
	return "ClearRestrictionsPassword"
}

// RequestTypeName returns "Restrictions".
func (*Restrictions) RequestTypeName() string { return "Restrictions" }

// ResponseRequestTypeName returns "Restrictions".
func (*RestrictionsResponse) ResponseRequestTypeName() string { return "Restrictions" }

// RequestTypeName returns "ShutDownDevice".
func (*ShutDownDevice) RequestTypeName() string { return "ShutDownDevice" }

// ResponseRequestTypeName returns "ShutDownDevice".
func (*ShutDownDeviceResponse) ResponseRequestTypeName() string { return "ShutDownDevice" }

// RequestTypeName returns "ContentCachingInformation".
func (*ContentCachingInformation) RequestTypeName() string { return "ContentCachingInformation" }

// ResponseRequestTypeName returns "ContentCachingInformation".
func (*ContentCachingInformationResponse) ResponseRequestTypeName() string {
	return "ContentCachingInformation"
}

// RequestTypeName returns "DeviceInformation".
func (*DeviceInformation) RequestTypeName() string { return "DeviceInformation" }

// ResponseRequestTypeName returns "DeviceInformation".
func (*DeviceInformationResponse) ResponseRequestTypeName() string { return "DeviceInformation" }

// RequestTypeName returns "SecurityInfo".
func (*SecurityInfo) RequestTypeName() string { return "SecurityInfo" }

// ResponseRequestTypeName returns "SecurityInfo".
func (*SecurityInfoResponse) ResponseRequestTypeName() string { return "SecurityInfo" }

// RequestTypeName returns "LOMDeviceRequest".
func (*LOMDeviceRequest) RequestTypeName() string { return "LOMDeviceRequest" }

// ResponseRequestTypeName returns "LOMDeviceRequest".
func (*LOMDeviceRequestResponse) ResponseRequestTypeName() string { return "LOMDeviceRequest" }

// RequestTypeName returns "LOMSetupRequest".
func (*LOMSetupRequest) RequestTypeName() string { return "LOMSetupRequest" }

// ResponseRequestTypeName returns "LOMSetupRequest".
func (*LOMSetupRequestResponse) ResponseRequestTypeName() string { return "LOMSetupRequest" }

// RequestTypeName returns "ManagedApplicationAttributes".
func (*ManagedApplicationAttributes) RequestTypeName() string { return "ManagedApplicationAttributes" }

// ResponseRequestTypeName returns "ManagedApplicationAttributes".
func (*ManagedApplicationAttributesResponse) ResponseRequestTypeName() string {
	return "ManagedApplicationAttributes"
}

// RequestTypeName returns "ManagedApplicationConfiguration".
func (*ManagedApplicationConfiguration) RequestTypeName() string {
	return "ManagedApplicationConfiguration"
}

// ResponseRequestTypeName returns "ManagedApplicationConfiguration".
func (*ManagedApplicationConfigurationResponse) ResponseRequestTypeName() string {
	return "ManagedApplicationConfiguration"
}

// RequestTypeName returns "ManagedApplicationFeedback".
func (*ManagedApplicationFeedback) RequestTypeName() string { return "ManagedApplicationFeedback" }

// ResponseRequestTypeName returns "ManagedApplicationFeedback".
func (*ManagedApplicationFeedbackResponse) ResponseRequestTypeName() string {
	return "ManagedApplicationFeedback"
}

// RequestTypeName returns "InstallMedia".
func (*InstallMedia) RequestTypeName() string { return "InstallMedia" }

// ResponseRequestTypeName returns "InstallMedia".
func (*InstallMediaResponse) ResponseRequestTypeName() string { return "InstallMedia" }

// RequestTypeName returns "ManagedMediaList".
func (*ManagedMediaList) RequestTypeName() string { return "ManagedMediaList" }

// ResponseRequestTypeName returns "ManagedMediaList".
func (*ManagedMediaListResponse) ResponseRequestTypeName() string { return "ManagedMediaList" }

// RequestTypeName returns "RemoveMedia".
func (*RemoveMedia) RequestTypeName() string { return "RemoveMedia" }

// ResponseRequestTypeName returns "RemoveMedia".
func (*RemoveMediaResponse) ResponseRequestTypeName() string { return "RemoveMedia" }

// RequestTypeName returns "RequestMirroring".
func (*RequestMirroring) RequestTypeName() string { return "RequestMirroring" }

// ResponseRequestTypeName returns "RequestMirroring".
func (*RequestMirroringResponse) ResponseRequestTypeName() string { return "RequestMirroring" }

// RequestTypeName returns "StopMirroring".
func (*StopMirroring) RequestTypeName() string { return "StopMirroring" }

// ResponseRequestTypeName returns "StopMirroring".
func (*StopMirroringResponse) ResponseRequestTypeName() string { return "StopMirroring" }

// RequestTypeName returns "ClearPasscode".
func (*ClearPasscode) RequestTypeName() string { return "ClearPasscode" }

// ResponseRequestTypeName returns "ClearPasscode".
func (*ClearPasscodeResponse) ResponseRequestTypeName() string { return "ClearPasscode" }

// RequestTypeName returns "SetFirmwarePassword".
func (*SetFirmwarePassword) RequestTypeName() string { return "SetFirmwarePassword" }

// ResponseRequestTypeName returns "SetFirmwarePassword".
func (*SetFirmwarePasswordResponse) ResponseRequestTypeName() string { return "SetFirmwarePassword" }

// RequestTypeName returns "VerifyFirmwarePassword".
func (*VerifyFirmwarePassword) RequestTypeName() string { return "VerifyFirmwarePassword" }

// ResponseRequestTypeName returns "VerifyFirmwarePassword".
func (*VerifyFirmwarePasswordResponse) ResponseRequestTypeName() string {
	return "VerifyFirmwarePassword"
}

// RequestTypeName returns "SetRecoveryLock".
func (*SetRecoveryLock) RequestTypeName() string { return "SetRecoveryLock" }

// ResponseRequestTypeName returns "SetRecoveryLock".
func (*SetRecoveryLockResponse) ResponseRequestTypeName() string { return "SetRecoveryLock" }

// RequestTypeName returns "VerifyRecoveryLock".
func (*VerifyRecoveryLock) RequestTypeName() string { return "VerifyRecoveryLock" }

// ResponseRequestTypeName returns "VerifyRecoveryLock".
func (*VerifyRecoveryLockResponse) ResponseRequestTypeName() string { return "VerifyRecoveryLock" }

// RequestTypeName returns "InstallProfile".
func (*InstallProfile) RequestTypeName() string { return "InstallProfile" }

// ResponseRequestTypeName returns "InstallProfile".
func (*InstallProfileResponse) ResponseRequestTypeName() string { return "InstallProfile" }

// RequestTypeName returns "ProfileList".
func (*ProfileList) RequestTypeName() string { return "ProfileList" }

// ResponseRequestTypeName returns "ProfileList".
func (*ProfileListResponse) ResponseRequestTypeName() string { return "ProfileList" }

// RequestTypeName returns "InstallProvisioningProfile".
func (*InstallProvisioningProfile) RequestTypeName() string { return "InstallProvisioningProfile" }

// ResponseRequestTypeName returns "InstallProvisioningProfile".
func (*InstallProvisioningProfileResponse) ResponseRequestTypeName() string {
	return "InstallProvisioningProfile"
}

// RequestTypeName returns "ProvisioningProfileList".
func (*ProvisioningProfileList) RequestTypeName() string { return "ProvisioningProfileList" }

// ResponseRequestTypeName returns "ProvisioningProfileList".
func (*ProvisioningProfileListResponse) ResponseRequestTypeName() string {
	return "ProvisioningProfileList"
}

// RequestTypeName returns "RemoveProvisioningProfile".
func (*RemoveProvisioningProfile) RequestTypeName() string { return "RemoveProvisioningProfile" }

// ResponseRequestTypeName returns "RemoveProvisioningProfile".
func (*RemoveProvisioningProfileResponse) ResponseRequestTypeName() string {
	return "RemoveProvisioningProfile"
}

// RequestTypeName returns "RemoveProfile".
func (*RemoveProfile) RequestTypeName() string { return "RemoveProfile" }

// ResponseRequestTypeName returns "RemoveProfile".
func (*RemoveProfileResponse) ResponseRequestTypeName() string { return "RemoveProfile" }

// RequestTypeName returns "DisableRemoteDesktop".
func (*DisableRemoteDesktop) RequestTypeName() string { return "DisableRemoteDesktop" }

// ResponseRequestTypeName returns "DisableRemoteDesktop".
func (*DisableRemoteDesktopResponse) ResponseRequestTypeName() string { return "DisableRemoteDesktop" }

// RequestTypeName returns "EnableRemoteDesktop".
func (*EnableRemoteDesktop) RequestTypeName() string { return "EnableRemoteDesktop" }

// ResponseRequestTypeName returns "EnableRemoteDesktop".
func (*EnableRemoteDesktopResponse) ResponseRequestTypeName() string { return "EnableRemoteDesktop" }

// RequestTypeName returns "RotateFileVaultKey".
func (*RotateFileVaultKey) RequestTypeName() string { return "RotateFileVaultKey" }

// ResponseRequestTypeName returns "RotateFileVaultKey".
func (*RotateFileVaultKeyResponse) ResponseRequestTypeName() string { return "RotateFileVaultKey" }

// RequestTypeName returns "SetAutoAdminPassword".
func (*SetAutoAdminPassword) RequestTypeName() string { return "SetAutoAdminPassword" }

// ResponseRequestTypeName returns "SetAutoAdminPassword".
func (*SetAutoAdminPasswordResponse) ResponseRequestTypeName() string { return "SetAutoAdminPassword" }

// RequestTypeName returns "Settings".
func (*Settings) RequestTypeName() string { return "Settings" }

// ResponseRequestTypeName returns "Settings".
func (*SettingsResponse) ResponseRequestTypeName() string { return "Settings" }

// RequestTypeName returns "AvailableOSUpdates".
func (*AvailableOSUpdates) RequestTypeName() string { return "AvailableOSUpdates" }

// ResponseRequestTypeName returns "AvailableOSUpdates".
func (*AvailableOSUpdatesResponse) ResponseRequestTypeName() string { return "AvailableOSUpdates" }

// RequestTypeName returns "ScheduleOSUpdateScan".
func (*ScheduleOSUpdateScan) RequestTypeName() string { return "ScheduleOSUpdateScan" }

// ResponseRequestTypeName returns "ScheduleOSUpdateScan".
func (*ScheduleOSUpdateScanResponse) ResponseRequestTypeName() string { return "ScheduleOSUpdateScan" }

// RequestTypeName returns "ScheduleOSUpdate".
func (*ScheduleOSUpdate) RequestTypeName() string { return "ScheduleOSUpdate" }

// ResponseRequestTypeName returns "ScheduleOSUpdate".
func (*ScheduleOSUpdateResponse) ResponseRequestTypeName() string { return "ScheduleOSUpdate" }

// RequestTypeName returns "OSUpdateStatus".
func (*OSUpdateStatus) RequestTypeName() string { return "OSUpdateStatus" }

// ResponseRequestTypeName returns "OSUpdateStatus".
func (*OSUpdateStatusResponse) ResponseRequestTypeName() string { return "OSUpdateStatus" }

// RequestTypeName returns "UserConfigured".
func (*UserConfigured) RequestTypeName() string { return "UserConfigured" }

// ResponseRequestTypeName returns "UserConfigured".
func (*UserConfiguredResponse) ResponseRequestTypeName() string { return "UserConfigured" }

// RequestTypeName returns "DeleteUser".
func (*DeleteUser) RequestTypeName() string { return "DeleteUser" }

// ResponseRequestTypeName returns "DeleteUser".
func (*DeleteUserResponse) ResponseRequestTypeName() string { return "DeleteUser" }

// RequestTypeName returns "UserList".
func (*UserList) RequestTypeName() string { return "UserList" }

// ResponseRequestTypeName returns "UserList".
func (*UserListResponse) ResponseRequestTypeName() string { return "UserList" }

// RequestTypeName returns "LogOutUser".
func (*LogOutUser) RequestTypeName() string { return "LogOutUser" }

// ResponseRequestTypeName returns "LogOutUser".
func (*LogOutUserResponse) ResponseRequestTypeName() string { return "LogOutUser" }

// RequestTypeName returns "UnlockUserAccount".
func (*UnlockUserAccount) RequestTypeName() string { return "UnlockUserAccount" }

// ResponseRequestTypeName returns "UnlockUserAccount".
func (*UnlockUserAccountResponse) ResponseRequestTypeName() string { return "UnlockUserAccount" }
