// Code generated by admgen; DO NOT EDIT.
// Source: apple/device-management@67045e2fa06f528b196c01edee6a8bf88b844beb

package errors

import (
	"github.com/deploymenttheory/go-apple-mdm/schema/support"
	"github.com/deploymenttheory/go-apple-mdm/schema/validation"
)

// Validate checks x against the schema. With a non-zero target it also checks
// that every present key is supported on that OS version and enrollment context.
func (x *CodePlatformSSORequired) Validate(t support.Target) error {
	c := validation.New(t)
	x.validate(c, "")
	return c.Err()
}

func (x *CodePlatformSSORequired) validate(c *validation.Collector, p string) {
	{
		path := validation.Join(p, "code")
		present := x.Code != ""
		_, _ = path, present
		c.Support(path, present, supportTable["CodePlatformSSORequired.code"])
		c.Required(path, present)
		if present {
			c.Enum(path, true, x.Code, []any{"com.apple.psso.required"})
		}
	}
	{
		path := validation.Join(p, "description")
		present := x.Description != nil
		_, _ = path, present
		c.Support(path, present, supportTable["CodePlatformSSORequired.description"])
	}
	{
		path := validation.Join(p, "message")
		present := x.Message != nil
		_, _ = path, present
		c.Support(path, present, supportTable["CodePlatformSSORequired.message"])
	}
	{
		path := validation.Join(p, "details")
		present := true
		_, _ = path, present
		c.Support(path, present, supportTable["CodePlatformSSORequired.details"])
		c.Required(path, present)
		if present {
			x.Details.validate(c, path)
		}
	}
}

func (x *CodePlatformSSORequiredDetails) validate(c *validation.Collector, p string) {
	{
		path := validation.Join(p, "ProfileURL")
		present := x.ProfileURL != ""
		_, _ = path, present
		c.Support(path, present, supportTable["CodePlatformSSORequired.details.ProfileURL"])
		c.Required(path, present)
	}
	{
		path := validation.Join(p, "Package")
		present := true
		_, _ = path, present
		c.Support(path, present, supportTable["CodePlatformSSORequired.details.Package"])
		c.Required(path, present)
		if present {
			x.Package.validate(c, path)
		}
	}
	{
		path := validation.Join(p, "AuthURL")
		present := x.AuthURL != ""
		_, _ = path, present
		c.Support(path, present, supportTable["CodePlatformSSORequired.details.AuthURL"])
		c.Required(path, present)
	}
}

func (x *CodePlatformSSORequiredDetailsPackage) validate(c *validation.Collector, p string) {
	{
		path := validation.Join(p, "ManifestURL")
		present := x.ManifestURL != ""
		_, _ = path, present
		c.Support(path, present, supportTable["CodePlatformSSORequired.details.Package.ManifestURL"])
		c.Required(path, present)
	}
	{
		path := validation.Join(p, "PinningCerts")
		present := len(x.PinningCerts) > 0
		_, _ = path, present
		c.Support(path, present, supportTable["CodePlatformSSORequired.details.Package.PinningCerts"])
	}
	{
		path := validation.Join(p, "PinningRevocationCheckRequired")
		present := x.PinningRevocationCheckRequired != nil
		_, _ = path, present
		c.Support(path, present, supportTable["CodePlatformSSORequired.details.Package.PinningRevocationCheckRequired"])
	}
}

// Validate checks x against the schema. With a non-zero target it also checks
// that every present key is supported on that OS version and enrollment context.
func (x *CodeSoftwareUpdateRequired) Validate(t support.Target) error {
	c := validation.New(t)
	x.validate(c, "")
	return c.Err()
}

func (x *CodeSoftwareUpdateRequired) validate(c *validation.Collector, p string) {
	{
		path := validation.Join(p, "code")
		present := x.Code != ""
		_, _ = path, present
		c.Support(path, present, supportTable["CodeSoftwareUpdateRequired.code"])
		c.Required(path, present)
		if present {
			c.Enum(path, true, x.Code, []any{"com.apple.softwareupdate.required"})
		}
	}
	{
		path := validation.Join(p, "description")
		present := x.Description != nil
		_, _ = path, present
		c.Support(path, present, supportTable["CodeSoftwareUpdateRequired.description"])
	}
	{
		path := validation.Join(p, "message")
		present := x.Message != nil
		_, _ = path, present
		c.Support(path, present, supportTable["CodeSoftwareUpdateRequired.message"])
	}
	{
		path := validation.Join(p, "details")
		present := true
		_, _ = path, present
		c.Support(path, present, supportTable["CodeSoftwareUpdateRequired.details"])
		c.Required(path, present)
		if present {
			x.Details.validate(c, path)
		}
	}
}

func (x *CodeSoftwareUpdateRequiredDetails) validate(c *validation.Collector, p string) {
	{
		path := validation.Join(p, "OSVersion")
		present := x.OSVersion != ""
		_, _ = path, present
		c.Support(path, present, supportTable["CodeSoftwareUpdateRequired.details.OSVersion"])
		c.Required(path, present)
	}
	{
		path := validation.Join(p, "BuildVersion")
		present := x.BuildVersion != nil
		_, _ = path, present
		c.Support(path, present, supportTable["CodeSoftwareUpdateRequired.details.BuildVersion"])
	}
	{
		path := validation.Join(p, "RequireBetaProgram")
		present := x.RequireBetaProgram != nil
		_, _ = path, present
		c.Support(path, present, supportTable["CodeSoftwareUpdateRequired.details.RequireBetaProgram"])
		if present {
			x.RequireBetaProgram.validate(c, path)
		}
	}
}

func (x *CodeSoftwareUpdateRequiredDetailsRequireBetaProgram) validate(c *validation.Collector, p string) {
	{
		path := validation.Join(p, "Description")
		present := x.Description != ""
		_, _ = path, present
		c.Support(path, present, supportTable["CodeSoftwareUpdateRequired.details.RequireBetaProgram.Description"])
		c.Required(path, present)
	}
	{
		path := validation.Join(p, "Token")
		present := x.Token != ""
		_, _ = path, present
		c.Support(path, present, supportTable["CodeSoftwareUpdateRequired.details.RequireBetaProgram.Token"])
		c.Required(path, present)
	}
}

// Validate checks x against the schema. With a non-zero target it also checks
// that every present key is supported on that OS version and enrollment context.
func (x *UnrecognizedDevice) Validate(t support.Target) error {
	c := validation.New(t)
	x.validate(c, "")
	return c.Err()
}

func (x *UnrecognizedDevice) validate(c *validation.Collector, p string) {
	{
		path := validation.Join(p, "code")
		present := x.Code != ""
		_, _ = path, present
		c.Support(path, present, supportTable["UnrecognizedDevice.code"])
		c.Required(path, present)
		if present {
			c.Enum(path, true, x.Code, []any{"com.apple.unrecognized.device"})
		}
	}
	{
		path := validation.Join(p, "description")
		present := x.Description != nil
		_, _ = path, present
		c.Support(path, present, supportTable["UnrecognizedDevice.description"])
	}
	{
		path := validation.Join(p, "message")
		present := x.Message != nil
		_, _ = path, present
		c.Support(path, present, supportTable["UnrecognizedDevice.message"])
	}
}

// Validate checks x against the schema. With a non-zero target it also checks
// that every present key is supported on that OS version and enrollment context.
func (x *CodePairingTokenMissing) Validate(t support.Target) error {
	c := validation.New(t)
	x.validate(c, "")
	return c.Err()
}

func (x *CodePairingTokenMissing) validate(c *validation.Collector, p string) {
	{
		path := validation.Join(p, "code")
		present := x.Code != ""
		_, _ = path, present
		c.Support(path, present, supportTable["CodePairingTokenMissing.code"])
		c.Required(path, present)
		if present {
			c.Enum(path, true, x.Code, []any{"com.apple.watch.pairing.token.missing"})
		}
	}
	{
		path := validation.Join(p, "description")
		present := x.Description != nil
		_, _ = path, present
		c.Support(path, present, supportTable["CodePairingTokenMissing.description"])
	}
	{
		path := validation.Join(p, "message")
		present := x.Message != nil
		_, _ = path, present
		c.Support(path, present, supportTable["CodePairingTokenMissing.message"])
	}
	{
		path := validation.Join(p, "details")
		present := true
		_, _ = path, present
		c.Support(path, present, supportTable["CodePairingTokenMissing.details"])
		c.Required(path, present)
		if present {
			x.Details.validate(c, path)
		}
	}
}

func (x *CodePairingTokenMissingDetails) validate(c *validation.Collector, p string) {
	{
		path := validation.Join(p, "security-token")
		present := x.SecurityToken != ""
		_, _ = path, present
		c.Support(path, present, supportTable["CodePairingTokenMissing.details.security-token"])
		c.Required(path, present)
	}
}

// Validate checks x against the schema. With a non-zero target it also checks
// that every present key is supported on that OS version and enrollment context.
func (x *WellKnownFailed) Validate(t support.Target) error {
	c := validation.New(t)
	x.validate(c, "")
	return c.Err()
}

func (x *WellKnownFailed) validate(c *validation.Collector, p string) {
	{
		path := validation.Join(p, "code")
		present := x.Code != ""
		_, _ = path, present
		c.Support(path, present, supportTable["WellKnownFailed.code"])
		c.Required(path, present)
		if present {
			c.Enum(path, true, x.Code, []any{"com.apple.well-known.failed"})
		}
	}
	{
		path := validation.Join(p, "description")
		present := x.Description != nil
		_, _ = path, present
		c.Support(path, present, supportTable["WellKnownFailed.description"])
	}
	{
		path := validation.Join(p, "message")
		present := x.Message != nil
		_, _ = path, present
		c.Support(path, present, supportTable["WellKnownFailed.message"])
	}
}
